# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -mtriple=mos -run-pass=branch-relaxation -verify-machineinstrs -o - %s | FileCheck %s
---
name: far_branch
body: |
  ; CHECK-LABEL: name: far_branch
  ; CHECK: bb.0.entry:
  ; CHECK:   successors: %bb.1(0x80000000)
  ; CHECK:   JMP %bb.1
  ; CHECK: bb.1:
  ; CHECK:   successors: %bb.1(0x40000000), %bb.2(0x40000000)
  ; CHECK:   $a = LDImm 0
  ; CHECK:   $a = LDImm 0
  ; CHECK:   $a = LDImm 0
  ; CHECK:   $a = LDImm 0
  ; CHECK:   $a = LDImm 0
  ; CHECK:   $a = LDImm 0
  ; CHECK:   $a = LDImm 0
  ; CHECK:   $a = LDImm 0
  ; CHECK:   $a = LDImm 0
  ; CHECK:   $a = LDImm 0
  ; CHECK:   $a = LDImm 0
  ; CHECK:   $a = LDImm 0
  ; CHECK:   $a = LDImm 0
  ; CHECK:   $a = LDImm 0
  ; CHECK:   $a = LDImm 0
  ; CHECK:   $a = LDImm 0
  ; CHECK:   $a = LDImm 0
  ; CHECK:   $a = LDImm 0
  ; CHECK:   $a = LDImm 0
  ; CHECK:   $a = LDImm 0
  ; CHECK:   $a = LDImm 0
  ; CHECK:   $a = LDImm 0
  ; CHECK:   $a = LDImm 0
  ; CHECK:   $a = LDImm 0
  ; CHECK:   $a = LDImm 0
  ; CHECK:   $a = LDImm 0
  ; CHECK:   $a = LDImm 0
  ; CHECK:   $a = LDImm 0
  ; CHECK:   $a = LDImm 0
  ; CHECK:   $a = LDImm 0
  ; CHECK:   $a = LDImm 0
  ; CHECK:   $a = LDImm 0
  ; CHECK:   $a = LDImm 0
  ; CHECK:   $a = LDImm 0
  ; CHECK:   $a = LDImm 0
  ; CHECK:   $a = LDImm 0
  ; CHECK:   $a = LDImm 0
  ; CHECK:   $a = LDImm 0
  ; CHECK:   $a = LDImm 0
  ; CHECK:   $a = LDImm 0
  ; CHECK:   $a = LDImm 0
  ; CHECK:   $a = LDImm 0
  ; CHECK:   $a = LDImm 0
  ; CHECK:   BR %bb.2, $c, 1
  ; CHECK:   JMP %bb.1
  ; CHECK: bb.2:
  ; CHECK:   RTS
  bb.0.entry:
    liveins: $c
    JMP %bb.1

  bb.1:
    liveins: $c
    $a = LDImm 0
    $a = LDImm 0
    $a = LDImm 0
    $a = LDImm 0
    $a = LDImm 0
    $a = LDImm 0
    $a = LDImm 0
    $a = LDImm 0
    $a = LDImm 0
    $a = LDImm 0
    $a = LDImm 0
    $a = LDImm 0
    $a = LDImm 0
    $a = LDImm 0
    $a = LDImm 0
    $a = LDImm 0
    $a = LDImm 0
    $a = LDImm 0
    $a = LDImm 0
    $a = LDImm 0
    $a = LDImm 0
    $a = LDImm 0
    $a = LDImm 0
    $a = LDImm 0
    $a = LDImm 0
    $a = LDImm 0
    $a = LDImm 0
    $a = LDImm 0
    $a = LDImm 0
    $a = LDImm 0
    $a = LDImm 0
    $a = LDImm 0
    $a = LDImm 0
    $a = LDImm 0
    $a = LDImm 0
    $a = LDImm 0
    $a = LDImm 0
    $a = LDImm 0
    $a = LDImm 0
    $a = LDImm 0
    $a = LDImm 0
    $a = LDImm 0
    $a = LDImm 0
    BR %bb.1, $c, 0

  bb.2:
    RTS
...
