# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -mtriple=mos -run-pass=branch-relaxation -verify-machineinstrs -o - %s | FileCheck %s
---
name: far_branch
body: |
  ; CHECK-LABEL: name: far_branch
  ; CHECK: bb.0.entry:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT:   liveins: $c
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   JMP %bb.1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.1(0x40000000), %bb.2(0x40000000)
  ; CHECK-NEXT:   liveins: $c
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   INLINEASM &"lda #0\0Alda #0\0Alda #0\0Alda #0\0Alda #0\0Alda #0\0Alda #0\0Alda #0\0Alda #0\0Alda #0\0Alda #0\0Alda #0\0Alda #0\0Alda #0\0Alda #0\0Alda #0\0Alda #0\0Alda #0\0Alda #0\0Alda #0\0Alda #0\0Alda #0\0Alda #0\0Alda #0\0Alda #0\0Alda #0\0Alda #0\0Alda #0\0Alda #0\0Alda #0\0Alda #0\0Alda #0\0Alda #0\0Alda #0\0Alda #0\0Alda #0\0Alda #0\0Alda #0\0Alda #0\0Alda #0\0Alda #0\0Alda #0\0Alda #0\0Alda #0\0Alda #0\0Alda #0\0Alda #0\0Alda #0\0Alda #0\0Alda #0\0Alda #0\0Alda #0\0Alda #0\0Alda #0\0Alda #0\0Alda #0\0Alda #0\0Alda #0\0Alda #0\0Alda #0\0Alda #0\0Alda #0\0Alda #0\0Alda #0\0A", sideeffect attdialect
  ; CHECK-NEXT:   BR %bb.2, $c, 1
  ; CHECK-NEXT:   JMP %bb.1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   RTS
  bb.0.entry:
    liveins: $c
    JMP %bb.1

  bb.1:
    liveins: $c
    INLINEASM &"lda #0\0Alda #0\0Alda #0\0Alda #0\0Alda #0\0Alda #0\0Alda #0\0Alda #0\0Alda #0\0Alda #0\0Alda #0\0Alda #0\0Alda #0\0Alda #0\0Alda #0\0Alda #0\0Alda #0\0Alda #0\0Alda #0\0Alda #0\0Alda #0\0Alda #0\0Alda #0\0Alda #0\0Alda #0\0Alda #0\0Alda #0\0Alda #0\0Alda #0\0Alda #0\0Alda #0\0Alda #0\0Alda #0\0Alda #0\0Alda #0\0Alda #0\0Alda #0\0Alda #0\0Alda #0\0Alda #0\0Alda #0\0Alda #0\0Alda #0\0Alda #0\0Alda #0\0Alda #0\0Alda #0\0Alda #0\0Alda #0\0Alda #0\0Alda #0\0Alda #0\0Alda #0\0Alda #0\0Alda #0\0Alda #0\0Alda #0\0Alda #0\0Alda #0\0Alda #0\0Alda #0\0Alda #0\0Alda #0\0Alda #0\0A", 1 /* sideeffect attdialect */
    BR %bb.1, $c, 0

  bb.2:
    RTS
...
