# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -mtriple=mos -mcpu=mos65c02 -run-pass=branch-relaxation -verify-machineinstrs -o - %s | FileCheck %s
---
name: far_branch
tracksRegLiveness: true
body: |
  ; CHECK-LABEL: name: far_branch
  ; CHECK: bb.0.entry:
  ; CHECK:   successors: %bb.1(0x80000000)
  ; CHECK:   BRA %bb.1
  ; CHECK: bb.1:
  ; CHECK:   successors: %bb.1(0x80000000)
  ; CHECK:   $a = LDImm 0
  ; CHECK:   $a = LDImm 0
  ; CHECK:   $a = LDImm 0
  ; CHECK:   $a = LDImm 0
  ; CHECK:   $a = LDImm 0
  ; CHECK:   $a = LDImm 0
  ; CHECK:   $a = LDImm 0
  ; CHECK:   $a = LDImm 0
  ; CHECK:   $a = LDImm 0
  ; CHECK:   $a = LDImm 0
  ; CHECK:   $a = LDImm 0
  ; CHECK:   $a = LDImm 0
  ; CHECK:   $a = LDImm 0
  ; CHECK:   $a = LDImm 0
  ; CHECK:   $a = LDImm 0
  ; CHECK:   $a = LDImm 0
  ; CHECK:   $a = LDImm 0
  ; CHECK:   $a = LDImm 0
  ; CHECK:   $a = LDImm 0
  ; CHECK:   $a = LDImm 0
  ; CHECK:   $a = LDImm 0
  ; CHECK:   $a = LDImm 0
  ; CHECK:   $a = LDImm 0
  ; CHECK:   $a = LDImm 0
  ; CHECK:   $a = LDImm 0
  ; CHECK:   $a = LDImm 0
  ; CHECK:   $a = LDImm 0
  ; CHECK:   $a = LDImm 0
  ; CHECK:   $a = LDImm 0
  ; CHECK:   $a = LDImm 0
  ; CHECK:   $a = LDImm 0
  ; CHECK:   $a = LDImm 0
  ; CHECK:   $a = LDImm 0
  ; CHECK:   $a = LDImm 0
  ; CHECK:   $a = LDImm 0
  ; CHECK:   $a = LDImm 0
  ; CHECK:   $a = LDImm 0
  ; CHECK:   $a = LDImm 0
  ; CHECK:   $a = LDImm 0
  ; CHECK:   $a = LDImm 0
  ; CHECK:   $a = LDImm 0
  ; CHECK:   $a = LDImm 0
  ; CHECK:   BRA %bb.1
  ; CHECK: bb.2:
  ; CHECK:   successors: %bb.4(0x80000000)
  ; CHECK:   $a = LDImm 0
  ; CHECK: bb.4:
  ; CHECK:   successors: %bb.1(0x80000000)
  ; CHECK:   JMP %bb.1
  ; CHECK: bb.3:
  ; CHECK:   RTS
  bb.0.entry:
    BRA %bb.1

  bb.1:
    $a = LDImm 0
    $a = LDImm 0
    $a = LDImm 0
    $a = LDImm 0
    $a = LDImm 0
    $a = LDImm 0
    $a = LDImm 0
    $a = LDImm 0
    $a = LDImm 0
    $a = LDImm 0
    $a = LDImm 0
    $a = LDImm 0
    $a = LDImm 0
    $a = LDImm 0
    $a = LDImm 0
    $a = LDImm 0
    $a = LDImm 0
    $a = LDImm 0
    $a = LDImm 0
    $a = LDImm 0
    $a = LDImm 0
    $a = LDImm 0
    $a = LDImm 0
    $a = LDImm 0
    $a = LDImm 0
    $a = LDImm 0
    $a = LDImm 0
    $a = LDImm 0
    $a = LDImm 0
    $a = LDImm 0
    $a = LDImm 0
    $a = LDImm 0
    $a = LDImm 0
    $a = LDImm 0
    $a = LDImm 0
    $a = LDImm 0
    $a = LDImm 0
    $a = LDImm 0
    $a = LDImm 0
    $a = LDImm 0
    $a = LDImm 0
    $a = LDImm 0
    ; This BRA is kept
    BRA %bb.1

  bb.2:
    $a = LDImm 0
    ; This BRA is relaxed to JMP
    BRA %bb.1

  bb.3:
    RTS
...
