; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -verify-machineinstrs < %s | FileCheck %s -check-prefix=NMOS
; RUN: llc -mcpu=mos65c02 -verify-machineinstrs < %s | FileCheck %s -check-prefix=CMOS

target datalayout = "e-p:16:8:8-p1:8:8-i16:8:8-i32:8:8-i64:8:8-f32:8:8-f64:8:8-a:8:8-Fi8-n8"
target triple = "mos"

; Function Attrs: nounwind optsize
define void @char_stats() local_unnamed_addr #0 {
; NMOS-LABEL: char_stats:
; NMOS:       ; %bb.0: ; %entry
; NMOS-NEXT:    lda __rc20
; NMOS-NEXT:    pha
; NMOS-NEXT:    lda __rc21
; NMOS-NEXT:    pha
; NMOS-NEXT:    lda __rc22
; NMOS-NEXT:    pha
; NMOS-NEXT:    ldx #mos16lo(.Lchar_stats_sstk)
; NMOS-NEXT:    ldy #mos16hi(.Lchar_stats_sstk)
; NMOS-NEXT:    stx __rc20
; NMOS-NEXT:    sty __rc21
; NMOS-NEXT:    stx __rc2
; NMOS-NEXT:    sty __rc3
; NMOS-NEXT:    ldx #2
; NMOS-NEXT:    stx __rc4
; NMOS-NEXT:    ldx #0
; NMOS-NEXT:    ldy #0
; NMOS-NEXT:    sty __rc22
; NMOS-NEXT:    tya
; NMOS-NEXT:    jsr __memset
; NMOS-NEXT:  .LBB0_1: ; %while.body
; NMOS-NEXT:    ; =>This Inner Loop Header: Depth=1
; NMOS-NEXT:    jsr next_char
; NMOS-NEXT:    tax
; NMOS-NEXT:    beq .LBB0_5
; NMOS-NEXT:  ; %bb.2: ; %while.body
; NMOS-NEXT:    ; in Loop: Header=BB0_1 Depth=1
; NMOS-NEXT:    asl
; NMOS-NEXT:    sta __rc2
; NMOS-NEXT:    lda __rc22
; NMOS-NEXT:    rol
; NMOS-NEXT:    sta __rc3
; NMOS-NEXT:    lda #mos16lo(.Lchar_stats_sstk)
; NMOS-NEXT:    clc
; NMOS-NEXT:    adc __rc2
; NMOS-NEXT:    sta __rc2
; NMOS-NEXT:    lda #mos16hi(.Lchar_stats_sstk)
; NMOS-NEXT:    adc __rc3
; NMOS-NEXT:    sta __rc3
; NMOS-NEXT:    ldy #0
; NMOS-NEXT:    lda (__rc2),y
; NMOS-NEXT:    sta __rc6
; NMOS-NEXT:    sty __rc4
; NMOS-NEXT:    iny
; NMOS-NEXT:    lda (__rc2),y
; NMOS-NEXT:    tax
; NMOS-NEXT:    sty __rc5
; NMOS-NEXT:    lda __rc6
; NMOS-NEXT:    clc
; NMOS-NEXT:    adc #1
; NMOS-NEXT:    bne .LBB0_4
; NMOS-NEXT:  ; %bb.3: ; %while.body
; NMOS-NEXT:    ; in Loop: Header=BB0_1 Depth=1
; NMOS-NEXT:    inx
; NMOS-NEXT:  .LBB0_4: ; %while.body
; NMOS-NEXT:    ; in Loop: Header=BB0_1 Depth=1
; NMOS-NEXT:    ldy __rc4
; NMOS-NEXT:    sta (__rc2),y
; NMOS-NEXT:    txa
; NMOS-NEXT:    ldy __rc5
; NMOS-NEXT:    sta (__rc2),y
; NMOS-NEXT:    jmp .LBB0_1
; NMOS-NEXT:  .LBB0_5: ; %while.end
; NMOS-NEXT:    ldx __rc20
; NMOS-NEXT:    stx __rc2
; NMOS-NEXT:    ldx __rc21
; NMOS-NEXT:    stx __rc3
; NMOS-NEXT:    jsr report_counts
; NMOS-NEXT:    pla
; NMOS-NEXT:    sta __rc22
; NMOS-NEXT:    pla
; NMOS-NEXT:    sta __rc21
; NMOS-NEXT:    pla
; NMOS-NEXT:    sta __rc20
; NMOS-NEXT:    rts
;
; CMOS-LABEL: char_stats:
; CMOS:       ; %bb.0: ; %entry
; CMOS-NEXT:    ldx __rc20
; CMOS-NEXT:    phx
; CMOS-NEXT:    ldx __rc21
; CMOS-NEXT:    phx
; CMOS-NEXT:    ldx #mos16lo(.Lchar_stats_sstk)
; CMOS-NEXT:    ldy #mos16hi(.Lchar_stats_sstk)
; CMOS-NEXT:    stx __rc20
; CMOS-NEXT:    sty __rc21
; CMOS-NEXT:    stx __rc2
; CMOS-NEXT:    sty __rc3
; CMOS-NEXT:    lda #0
; CMOS-NEXT:    ldx #2
; CMOS-NEXT:    stx __rc4
; CMOS-NEXT:    tax
; CMOS-NEXT:    jsr __memset
; CMOS-NEXT:  .LBB0_1: ; %while.body
; CMOS-NEXT:    ; =>This Inner Loop Header: Depth=1
; CMOS-NEXT:    jsr next_char
; CMOS-NEXT:    tax
; CMOS-NEXT:    beq .LBB0_5
; CMOS-NEXT:  ; %bb.2: ; %while.body
; CMOS-NEXT:    ; in Loop: Header=BB0_1 Depth=1
; CMOS-NEXT:    asl
; CMOS-NEXT:    sta __rc2
; CMOS-NEXT:    lda #0
; CMOS-NEXT:    rol
; CMOS-NEXT:    sta __rc3
; CMOS-NEXT:    lda #mos16lo(.Lchar_stats_sstk)
; CMOS-NEXT:    clc
; CMOS-NEXT:    adc __rc2
; CMOS-NEXT:    sta __rc2
; CMOS-NEXT:    lda #mos16hi(.Lchar_stats_sstk)
; CMOS-NEXT:    adc __rc3
; CMOS-NEXT:    sta __rc3
; CMOS-NEXT:    lda (__rc2)
; CMOS-NEXT:    sta __rc4
; CMOS-NEXT:    ldy #1
; CMOS-NEXT:    lda (__rc2),y
; CMOS-NEXT:    tax
; CMOS-NEXT:    lda __rc4
; CMOS-NEXT:    inc
; CMOS-NEXT:    bne .LBB0_4
; CMOS-NEXT:  ; %bb.3: ; %while.body
; CMOS-NEXT:    ; in Loop: Header=BB0_1 Depth=1
; CMOS-NEXT:    inx
; CMOS-NEXT:  .LBB0_4: ; %while.body
; CMOS-NEXT:    ; in Loop: Header=BB0_1 Depth=1
; CMOS-NEXT:    sta (__rc2)
; CMOS-NEXT:    txa
; CMOS-NEXT:    sta (__rc2),y
; CMOS-NEXT:    bra .LBB0_1
; CMOS-NEXT:  .LBB0_5: ; %while.end
; CMOS-NEXT:    ldx __rc20
; CMOS-NEXT:    stx __rc2
; CMOS-NEXT:    ldx __rc21
; CMOS-NEXT:    stx __rc3
; CMOS-NEXT:    jsr report_counts
; CMOS-NEXT:    plx
; CMOS-NEXT:    stx __rc21
; CMOS-NEXT:    plx
; CMOS-NEXT:    stx __rc20
; CMOS-NEXT:    rts
entry:
  %counts = alloca [256 x i16], align 1
  %0 = bitcast [256 x i16]* %counts to i8*
  call void @llvm.lifetime.start.p0i8(i64 512, i8* nonnull %0) #4
  call void @llvm.memset.p0i8.i16(i8* nonnull align 1 dereferenceable(512) %0, i8 0, i16 512, i1 false)
  %call1 = tail call zeroext i8 bitcast (i8 (...)* @next_char to i8 ()*)() #5
  %tobool.not2 = icmp eq i8 %call1, 0
  br i1 %tobool.not2, label %while.end, label %while.body

while.body:                                       ; preds = %entry, %while.body
  %call3 = phi i8 [ %call, %while.body ], [ %call1, %entry ]
  %idxprom = zext i8 %call3 to i16
  %arrayidx = getelementptr inbounds [256 x i16], [256 x i16]* %counts, i16 0, i16 %idxprom
  %1 = load i16, i16* %arrayidx, align 1, !tbaa !2
  %inc = add nsw i16 %1, 1
  store i16 %inc, i16* %arrayidx, align 1, !tbaa !2
  %call = tail call zeroext i8 bitcast (i8 (...)* @next_char to i8 ()*)() #5
  %tobool.not = icmp eq i8 %call, 0
  br i1 %tobool.not, label %while.end, label %while.body, !llvm.loop !6

while.end:                                        ; preds = %while.body, %entry
  %arraydecay = getelementptr inbounds [256 x i16], [256 x i16]* %counts, i16 0, i16 0
  call void @report_counts(i16* nonnull %arraydecay) #5
  call void @llvm.lifetime.end.p0i8(i64 512, i8* nonnull %0) #4
  ret void
}

; Function Attrs: argmemonly nofree nosync nounwind willreturn
declare void @llvm.lifetime.start.p0i8(i64 immarg, i8* nocapture) #1

; Function Attrs: argmemonly nofree nosync nounwind willreturn writeonly
declare void @llvm.memset.p0i8.i16(i8* nocapture writeonly, i8, i16, i1 immarg) #2

; Function Attrs: nocallback optsize
declare zeroext i8 @next_char(...) local_unnamed_addr #3

; Function Attrs: nocallback optsize
declare void @report_counts(i16*) local_unnamed_addr #3

; Function Attrs: argmemonly nofree nosync nounwind willreturn
declare void @llvm.lifetime.end.p0i8(i64 immarg, i8* nocapture) #1

attributes #0 = { nounwind optsize "disable-tail-calls"="false" "frame-pointer"="all" "less-precise-fpmad"="false" "min-legal-vector-width"="0" "no-infs-fp-math"="false" "no-jump-tables"="false" "no-nans-fp-math"="false" "no-signed-zeros-fp-math"="false" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "unsafe-fp-math"="false" "use-soft-float"="false" }
attributes #1 = { argmemonly nofree nosync nounwind willreturn }
attributes #2 = { argmemonly nofree nosync nounwind willreturn writeonly }
attributes #3 = { nocallback optsize "disable-tail-calls"="false" "frame-pointer"="all" "less-precise-fpmad"="false" "no-infs-fp-math"="false" "no-nans-fp-math"="false" "no-signed-zeros-fp-math"="false" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "unsafe-fp-math"="false" "use-soft-float"="false" }
attributes #4 = { nounwind }
attributes #5 = { nocallback nounwind optsize }

!llvm.module.flags = !{!0}
!llvm.ident = !{!1}

!0 = !{i32 1, !"wchar_size", i32 4}
!1 = !{!"clang version 12.0.0 (git@github.com:mysterymath/clang6502.git 948c84f839c7884dc9f820cf333312348759050e)"}
!2 = !{!3, !3, i64 0}
!3 = !{!"int", !4, i64 0}
!4 = !{!"omnipotent char", !5, i64 0}
!5 = !{!"Simple C/C++ TBAA"}
!6 = distinct !{!6, !7}
!7 = !{!"llvm.loop.mustprogress"}
