; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=mos -verify-machineinstrs < %s | FileCheck %s

define i8 @cmp_select(i8 %a, i8 %b) {
; CHECK-LABEL: cmp_select:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    tay
; CHECK-NEXT:    stx __rc2
; CHECK-NEXT:    lda #1
; CHECK-NEXT:    cpy __rc2
; CHECK-NEXT:    beq .LBB0_2
; CHECK-NEXT:  ; %bb.1: ; %select.false
; CHECK-NEXT:    lda #2
; CHECK-NEXT:  .LBB0_2: ; %select.end
; CHECK-NEXT:    rts
entry:
  %cmp = icmp eq i8 %a, %b
  %sel = select i1 %cmp, i8 1, i8 2
  ret i8 %sel
}
