; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -verify-machineinstrs -o - %s | FileCheck %s

; ModuleID = 'crabquest.dd71e8b8-cgu.0'
source_filename = "crabquest.dd71e8b8-cgu.0"
target datalayout = "e-m:e-p:16:8-p1:8:8-i16:8-i32:8-i64:8-f32:8-f64:8-a:8-Fi8-n8"
target triple = "mos-unknown-none"

@_ZN9crabquest9NAMETABLE17hd51a107367afa20aE = constant <{ [1024 x i8] }> <{ [1024 x i8] c"\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\01\02\03\04\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\01\02\03\04\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\01\02\03\04\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\01\02\03\04\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\01\02\03\04\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\01\02\03\04\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\01\02\03\04\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\01\02\03\04\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\01\02\03\04\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00" }>, align 1

; crabquest::write_nametable
; Function Attrs: nofree noinline norecurse noredzone nounwind optsize
define fastcc void @_ZN9crabquest15write_nametable17h6fe548716a276623E() unnamed_addr #0 {
; CHECK-LABEL: _ZN9crabquest15write_nametable17h6fe548716a276623E:
; CHECK:       ; %bb.0: ; %start
; CHECK-NEXT:    ldx #32
; CHECK-NEXT:    stx 8198
; CHECK-NEXT:    ldy #0
; CHECK-NEXT:    sty 8198
; CHECK-NEXT:    ldx #mos16lo(_ZN9crabquest9NAMETABLE17hd51a107367afa20aE)
; CHECK-NEXT:    stx __rc2
; CHECK-NEXT:    ldx #mos16hi(_ZN9crabquest9NAMETABLE17hd51a107367afa20aE)
; CHECK-NEXT:    stx __rc3
; CHECK-NEXT:    lda #4
; CHECK-NEXT:    ldx #0
; CHECK-NEXT:    sta __rc4
; CHECK-NEXT:  .LBB0_1: ; %bb6
; CHECK-NEXT:    ; =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    lda (__rc2),y
; CHECK-NEXT:    inc __rc2
; CHECK-NEXT:    bne .LBB0_3
; CHECK-NEXT:  ; %bb.2: ; %bb6
; CHECK-NEXT:    ; in Loop: Header=BB0_1 Depth=1
; CHECK-NEXT:    inc __rc3
; CHECK-NEXT:  .LBB0_3: ; %bb6
; CHECK-NEXT:    ; in Loop: Header=BB0_1 Depth=1
; CHECK-NEXT:    sta 8199
; CHECK-NEXT:    dex
; CHECK-NEXT:    cpx #255
; CHECK-NEXT:    bne .LBB0_5
; CHECK-NEXT:  ; %bb.4: ; %bb6
; CHECK-NEXT:    ; in Loop: Header=BB0_1 Depth=1
; CHECK-NEXT:    dec __rc4
; CHECK-NEXT:  .LBB0_5: ; %bb6
; CHECK-NEXT:    ; in Loop: Header=BB0_1 Depth=1
; CHECK-NEXT:    lda __rc4
; CHECK-NEXT:    bne .LBB0_1
; CHECK-NEXT:  ; %bb.6: ; %bb6
; CHECK-NEXT:    ; in Loop: Header=BB0_1 Depth=1
; CHECK-NEXT:    txa
; CHECK-NEXT:    bne .LBB0_1
; CHECK-NEXT:  ; %bb.7: ; %bb8
; CHECK-NEXT:    rts
start:
  store volatile i8 32, ptr inttoptr (i16 8198 to ptr), align 2
  store volatile i8 0, ptr inttoptr (i16 8198 to ptr), align 2
  br label %bb6

bb8:                                              ; preds = %bb6
  ret void

bb6:                                              ; preds = %start, %bb6
  %iter.sroa.0.03 = phi ptr [ @_ZN9crabquest9NAMETABLE17hd51a107367afa20aE, %start ], [ %0, %bb6 ]
  %0 = getelementptr inbounds i8, ptr %iter.sroa.0.03, i16 1
  %byte = load i8, ptr %iter.sroa.0.03, align 1
  store volatile i8 %byte, ptr inttoptr (i16 8199 to ptr), align 1
  %_12.i = icmp eq ptr %0, getelementptr inbounds (<{ [1024 x i8] }>, ptr @_ZN9crabquest9NAMETABLE17hd51a107367afa20aE, i16 1, i32 0, i16 0)
  br i1 %_12.i, label %bb8, label %bb6
}

attributes #0 = { nofree noinline norecurse noredzone nounwind optsize "target-cpu"="mos6502" }

!llvm.module.flags = !{!0, !1, !2}

!0 = !{i32 7, !"PIC Level", i32 2}
!1 = !{i32 7, !"PIE Level", i32 2}
!2 = !{i32 1, !"LTOPostLink", i32 1}
