# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -mtriple=mos -run-pass=twoaddressinstruction -verify-machineinstrs -o - %s | FileCheck %s
---
name: ADCImag8
body: |
  bb.0.entry:
    liveins: $c
    ; CHECK-LABEL: name: ADCImag8
    ; CHECK: liveins: $c
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:imag8 = COPY $x
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:ac = COPY $y
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:cc = COPY $v
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:ac = COPY [[COPY1]]
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:ac, dead [[ADCImag8_:%[0-9]+]]:cc, dead [[ADCImag8_1:%[0-9]+]]:vc = ADCImag8 [[COPY3]], [[COPY]], [[COPY2]]
    ; CHECK-NEXT: RTS implicit [[COPY]], implicit [[COPY3]]
    %0:ac = COPY $x
    %1:imag8 = COPY $y
    %2:cc = COPY $v
    %3:ac, dead %4:cc, dead %5:vc = ADCImag8 %0, killed %1, %2
    RTS implicit %0, implicit %3
...
---
name: ADCImag8_avoid_commuting_if_preferable
body: |
  bb.0.entry:
    liveins: $c
    ; CHECK-LABEL: name: ADCImag8_avoid_commuting_if_preferable
    ; CHECK: liveins: $c
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:ac = COPY $a
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:imag8 = COPY $x
    ; CHECK-NEXT: [[LDImm1_:%[0-9]+]]:cc = LDImm1 0
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:ac = COPY [[COPY]]
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:ac, [[ADCImag8_:%[0-9]+]]:cc, dead [[ADCImag8_1:%[0-9]+]]:vc = ADCImag8 [[COPY2]], killed [[COPY1]], killed [[LDImm1_]]
    ; CHECK-NEXT: RTS implicit [[ADCImag8_]]
    %0:ac = COPY $a
    %1:imag8 = COPY $x
    %2:cc = LDImm1 0
    %3:ac, %4:cc, dead %5:vc = ADCImag8 killed %0, killed %1, killed %2
    RTS implicit %4
...
---
name: ANDImag8
body: |
  bb.0.entry:
    liveins: $c
    ; CHECK-LABEL: name: ANDImag8
    ; CHECK: liveins: $c
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:imag8 = COPY $x
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:ac = COPY $y
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:ac = COPY [[COPY1]]
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:ac = ANDImag8 [[COPY2]], [[COPY]]
    ; CHECK-NEXT: RTS implicit [[COPY2]]
    %0:ac = COPY $x
    %1:imag8 = COPY $y
    %2:ac = ANDImag8 %0, killed %1
    RTS implicit %2
...
---
name: EORImag8
body: |
  bb.0.entry:
    liveins: $c
    ; CHECK-LABEL: name: EORImag8
    ; CHECK: liveins: $c
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:imag8 = COPY $x
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:ac = COPY $y
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:ac = COPY [[COPY1]]
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:ac = EORImag8 [[COPY2]], [[COPY]]
    ; CHECK-NEXT: RTS implicit [[COPY2]]
    %0:ac = COPY $x
    %1:imag8 = COPY $y
    %2:ac = EORImag8 %0, killed %1
    RTS implicit %2
...
---
name: ORAImag8
body: |
  bb.0.entry:
    liveins: $c
    ; CHECK-LABEL: name: ORAImag8
    ; CHECK: liveins: $c
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:imag8 = COPY $x
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:ac = COPY $y
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:ac = COPY [[COPY1]]
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:ac = ORAImag8 [[COPY2]], [[COPY]]
    ; CHECK-NEXT: RTS implicit [[COPY2]]
    %0:ac = COPY $x
    %1:imag8 = COPY $y
    %2:ac = ORAImag8 %0, killed %1
    RTS implicit %2
...
