# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -mtriple=mos -mcpu=mosspc700 -run-pass=postrapseudos -verify-machineinstrs -o - %s | FileCheck %s
---
name: imag8_to_imag8
tracksRegLiveness: true
body: |
  bb.0.entry:
    liveins: $rc0
    ; CHECK-LABEL: name: imag8_to_imag8
    ; CHECK: liveins: $rc0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: $rc1 = MOVImag8 $rc0
    $rc1 = COPY $rc0
...
---
name: imag8_to_imag8_gpr_store
tracksRegLiveness: true
body: |
  bb.0.entry:
    liveins: $x, $rc0
    ; CHECK-LABEL: name: imag8_to_imag8_gpr_store
    ; CHECK: liveins: $x, $rc0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: $rc0 = STImag8 $x
    ; CHECK-NEXT: $rc1 = MOVImag8 $rc0
    $rc0 = COPY $x
    $rc1 = COPY $rc0
...
...
---
name: imag8_to_imag8_gpr_store_clobber_src
tracksRegLiveness: true
body: |
  bb.0.entry:
    liveins: $x, $y, $rc0
    ; CHECK-LABEL: name: imag8_to_imag8_gpr_store_clobber_src
    ; CHECK: liveins: $x, $y, $rc0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: $rc0 = STImag8 $x
    ; CHECK-NEXT: PH_CMOS $y
    ; CHECK-NEXT: $x = PL_CMOS
    ; CHECK-NEXT: $rc1 = MOVImag8 $rc0
    $rc0 = COPY $x
    $x = COPY $y
    $rc1 = COPY $rc0
...
---
name: imag8_to_imag8_gpr_store_clobber_dst
tracksRegLiveness: true
body: |
  bb.0.entry:
    liveins: $x, $y, $rc0, $rc2
    ; CHECK-LABEL: name: imag8_to_imag8_gpr_store_clobber_dst
    ; CHECK: liveins: $x, $y, $rc0, $rc2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: $rc0 = STImag8 $x
    ; CHECK-NEXT: $rc0 = MOVImag8 $rc2
    ; CHECK-NEXT: $rc1 = MOVImag8 $rc0
    $rc0 = COPY $x
    $rc0 = COPY $rc2
    $rc1 = COPY $rc0
...
---
name: imag8_to_imag8_gpr_use
tracksRegLiveness: true
body: |
  bb.0.entry:
    liveins: $x, $rc0
    ; CHECK-LABEL: name: imag8_to_imag8_gpr_use
    ; CHECK: liveins: $x, $rc0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: $x = LDImag8 $rc0
    ; CHECK-NEXT: $rc1 = MOVImag8 $rc0
    $x = COPY $rc0
    $rc1 = COPY $rc0
...
---
name: imag8_to_imag8_gpr_use_clobber_src
tracksRegLiveness: true
body: |
  bb.0.entry:
    liveins: $x, $rc0, $rc2
    ; CHECK-LABEL: name: imag8_to_imag8_gpr_use_clobber_src
    ; CHECK: liveins: $x, $rc0, $rc2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: $x = LDImag8 $rc0
    ; CHECK-NEXT: $rc0 = MOVImag8 $rc2
    ; CHECK-NEXT: $rc1 = MOVImag8 $rc0
    $x = COPY $rc0
    $rc0 = COPY $rc2
    $rc1 = COPY $rc0
...
---
name: imag8_to_imag8_gpr_use_clobber_dst
tracksRegLiveness: true
body: |
  bb.0.entry:
    liveins: $x, $y, $rc0
    ; CHECK-LABEL: name: imag8_to_imag8_gpr_use_clobber_dst
    ; CHECK: liveins: $x, $y, $rc0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: $x = LDImag8 $rc0
    ; CHECK-NEXT: PH_CMOS $y
    ; CHECK-NEXT: $x = PL_CMOS
    ; CHECK-NEXT: $rc1 = MOVImag8 $rc0
    $x = COPY $rc0
    $x = COPY $y
    $rc1 = COPY $rc0
...
---
name: imag16_to_imag16
tracksRegLiveness: true
body: |
  bb.0.entry:
    liveins: $rs0
    ; CHECK-LABEL: name: imag16_to_imag16
    ; CHECK: liveins: $rs0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: $rc2 = MOVImag8 $rc0
    ; CHECK-NEXT: $rc3 = MOVImag8 $rc1
    $rs1 = COPY $rs0
...
