# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 2
# RUN: llc -mtriple=mos -mcpu=mos65c02 -run-pass=postrapseudos -verify-machineinstrs -o - %s | FileCheck %s
---
name: xlsb_to_v
tracksRegLiveness: true
body: |
  bb.0.entry:
    liveins: $xlsb
    ; CHECK-LABEL: name: xlsb_to_v
    ; CHECK: liveins: $xlsb
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: PH_CMOS $x
    ; CHECK-NEXT: $x = PL_CMOS implicit-def $nz
    ; CHECK-NEXT: $v = SelectImm $z, 0, -1
    $v = COPY $xlsb
...
---
name: ylsb_to_v
tracksRegLiveness: true
body: |
  bb.0.entry:
    liveins: $ylsb
    ; CHECK-LABEL: name: ylsb_to_v
    ; CHECK: liveins: $ylsb
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: PH_CMOS $y
    ; CHECK-NEXT: $y = PL_CMOS implicit-def $nz
    ; CHECK-NEXT: $v = SelectImm $z, 0, -1
    $v = COPY $ylsb
...
---
name: xy_to_xy
tracksRegLiveness: true
body: |
  bb.0.entry:
    liveins: $x
    ; CHECK-LABEL: name: xy_to_xy
    ; CHECK: liveins: $x
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: PH_CMOS $x
    ; CHECK-NEXT: $y = PL_CMOS implicit-def $nz
    $y = COPY $x
...
