# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -mtriple=mos -run-pass=postrapseudos -verify-machineinstrs -o - %s | FileCheck %s
---
name: a_to_xy
tracksRegLiveness: true
body: |
  bb.0.entry:
    liveins: $a
    ; CHECK-LABEL: name: a_to_xy
    ; CHECK: liveins: $a
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: $x = TA $a
    $x = COPY $a
...
---
name: xy_to_a
tracksRegLiveness: true
body: |
  bb.0.entry:
    liveins: $x
    ; CHECK-LABEL: name: xy_to_a
    ; CHECK: liveins: $x
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: $a = T_A $x
    $a = COPY $x
...
---
name: xy_to_xy
tracksRegLiveness: true
body: |
  bb.0.entry:
    liveins: $x
    ; CHECK-LABEL: name: xy_to_xy
    ; CHECK: liveins: $x
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[T_A:%[0-9]+]]:ac = T_A $x
    ; CHECK-NEXT: $y = TA [[T_A]]
    $y = COPY $x
...
---
name: gpr_to_imag8
tracksRegLiveness: true
body: |
  bb.0.entry:
    liveins: $a
    ; CHECK-LABEL: name: gpr_to_imag8
    ; CHECK: liveins: $a
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: $rc0 = STImag8 $a
    $rc0 = COPY $a
...
---
name: imag8_to_gpr
tracksRegLiveness: true
body: |
  bb.0.entry:
    liveins: $rc0
    ; CHECK-LABEL: name: imag8_to_gpr
    ; CHECK: liveins: $rc0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: $a = LDImag8 $rc0
    $a = COPY $rc0
...
---
name: imag8_to_imag8
tracksRegLiveness: true
body: |
  bb.0.entry:
    liveins: $rc0
    ; CHECK-LABEL: name: imag8_to_imag8
    ; CHECK: liveins: $rc0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[LDImag8_:%[0-9]+]]:gpr = LDImag8 $rc0
    ; CHECK-NEXT: $rc1 = STImag8 [[LDImag8_]]
    $rc1 = COPY $rc0
...
---
name: imag8_to_imag8_gpr_store
tracksRegLiveness: true
body: |
  bb.0.entry:
    liveins: $x, $rc0
    ; CHECK-LABEL: name: imag8_to_imag8_gpr_store
    ; CHECK: liveins: $x, $rc0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: $rc0 = STImag8 $x
    ; CHECK-NEXT: $rc1 = STImag8 $x
    $rc0 = COPY $x
    $rc1 = COPY $rc0
...
...
---
name: imag8_to_imag8_gpr_store_clobber_src
tracksRegLiveness: true
body: |
  bb.0.entry:
    liveins: $x, $y, $rc0
    ; CHECK-LABEL: name: imag8_to_imag8_gpr_store_clobber_src
    ; CHECK: liveins: $x, $y, $rc0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: $rc0 = STImag8 $x
    ; CHECK-NEXT: [[T_A:%[0-9]+]]:ac = T_A $y
    ; CHECK-NEXT: $x = TA [[T_A]]
    ; CHECK-NEXT: [[LDImag8_:%[0-9]+]]:gpr = LDImag8 $rc0
    ; CHECK-NEXT: $rc1 = STImag8 [[LDImag8_]]
    $rc0 = COPY $x
    $x = COPY $y
    $rc1 = COPY $rc0
...
---
name: imag8_to_imag8_gpr_store_clobber_dst
tracksRegLiveness: true
body: |
  bb.0.entry:
    liveins: $x, $y, $rc0, $rc2
    ; CHECK-LABEL: name: imag8_to_imag8_gpr_store_clobber_dst
    ; CHECK: liveins: $x, $y, $rc0, $rc2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: $rc0 = STImag8 $x
    ; CHECK-NEXT: [[LDImag8_:%[0-9]+]]:gpr = LDImag8 $rc2
    ; CHECK-NEXT: $rc0 = STImag8 [[LDImag8_]]
    ; CHECK-NEXT: [[LDImag8_1:%[0-9]+]]:gpr = LDImag8 $rc0
    ; CHECK-NEXT: $rc1 = STImag8 [[LDImag8_1]]
    $rc0 = COPY $x
    $rc0 = COPY $rc2
    $rc1 = COPY $rc0
...
---
name: imag8_to_imag8_gpr_use
tracksRegLiveness: true
body: |
  bb.0.entry:
    liveins: $x, $rc0
    ; CHECK-LABEL: name: imag8_to_imag8_gpr_use
    ; CHECK: liveins: $x, $rc0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: $x = LDImag8 $rc0
    ; CHECK-NEXT: [[LDImag8_:%[0-9]+]]:gpr = LDImag8 $rc0
    ; CHECK-NEXT: $rc1 = STImag8 [[LDImag8_]]
    $x = COPY $rc0
    $rc1 = COPY $rc0
...
---
name: imag8_to_imag8_gpr_use_clobber_src
tracksRegLiveness: true
body: |
  bb.0.entry:
    liveins: $x, $rc0, $rc2
    ; CHECK-LABEL: name: imag8_to_imag8_gpr_use_clobber_src
    ; CHECK: liveins: $x, $rc0, $rc2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: $x = LDImag8 $rc0
    ; CHECK-NEXT: [[LDImag8_:%[0-9]+]]:gpr = LDImag8 $rc2
    ; CHECK-NEXT: $rc0 = STImag8 [[LDImag8_]]
    ; CHECK-NEXT: [[LDImag8_1:%[0-9]+]]:gpr = LDImag8 $rc0
    ; CHECK-NEXT: $rc1 = STImag8 [[LDImag8_1]]
    $x = COPY $rc0
    $rc0 = COPY $rc2
    $rc1 = COPY $rc0
...
---
name: imag8_to_imag8_gpr_use_clobber_dst
tracksRegLiveness: true
body: |
  bb.0.entry:
    liveins: $x, $y, $rc0
    ; CHECK-LABEL: name: imag8_to_imag8_gpr_use_clobber_dst
    ; CHECK: liveins: $x, $y, $rc0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: $x = LDImag8 $rc0
    ; CHECK-NEXT: [[T_A:%[0-9]+]]:ac = T_A $y
    ; CHECK-NEXT: $x = TA [[T_A]]
    ; CHECK-NEXT: [[LDImag8_:%[0-9]+]]:gpr = LDImag8 $rc0
    ; CHECK-NEXT: $rc1 = STImag8 [[LDImag8_]]
    $x = COPY $rc0
    $x = COPY $y
    $rc1 = COPY $rc0
...
---
name: imag16_to_imag16
tracksRegLiveness: true
body: |
  bb.0.entry:
    liveins: $rs0
    ; CHECK-LABEL: name: imag16_to_imag16
    ; CHECK: liveins: $rs0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[LDImag8_:%[0-9]+]]:gpr = LDImag8 $rc0
    ; CHECK-NEXT: $rc2 = STImag8 [[LDImag8_]]
    ; CHECK-NEXT: [[LDImag8_1:%[0-9]+]]:gpr = LDImag8 $rc1
    ; CHECK-NEXT: $rc3 = STImag8 [[LDImag8_1]]
    $rs1 = COPY $rs0
...
---
name: lsb_to_lsb
tracksRegLiveness: true
body: |
  bb.0.entry:
    liveins: $alsb
    ; CHECK-LABEL: name: lsb_to_lsb
    ; CHECK: liveins: $alsb
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: $x = TA $a
    $xlsb = COPY $alsb
...
---
name: gpr_lsb_to_c
tracksRegLiveness: true
body: |
  bb.0.entry:
    liveins: $xlsb
    ; CHECK-LABEL: name: gpr_lsb_to_c
    ; CHECK: liveins: $xlsb
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: $c = CMPImm $x, 1
    $c = COPY $xlsb
...
---
name: imag8lsb_to_c
tracksRegLiveness: true
body: |
  bb.0.entry:
    liveins: $rc2lsb
    ; CHECK-LABEL: name: imag8lsb_to_c
    ; CHECK: liveins: $rc2lsb
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[LDImag8_:%[0-9]+]]:gpr = LDImag8 $rc2
    ; CHECK-NEXT: $c = CMPImm [[LDImag8_]], 1
    $c = COPY $rc2lsb
...
---
name: alsb_to_v
tracksRegLiveness: true
body: |
  bb.0.entry:
    liveins: $alsb
    ; CHECK-LABEL: name: alsb_to_v
    ; CHECK: liveins: $alsb
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: $a = ORAImm $a, 0, implicit-def $nz
    ; CHECK-NEXT: $v = SelectImm $z, 0, -1
    $v = COPY $alsb
...
---
name: non_alsb_to_v
tracksRegLiveness: true
body: |
  bb.0.entry:
    liveins: $xlsb
    ; CHECK-LABEL: name: non_alsb_to_v
    ; CHECK: liveins: $xlsb
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: $x = DE $x
    ; CHECK-NEXT: $x = IN $x, implicit-def $nz
    ; CHECK-NEXT: $v = SelectImm $z, 0, -1
    $v = COPY $xlsb
...
---
name: flag_to_flag
tracksRegLiveness: true
body: |
  bb.0.entry:
    liveins: $v
    ; CHECK-LABEL: name: flag_to_flag
    ; CHECK: liveins: $v
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: $c = SelectImm $v, -1, 0
    $c = COPY $v
...
---
name: flag_to_gpr_lsb
tracksRegLiveness: true
body: |
  bb.0.entry:
    liveins: $v
    ; CHECK-LABEL: name: flag_to_gpr_lsb
    ; CHECK: liveins: $v
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: $x = SelectImm $v, 1, 0
    $xlsb = COPY $v
...
---
name: flag_to_nongpr_lsb
tracksRegLiveness: true
body: |
  bb.0.entry:
    liveins: $v
    ; CHECK-LABEL: name: flag_to_nongpr_lsb
    ; CHECK: liveins: $v
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[SelectImm:%[0-9]+]]:gpr = SelectImm $v, 1, 0
    ; CHECK-NEXT: $rc2 = STImag8 [[SelectImm]]
    $rc2lsb = COPY $v
...
---
name: redundant_copy_dst
tracksRegLiveness: true
body: |
  bb.0.entry:
    liveins: $a
    ; CHECK-LABEL: name: redundant_copy_dst
    ; CHECK: liveins: $a
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: $x = TA $a
    $x = COPY $a
    $x = COPY $a
...
---
name: redundant_copy_dst_clobber_dst
tracksRegLiveness: true
body: |
  bb.0.entry:
    liveins: $a, $y
    ; CHECK-LABEL: name: redundant_copy_dst_clobber_dst
    ; CHECK: liveins: $a, $y
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: $x = TA $a
    ; CHECK-NEXT: [[T_A:%[0-9]+]]:ac = T_A $y
    ; CHECK-NEXT: $x = TA [[T_A]]
    ; CHECK-NEXT: $x = TA $a
    $x = COPY $a
    $x = COPY $y
    $x = COPY $a
...
---
name: redundant_copy_dst_clobber_src
tracksRegLiveness: true
body: |
  bb.0.entry:
    liveins: $a, $y
    ; CHECK-LABEL: name: redundant_copy_dst_clobber_src
    ; CHECK: liveins: $a, $y
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: $x = TA $a
    ; CHECK-NEXT: $a = T_A $y
    ; CHECK-NEXT: $x = TA $a
    $x = COPY $a
    $a = COPY $y
    $x = COPY $a
...
---
name: redundant_copy_src
tracksRegLiveness: true
body: |
  bb.0.entry:
    liveins: $x
    ; CHECK-LABEL: name: redundant_copy_src
    ; CHECK: liveins: $x
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: $a = T_A $x
    $a = COPY $x
    $x = COPY $a
...
---
name: redundant_copy_src_clobber_dst
tracksRegLiveness: true
body: |
  bb.0.entry:
    liveins: $x, $y
    ; CHECK-LABEL: name: redundant_copy_src_clobber_dst
    ; CHECK: liveins: $x, $y
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: $a = T_A $x
    ; CHECK-NEXT: $a = T_A $y
    ; CHECK-NEXT: $x = TA $a
    $a = COPY $x
    $a = COPY $y
    $x = COPY $a
...
---
name: redundant_copy_src_clobber_src
tracksRegLiveness: true
body: |
  bb.0.entry:
    liveins: $x, $y
    ; CHECK-LABEL: name: redundant_copy_src_clobber_src
    ; CHECK: liveins: $x, $y
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: $a = T_A $x
    ; CHECK-NEXT: [[T_A:%[0-9]+]]:ac = T_A $y
    ; CHECK-NEXT: $x = TA [[T_A]]
    ; CHECK-NEXT: $x = TA $a
    $a = COPY $x
    $x = COPY $y
    $x = COPY $a
...
