; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -O2 -verify-machineinstrs < %s | FileCheck %s
; FIXME: Reenable this test after new register allocator
; UNSUPPORTED: target={{.*}}

; ModuleID = 'tmp.c'
source_filename = "tmp.c"
target datalayout = "e-m:e-p:16:8-p1:8:8-i16:8-i32:8-i64:8-f32:8-f64:8-a:8-Fi8-n8"
target triple = "mos"

; Function Attrs: noinline nounwind
define dso_local i16 @getchar() #0 {
; CHECK-LABEL: getchar:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    ldx #0
; CHECK-NEXT:    stx 840
; CHECK-NEXT:    stx 841
; CHECK-NEXT:    ;APP
; CHECK-NEXT:    ldx #0
; CHECK-NEXT:    jsr 58454
; CHECK-EMPTY:
; CHECK-NEXT:    ;NO_APP
; CHECK-NEXT:    tax
; CHECK-NEXT:    sta .Lgetchar_sstk
; CHECK-NEXT:    lda #10
; CHECK-NEXT:    cpx #155
; CHECK-NEXT:    beq .LBB0_2
; CHECK-NEXT:  ; %bb.1: ; %cond.false
; CHECK-NEXT:    lda .Lgetchar_sstk
; CHECK-NEXT:  .LBB0_2: ; %cond.end
; CHECK-NEXT:    ldx #0
; CHECK-NEXT:    rts
entry:
  %c = alloca i8, align 1
  store i16 0, ptr inttoptr (i16 840 to ptr), align 1
  %0 = call i8 asm sideeffect "ldx #0\0Ajsr $$e456\0A", "=a,~{p},~{a},~{x},~{y}"() #1, !srcloc !3
  store i8 %0, ptr %c, align 1
  %1 = load i8, ptr %c, align 1
  %conv = zext i8 %1 to i16
  %cmp = icmp eq i16 %conv, 155
  br i1 %cmp, label %cond.true, label %cond.false

cond.true:                                        ; preds = %entry
  br label %cond.end

cond.false:                                       ; preds = %entry
  %2 = load i8, ptr %c, align 1
  %conv2 = zext i8 %2 to i16
  br label %cond.end

cond.end:                                         ; preds = %cond.false, %cond.true
  %cond = phi i16 [ 10, %cond.true ], [ %conv2, %cond.false ]
  ret i16 %cond
}

attributes #0 = { noinline nounwind optsize "frame-pointer"="all" "min-legal-vector-width"="0" "no-trapping-math"="true" "stack-protector-buffer-size"="8" }
attributes #1 = { nocallback nounwind }

!llvm.module.flags = !{!0, !1}
!llvm.ident = !{!2}

!0 = !{i32 1, !"wchar_size", i32 4}
!1 = !{i32 7, !"frame-pointer", i32 2}
!2 = !{!"clang version 16.0.0 (git@github.com:llvm-mos/llvm-mos.git 348ab14406080eb1d461e414ad15177bf3d4271d)"}
!3 = !{i64 106, i64 122}
