; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s | FileCheck %s -check-prefix=NMOS
; RUN: llc -mcpu=mos65c02 < %s | FileCheck %s -check-prefix=CMOS
; FIXME(llvm-mos): This is broken now.

target datalayout = "e-p:16:8:8-i16:8:8-i32:8:8-i64:8:8-f32:8:8-f64:8:8-a:8:8-Fi8-n8"
target triple = "mos"

@.str = private unnamed_addr constant [15 x i8] c"HELLO, WORLD!\0A\00", align 1

; Function Attrs: nounwind optsize
define i16 @main() local_unnamed_addr #0 {
; NMOS-LABEL: main:
; NMOS:       ; %bb.0: ; %entry
; NMOS-NEXT:    clc
; NMOS-NEXT:    lda mos8(__rc0)
; NMOS-NEXT:    adc #254
; NMOS-NEXT:    pha
; NMOS-NEXT:    lda mos8(__rc1)
; NMOS-NEXT:    adc #255
; NMOS-NEXT:    sta mos8(__rc1)
; NMOS-NEXT:    pla
; NMOS-NEXT:    sta mos8(__rc0)
; NMOS-NEXT:    ; kill: killed $p
; NMOS-NEXT:    lda mos8(__rc6)
; NMOS-NEXT:    pha
; NMOS-NEXT:    lda #14
; NMOS-NEXT:    ldy #1
; NMOS-NEXT:    sta (mos8(__rc0)),y ; 1-byte Folded Spill
; NMOS-NEXT:    lda #72
; NMOS-NEXT:    ldy #0
; NMOS-NEXT:    sta (mos8(__rc0)),y ; 1-byte Folded Spill
; NMOS-NEXT:    ldy #mos16lo(.str+1)
; NMOS-NEXT:    ldx #mos16hi(.str+1)
; NMOS-NEXT:  .LBB0_1: ; %while.body
; NMOS-NEXT:    ; =>This Inner Loop Header: Depth=1
; NMOS-NEXT:    sty mos8(__rc6)
; NMOS-NEXT:    sty mos8(__rc2)
; NMOS-NEXT:    stx mos8(__rc3)
; NMOS-NEXT:    ldy #0
; NMOS-NEXT:    lda (mos8(__rc0)),y ; 1-byte Folded Reload
; NMOS-NEXT:    ;APP
; NMOS-NEXT:    jsr 65490
; NMOS-NEXT:    ;NO_APP
; NMOS-NEXT:    ldy #0
; NMOS-NEXT:    lda (mos8(__rc2)),y
; NMOS-NEXT:    ldy #0
; NMOS-NEXT:    sta (mos8(__rc0)),y ; 1-byte Folded Spill
; NMOS-NEXT:    clc
; NMOS-NEXT:    ldy #1
; NMOS-NEXT:    lda (mos8(__rc0)),y ; 1-byte Folded Reload
; NMOS-NEXT:    adc #-1
; NMOS-NEXT:    sta mos8(__rc2)
; NMOS-NEXT:    clc
; NMOS-NEXT:    lda mos8(__rc6)
; NMOS-NEXT:    adc #1
; NMOS-NEXT:    tay
; NMOS-NEXT:    txa
; NMOS-NEXT:    adc #0
; NMOS-NEXT:    tax
; NMOS-NEXT:    lda mos8(__rc2)
; NMOS-NEXT:    pha
; NMOS-NEXT:    sty __save_y
; NMOS-NEXT:    ldy #1
; NMOS-NEXT:    sta (mos8(__rc0)),y ; 1-byte Folded Spill
; NMOS-NEXT:    ldy __save_y
; NMOS-NEXT:    pla
; NMOS-NEXT:    cmp #0
; NMOS-NEXT:    bne .LBB0_1
; NMOS-NEXT:  ; %bb.2: ; %while.end
; NMOS-NEXT:    ldx #0
; NMOS-NEXT:    lda #0
; NMOS-NEXT:    sta __save_a
; NMOS-NEXT:    pla
; NMOS-NEXT:    sta mos8(__rc6)
; NMOS-NEXT:    clc
; NMOS-NEXT:    lda mos8(__rc0)
; NMOS-NEXT:    adc #2
; NMOS-NEXT:    sta mos8(__rc0)
; NMOS-NEXT:    lda mos8(__rc1)
; NMOS-NEXT:    adc #0
; NMOS-NEXT:    sta mos8(__rc1)
; NMOS-NEXT:    lda __save_a
; NMOS-NEXT:    rts
;
; CMOS-LABEL: main:
; CMOS:       ; %bb.0: ; %entry
; CMOS-NEXT:    clc
; CMOS-NEXT:    lda mos8(__rc0)
; CMOS-NEXT:    adc #254
; CMOS-NEXT:    pha
; CMOS-NEXT:    lda mos8(__rc1)
; CMOS-NEXT:    adc #255
; CMOS-NEXT:    sta mos8(__rc1)
; CMOS-NEXT:    pla
; CMOS-NEXT:    sta mos8(__rc0)
; CMOS-NEXT:    ; kill: killed $p
; CMOS-NEXT:    lda mos8(__rc6)
; CMOS-NEXT:    pha
; CMOS-NEXT:    lda #14
; CMOS-NEXT:    ldy #1
; CMOS-NEXT:    sta (mos8(__rc0)),y ; 1-byte Folded Spill
; CMOS-NEXT:    lda #72
; CMOS-NEXT:    ldy #0
; CMOS-NEXT:    sta (mos8(__rc0)),y ; 1-byte Folded Spill
; CMOS-NEXT:    ldy #mos16lo(.str+1)
; CMOS-NEXT:    ldx #mos16hi(.str+1)
; CMOS-NEXT:  .LBB0_1: ; %while.body
; CMOS-NEXT:    ; =>This Inner Loop Header: Depth=1
; CMOS-NEXT:    sty mos8(__rc6)
; CMOS-NEXT:    sty mos8(__rc2)
; CMOS-NEXT:    stx mos8(__rc3)
; CMOS-NEXT:    ldy #0
; CMOS-NEXT:    lda (mos8(__rc0)),y ; 1-byte Folded Reload
; CMOS-NEXT:    ;APP
; CMOS-NEXT:    jsr 65490
; CMOS-NEXT:    ;NO_APP
; CMOS-NEXT:    ldy #0
; CMOS-NEXT:    lda (mos8(__rc2)),y
; CMOS-NEXT:    ldy #0
; CMOS-NEXT:    sta (mos8(__rc0)),y ; 1-byte Folded Spill
; CMOS-NEXT:    clc
; CMOS-NEXT:    ldy #1
; CMOS-NEXT:    lda (mos8(__rc0)),y ; 1-byte Folded Reload
; CMOS-NEXT:    adc #-1
; CMOS-NEXT:    sta mos8(__rc2)
; CMOS-NEXT:    clc
; CMOS-NEXT:    lda mos8(__rc6)
; CMOS-NEXT:    adc #1
; CMOS-NEXT:    tay
; CMOS-NEXT:    txa
; CMOS-NEXT:    adc #0
; CMOS-NEXT:    tax
; CMOS-NEXT:    lda mos8(__rc2)
; CMOS-NEXT:    pha
; CMOS-NEXT:    phy
; CMOS-NEXT:    ldy #1
; CMOS-NEXT:    sta (mos8(__rc0)),y ; 1-byte Folded Spill
; CMOS-NEXT:    ply
; CMOS-NEXT:    pla
; CMOS-NEXT:    cmp #0
; CMOS-NEXT:    bne .LBB0_1
; CMOS-NEXT:  ; %bb.2: ; %while.end
; CMOS-NEXT:    ldx #0
; CMOS-NEXT:    lda #0
; CMOS-NEXT:    sta __save_a
; CMOS-NEXT:    pla
; CMOS-NEXT:    sta mos8(__rc6)
; CMOS-NEXT:    clc
; CMOS-NEXT:    lda mos8(__rc0)
; CMOS-NEXT:    adc #2
; CMOS-NEXT:    sta mos8(__rc0)
; CMOS-NEXT:    lda mos8(__rc1)
; CMOS-NEXT:    adc #0
; CMOS-NEXT:    sta mos8(__rc1)
; CMOS-NEXT:    lda __save_a
; CMOS-NEXT:    rts
entry:
  br label %while.body

while.body:                                       ; preds = %entry, %while.body
  %mos-indexiv.iv = phi i8 [ 0, %entry ], [ %mos-indexiv.iv.next, %while.body ]
  %0 = phi i8 [ 72, %entry ], [ %3, %while.body ]
  %1 = zext i8 %mos-indexiv.iv to i16
  %uglygep = getelementptr i8, i8* getelementptr inbounds ([15 x i8], [15 x i8]* @.str, i16 0, i16 1), i16 %1
  %2 = tail call i8 asm sideeffect "JSR\09$$FFD2", "=a,0"(i8 %0) #1, !srcloc !1
  %3 = load i8, i8* %uglygep, align 1, !tbaa !2
  %mos-indexiv.iv.next = add nuw nsw i8 %mos-indexiv.iv, 1
  %exitcond = icmp eq i8 %mos-indexiv.iv.next, 14
  br i1 %exitcond, label %while.end, label %while.body, !llvm.loop !5

while.end:                                        ; preds = %while.body
  ret i16 0
}

attributes #0 = { nounwind optsize "disable-tail-calls"="false" "frame-pointer"="all" "less-precise-fpmad"="false" "min-legal-vector-width"="0" "no-infs-fp-math"="false" "no-jump-tables"="false" "no-nans-fp-math"="false" "no-signed-zeros-fp-math"="false" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "unsafe-fp-math"="false" "use-soft-float"="false" }
attributes #1 = { nounwind }

!llvm.module.flags = !{!0}

!0 = !{i32 1, !"wchar_size", i32 4}
!1 = !{i32 108}
!2 = !{!3, !3, i64 0}
!3 = !{!"omnipotent char", !4, i64 0}
!4 = !{!"Simple C/C++ TBAA"}
!5 = distinct !{!5, !6}
!6 = !{!"llvm.loop.mustprogress"}
