# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -mtriple=mos -mcpu=moshuc6280 -run-pass=mos-hucblockcopy -verify-machineinstrs -o - %s | FileCheck %s

--- |
  define i16 @load_store_pair_to_tii() #0 {
    ret i16 1
  }

  define i16 @memcpy_to_tii() #0 {
    ret i16 1
  }

  define i16 @store_to_tii() #0 {
    ret i16 1
  }

  define i16 @memset_to_tii() #0 {
    ret i16 1
  }

  attributes #0 = { optsize }
...
---
name: load_store_pair_to_tii
body: |
  bb.1 (%ir-block.0):
    ; CHECK-LABEL: name: load_store_pair_to_tii
    ; CHECK: [[C:%[0-9]+]]:_(s16) = G_CONSTANT i16 8704
    ; CHECK-NEXT: [[INTTOPTR:%[0-9]+]]:_(p0) = G_INTTOPTR [[C]](s16)
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s16) = G_CONSTANT i16 8960
    ; CHECK-NEXT: [[INTTOPTR1:%[0-9]+]]:_(p0) = G_INTTOPTR [[C1]](s16)
    ; CHECK-NEXT: [[C2:%[0-9]+]]:_(s16) = G_CONSTANT i16 0
    ; CHECK-NEXT: HuCMemcpy 8704, 8960, 8, 1
    ; CHECK-NEXT: RTS implicit [[C2]](s16)
    %2:_(s16) = G_CONSTANT i16 8704
    %1:_(p0) = G_INTTOPTR %2:_(s16)
    %4:_(s16) = G_CONSTANT i16 8960
    %3:_(p0) = G_INTTOPTR %4:_(s16)
    %5:_(s16) = G_CONSTANT i16 0
    %0:_(s64) = G_LOAD %1:_(p0) :: (load (s64) from `ptr inttoptr (i16 8704 to ptr)`, align 512); example.c:11:3
    G_STORE %0:_(s64), %3:_(p0) :: (store (s64) into `ptr inttoptr (i16 8960 to ptr)`, align 256); example.c:11:3
    RTS implicit %5
...
---
name: memcpy_to_tii
body: |
  bb.1 (%ir-block.0):
    ; CHECK-LABEL: name: memcpy_to_tii
    ; CHECK: [[C:%[0-9]+]]:_(s16) = G_CONSTANT i16 8960
    ; CHECK-NEXT: [[INTTOPTR:%[0-9]+]]:_(p0) = G_INTTOPTR [[C]](s16)
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s16) = G_CONSTANT i16 8704
    ; CHECK-NEXT: [[INTTOPTR1:%[0-9]+]]:_(p0) = G_INTTOPTR [[C1]](s16)
    ; CHECK-NEXT: [[C2:%[0-9]+]]:_(s16) = G_CONSTANT i16 6
    ; CHECK-NEXT: [[C3:%[0-9]+]]:_(s16) = G_CONSTANT i16 0
    ; CHECK-NEXT: HuCMemcpy 8704, 8960, 6, 0
    ; CHECK-NEXT: RTS implicit [[C3]](s16)
    %1:_(s16) = G_CONSTANT i16 8960
    %0:_(p0) = G_INTTOPTR %1:_(s16)
    %3:_(s16) = G_CONSTANT i16 8704
    %2:_(p0) = G_INTTOPTR %3:_(s16)
    %4:_(s16) = G_CONSTANT i16 6
    %5:_(s16) = G_CONSTANT i16 0
    G_MEMCPY %0:_(p0), %2:_(p0), %4:_(s16), 1 :: (store (s8) into `ptr inttoptr (i16 8960 to ptr)`, align 256), (load (s8) from `ptr inttoptr (i16 8704 to ptr)`, align 512); example.c:11:3
    RTS implicit %5
...
---
name: store_to_tii
body: |
  bb.1 (%ir-block.0):
    ; CHECK-LABEL: name: store_to_tii
    ; CHECK: [[C:%[0-9]+]]:_(s64) = G_CONSTANT i64 0
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s16) = G_CONSTANT i16 8960
    ; CHECK-NEXT: [[INTTOPTR:%[0-9]+]]:_(p0) = G_INTTOPTR [[C1]](s16)
    ; CHECK-NEXT: [[C2:%[0-9]+]]:_(s16) = G_CONSTANT i16 0
    ; CHECK-NEXT: [[C3:%[0-9]+]]:_(s8) = G_CONSTANT i8 0
    ; CHECK-NEXT: G_STORE [[C3]](s8), [[INTTOPTR]](p0) :: (store (s8))
    ; CHECK-NEXT: HuCMemcpy 8960, 8961, 7, 0
    ; CHECK-NEXT: RTS implicit [[C2]](s16)
    %0:_(s64) = G_CONSTANT i64 0
    %2:_(s16) = G_CONSTANT i16 8960
    %1:_(p0) = G_INTTOPTR %2:_(s16)
    %3:_(s16) = G_CONSTANT i16 0
    G_STORE %0:_(s64), %1:_(p0) :: (store (s64) into `ptr inttoptr (i16 8960 to ptr)`, align 256); example.c:11:3
    RTS implicit %3
...
---
name: memset_to_tii
body: |
  bb.1 (%ir-block.0):
    ; CHECK-LABEL: name: memset_to_tii
    ; CHECK: [[C:%[0-9]+]]:_(s16) = G_CONSTANT i16 8960
    ; CHECK-NEXT: [[INTTOPTR:%[0-9]+]]:_(p0) = G_INTTOPTR [[C]](s16)
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s8) = G_CONSTANT i8 0
    ; CHECK-NEXT: [[C2:%[0-9]+]]:_(s16) = G_CONSTANT i16 6
    ; CHECK-NEXT: [[C3:%[0-9]+]]:_(s16) = G_CONSTANT i16 0
    ; CHECK-NEXT: [[C4:%[0-9]+]]:_(s8) = G_CONSTANT i8 0
    ; CHECK-NEXT: G_STORE [[C4]](s8), [[INTTOPTR]](p0) :: (store (s8))
    ; CHECK-NEXT: HuCMemcpy 8960, 8961, 5, 0
    ; CHECK-NEXT: RTS implicit [[C3]](s16)
    %1:_(s16) = G_CONSTANT i16 8960
    %0:_(p0) = G_INTTOPTR %1:_(s16)
    %2:_(s8) = G_CONSTANT i8 0
    %3:_(s16) = G_CONSTANT i16 6
    %4:_(s16) = G_CONSTANT i16 0
    G_MEMSET %0:_(p0), %2:_(s8), %3:_(s16), 1 :: (store (s8) into `ptr inttoptr (i16 8960 to ptr)`, align 256); example.c:11:3
    RTS implicit %4
...
