; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mcpu=mos65c02 -verify-machineinstrs < %s | FileCheck %s

target datalayout = "e-m:e-p:16:8-p1:8:8-i16:8-i32:8-i64:8-f32:8-f64:8-a:8-Fi8-n8"
target triple = "mos"

@g = global i16 0

define i8 @inc_i8(i8 %a) {
; CHECK-LABEL: inc_i8:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    inc
; CHECK-NEXT:    rts
entry:
  %0 = add i8 %a, 1
  ret i8 %0
}

define i16 @inc_i16(i16 %a) {
; CHECK-LABEL: inc_i16:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    inc
; CHECK-NEXT:    bne .LBB1_2
; CHECK-NEXT:  ; %bb.1: ; %entry
; CHECK-NEXT:    inx
; CHECK-NEXT:  .LBB1_2: ; %entry
; CHECK-NEXT:    rts
entry:
  %0 = add i16 %a, 1
  ret i16 %0
}

define i32 @inc_i32(i32 %a) {
; CHECK-LABEL: inc_i32:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    inc
; CHECK-NEXT:    bne .LBB2_6
; CHECK-NEXT:  ; %bb.1: ; %entry
; CHECK-NEXT:    inx
; CHECK-NEXT:    bne .LBB2_5
; CHECK-NEXT:  ; %bb.2: ; %entry
; CHECK-NEXT:    inc __rc2
; CHECK-NEXT:    bne .LBB2_4
; CHECK-NEXT:  ; %bb.3: ; %entry
; CHECK-NEXT:    inc __rc3
; CHECK-NEXT:  .LBB2_4: ; %entry
; CHECK-NEXT:  .LBB2_5: ; %entry
; CHECK-NEXT:  .LBB2_6: ; %entry
; CHECK-NEXT:    rts
entry:
  %0 = add i32 %a, 1
  ret i32 %0
}

define i8 @dec_i8(i8 %a) {
; CHECK-LABEL: dec_i8:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    dec
; CHECK-NEXT:    rts
entry:
  %0 = add i8 %a, -1
  ret i8 %0
}

define i16 @dec_i16(i16 %a) {
; CHECK-LABEL: dec_i16:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    tay
; CHECK-NEXT:    dec
; CHECK-NEXT:    cpy #0
; CHECK-NEXT:    bne .LBB4_2
; CHECK-NEXT:  ; %bb.1: ; %entry
; CHECK-NEXT:    dex
; CHECK-NEXT:  .LBB4_2: ; %entry
; CHECK-NEXT:    rts
entry:
  %0 = add i16 %a, -1
  ret i16 %0
}

define i32 @dec_i32(i32 %a) {
; CHECK-LABEL: dec_i32:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    tay
; CHECK-NEXT:    dec
; CHECK-NEXT:    cpy #0
; CHECK-NEXT:    bne .LBB5_6
; CHECK-NEXT:  ; %bb.1: ; %entry
; CHECK-NEXT:    phx
; CHECK-NEXT:    ply
; CHECK-NEXT:    dex
; CHECK-NEXT:    cpy #0
; CHECK-NEXT:    bne .LBB5_5
; CHECK-NEXT:  ; %bb.2: ; %entry
; CHECK-NEXT:    ldy __rc2
; CHECK-NEXT:    dec __rc2
; CHECK-NEXT:    cpy #0
; CHECK-NEXT:    bne .LBB5_4
; CHECK-NEXT:  ; %bb.3: ; %entry
; CHECK-NEXT:    dec __rc3
; CHECK-NEXT:  .LBB5_4: ; %entry
; CHECK-NEXT:  .LBB5_5: ; %entry
; CHECK-NEXT:  .LBB5_6: ; %entry
; CHECK-NEXT:    rts
entry:
  %0 = add i32 %a, -1
  ret i32 %0
}
