# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -mtriple=mos -run-pass=mos-insert-copies -verify-machineinstrs -o - %s | FileCheck %s
---
name: asl_prev_imag8
body: |
  bb.0.entry:
    liveins: $a
    ; CHECK-LABEL: name: asl_prev_imag8
    ; CHECK: [[COPY:%[0-9]+]]:imag8 = COPY $a
    ; CHECK-NEXT: $a, $c, $v = ADCImag8 $a, [[COPY]], $c
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:aimag8 = COPY [[COPY]]
    ; CHECK-NEXT: %1:aimag8, $c = ASL [[COPY1]]
    ; CHECK-NEXT: RTS implicit %1
    %0:imag8 = COPY $a
    $a, $c, $v = ADCImag8 $a, %0, $c
    %1:aimag8, $c = ASL %0
    RTS implicit %1
...
---
name: asl_post_imag8
body: |
  bb.0.entry:
    liveins: $a
    ; CHECK-LABEL: name: asl_post_imag8
    ; CHECK: [[COPY:%[0-9]+]]:aimag8 = COPY $a
    ; CHECK-NEXT: %2:aimag8, $c = ASL [[COPY]]
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:imag8 = COPY %2
    ; CHECK-NEXT: $a, $c, $v = ADCImag8 $a, [[COPY1]], $c
    ; CHECK-NEXT: RTS implicit [[COPY1]]
    %0:aimag8 = COPY $a
    %1:imag8, $c = ASL %0
    $a, $c, $v = ADCImag8 $a, %1, $c
    RTS implicit %1
...
---
name: asl_both_sides_imag8
body: |
  bb.0.entry:
    liveins: $a
    ; CHECK-LABEL: name: asl_both_sides_imag8
    ; CHECK: [[COPY:%[0-9]+]]:imag8 = COPY $a
    ; CHECK-NEXT: $a, $c, $v = ADCImag8 $a, [[COPY]], $c
    ; CHECK-NEXT: %1:imag8, $c = ASL [[COPY]]
    ; CHECK-NEXT: $a, $c, $v = ADCImag8 $a, %1, $c
    ; CHECK-NEXT: RTS implicit %1
    %0:imag8 = COPY $a
    $a, $c, $v = ADCImag8 $a, %0, $c
    %1:imag8, $c = ASL %0
    $a, $c, $v = ADCImag8 $a, %1, $c
    RTS implicit %1
...
---
name: lsr
body: |
  bb.0.entry:
    liveins: $a
    ; CHECK-LABEL: name: lsr
    ; CHECK: [[COPY:%[0-9]+]]:imag8 = COPY $a
    ; CHECK-NEXT: $a, $c, $v = ADCImag8 $a, [[COPY]], $c
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:aimag8 = COPY [[COPY]]
    ; CHECK-NEXT: %1:aimag8, $c = LSR [[COPY1]]
    ; CHECK-NEXT: RTS implicit %1
    %0:imag8 = COPY $a
    $a, $c, $v = ADCImag8 $a, %0, $c
    %1:aimag8, $c = LSR %0
    RTS implicit %1
...
---
name: rol
body: |
  bb.0.entry:
    liveins: $a
    ; CHECK-LABEL: name: rol
    ; CHECK: [[COPY:%[0-9]+]]:imag8 = COPY $a
    ; CHECK-NEXT: $a, $c, $v = ADCImag8 $a, [[COPY]], $c
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:aimag8 = COPY [[COPY]]
    ; CHECK-NEXT: %1:aimag8, $c = ROL [[COPY1]], $c
    ; CHECK-NEXT: RTS implicit %1
    %0:imag8 = COPY $a
    $a, $c, $v = ADCImag8 $a, %0, $c
    %1:aimag8, $c = ROL %0, $c
    RTS implicit %1
...
---
name: ror
body: |
  bb.0.entry:
    liveins: $a
    ; CHECK-LABEL: name: ror
    ; CHECK: [[COPY:%[0-9]+]]:imag8 = COPY $a
    ; CHECK-NEXT: $a, $c, $v = ADCImag8 $a, [[COPY]], $c
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:aimag8 = COPY [[COPY]]
    ; CHECK-NEXT: %1:aimag8, $c = ROR [[COPY1]], $c
    ; CHECK-NEXT: RTS implicit %1
    %0:imag8 = COPY $a
    $a, $c, $v = ADCImag8 $a, %0, $c
    %1:aimag8, $c = ROR %0, $c
    RTS implicit %1
...
---
name: asl_prev_a
body: |
  bb.0.entry:
    liveins: $a
    ; CHECK-LABEL: name: asl_prev_a
    ; CHECK: %0:ac, $c, $v = ADCImm $a, 42, $c
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:aimag8 = COPY %0
    ; CHECK-NEXT: %1:aimag8, $c = ASL [[COPY]]
    ; CHECK-NEXT: RTS implicit %1
    %0:ac, $c, $v = ADCImm $a, 42, $c
    %1:aimag8, $c = ASL %0
    RTS implicit %1
...
---
name: unrelated_imag8
body: |
  bb.0.entry:
    liveins: $a
    ; CHECK-LABEL: name: unrelated_imag8
    ; CHECK: [[COPY:%[0-9]+]]:imag8 = COPY $a
    ; CHECK-NEXT: $a, $c, $v = ADCImag8 $a, [[COPY]], $c
    ; CHECK-NEXT: RTS implicit [[COPY]]
    %0:imag8 = COPY $a
    $a, $c, $v = ADCImag8 $a, %0, $c
    RTS implicit %0
...
---
name: incmb
body: |
  bb.0.entry:
    liveins: $a
    ; CHECK-LABEL: name: incmb
    ; CHECK: [[COPY:%[0-9]+]]:imag8 = COPY $a
    ; CHECK-NEXT: $a, $c, $v = ADCImag8 $a, [[COPY]], $c
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:anyi8 = COPY [[COPY]]
    ; CHECK-NEXT: [[IncMB:%[0-9]+]]:anyi8 = IncMB [[COPY1]](tied-def 0), implicit-def $c
    ; CHECK-NEXT: RTS implicit [[IncMB]]
    %0:imag8 = COPY $a
    $a, $c, $v = ADCImag8 $a, %0, $c
    %1:anyi8 = IncMB %0(tied-def 0), implicit-def $c
    RTS implicit %1
...
---
name: decmb
body: |
  bb.0.entry:
    liveins: $a
    ; CHECK-LABEL: name: decmb
    ; CHECK: [[COPY:%[0-9]+]]:imag8 = COPY $a
    ; CHECK-NEXT: $a, $c, $v = ADCImag8 $a, [[COPY]], $c
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:anyi8 = COPY [[COPY]]
    ; CHECK-NEXT: early-clobber $a, %1:anyi8 = DecMB [[COPY1]](tied-def 1), implicit-def $c
    ; CHECK-NEXT: RTS implicit %1
    %0:imag8 = COPY $a
    $a, $c, $v = ADCImag8 $a, %0, $c
    early-clobber $a, %1:anyi8 = DecMB %0(tied-def 1), implicit-def $c
    RTS implicit %1
...
