# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -mtriple=mos -run-pass=instruction-select -verify-machineinstrs -o - %s | FileCheck %s -check-prefixes=6502
# RUN: llc -mtriple=mos -mcpu=mos65c02 -run-pass=instruction-select -verify-machineinstrs -o - %s | FileCheck %s -check-prefixes=65C02
---
name: add
legalized: true
regBankSelected: true
body: |
  bb.0.entry:
    ; 6502-LABEL: name: add
    ; 6502: [[COPY:%[0-9]+]]:ac = COPY $x
    ; 6502-NEXT: [[COPY1:%[0-9]+]]:imag8 = COPY $a
    ; 6502-NEXT: [[LDCImm:%[0-9]+]]:cc = LDCImm 0
    ; 6502-NEXT: [[ADCImag8_:%[0-9]+]]:ac, dead [[ADCImag8_1:%[0-9]+]]:cc, dead [[ADCImag8_2:%[0-9]+]]:vc = ADCImag8 [[COPY]], [[COPY1]], [[LDCImm]]
    ; 6502-NEXT: RTS implicit [[ADCImag8_]]
    ;
    ; 65C02-LABEL: name: add
    ; 65C02: [[COPY:%[0-9]+]]:ac = COPY $x
    ; 65C02-NEXT: [[COPY1:%[0-9]+]]:imag8 = COPY $a
    ; 65C02-NEXT: [[LDCImm:%[0-9]+]]:cc = LDCImm 0
    ; 65C02-NEXT: [[ADCImag8_:%[0-9]+]]:ac, dead [[ADCImag8_1:%[0-9]+]]:cc, dead [[ADCImag8_2:%[0-9]+]]:vc = ADCImag8 [[COPY]], [[COPY1]], [[LDCImm]]
    ; 65C02-NEXT: RTS implicit [[ADCImag8_]]
    %0:any(s8) = COPY $x
    %1:any(s8) = COPY $a
    %2:any(s8) = G_ADD %0, %1
    RTS implicit %2
...
---
name: add_imm
legalized: true
regBankSelected: true
body: |
  bb.0.entry:
    ; 6502-LABEL: name: add_imm
    ; 6502: [[COPY:%[0-9]+]]:ac = COPY $x
    ; 6502-NEXT: [[LDCImm:%[0-9]+]]:cc = LDCImm 0
    ; 6502-NEXT: [[ADCImm:%[0-9]+]]:ac, dead [[ADCImm1:%[0-9]+]]:cc, dead [[ADCImm2:%[0-9]+]]:vc = ADCImm [[COPY]], 42, [[LDCImm]]
    ; 6502-NEXT: RTS implicit [[ADCImm]]
    ;
    ; 65C02-LABEL: name: add_imm
    ; 65C02: [[COPY:%[0-9]+]]:ac = COPY $x
    ; 65C02-NEXT: [[LDCImm:%[0-9]+]]:cc = LDCImm 0
    ; 65C02-NEXT: [[ADCImm:%[0-9]+]]:ac, dead [[ADCImm1:%[0-9]+]]:cc, dead [[ADCImm2:%[0-9]+]]:vc = ADCImm [[COPY]], 42, [[LDCImm]]
    ; 65C02-NEXT: RTS implicit [[ADCImm]]
    %0:any(s8) = COPY $x
    %1:any(s8) = G_CONSTANT i8 42
    %2:any(s8) = G_ADD %0, %1
    RTS implicit %2
...
---
name: add_abs
legalized: true
regBankSelected: true
body: |
  bb.0.entry:
    ; 6502-LABEL: name: add_abs
    ; 6502: [[COPY:%[0-9]+]]:ac = COPY $x
    ; 6502-NEXT: [[LDCImm:%[0-9]+]]:cc = LDCImm 0
    ; 6502-NEXT: [[ADCAbs:%[0-9]+]]:ac, [[ADCAbs1:%[0-9]+]]:cc, [[ADCAbs2:%[0-9]+]]:vc = ADCAbs [[COPY]], i16 1234, [[LDCImm]] :: (load (s8))
    ; 6502-NEXT: RTS implicit [[ADCAbs]]
    ;
    ; 65C02-LABEL: name: add_abs
    ; 65C02: [[COPY:%[0-9]+]]:ac = COPY $x
    ; 65C02-NEXT: [[LDCImm:%[0-9]+]]:cc = LDCImm 0
    ; 65C02-NEXT: [[ADCAbs:%[0-9]+]]:ac, [[ADCAbs1:%[0-9]+]]:cc, [[ADCAbs2:%[0-9]+]]:vc = ADCAbs [[COPY]], i16 1234, [[LDCImm]] :: (load (s8))
    ; 65C02-NEXT: RTS implicit [[ADCAbs]]
    %0:any(s8) = COPY $x
    %1:any(s8) = G_LOAD_ABS i16 1234 :: (load (s8))
    %2:any(s8) = G_ADD %0, %1
    RTS implicit %2
...
---
name: add_abs_commute
legalized: true
regBankSelected: true
body: |
  bb.0.entry:
    ; 6502-LABEL: name: add_abs_commute
    ; 6502: [[COPY:%[0-9]+]]:ac = COPY $x
    ; 6502-NEXT: [[LDCImm:%[0-9]+]]:cc = LDCImm 0
    ; 6502-NEXT: [[ADCAbs:%[0-9]+]]:ac, [[ADCAbs1:%[0-9]+]]:cc, [[ADCAbs2:%[0-9]+]]:vc = ADCAbs [[COPY]], i16 1234, [[LDCImm]] :: (load (s8))
    ; 6502-NEXT: RTS implicit [[ADCAbs]]
    ;
    ; 65C02-LABEL: name: add_abs_commute
    ; 65C02: [[COPY:%[0-9]+]]:ac = COPY $x
    ; 65C02-NEXT: [[LDCImm:%[0-9]+]]:cc = LDCImm 0
    ; 65C02-NEXT: [[ADCAbs:%[0-9]+]]:ac, [[ADCAbs1:%[0-9]+]]:cc, [[ADCAbs2:%[0-9]+]]:vc = ADCAbs [[COPY]], i16 1234, [[LDCImm]] :: (load (s8))
    ; 65C02-NEXT: RTS implicit [[ADCAbs]]
    %0:any(s8) = COPY $x
    %1:any(s8) = G_LOAD_ABS i16 1234 :: (load (s8))
    %2:any(s8) = G_ADD %1, %0
    RTS implicit %2
...
---
name: add_abs_2_uses
legalized: true
regBankSelected: true
body: |
  bb.0.entry:
    ; 6502-LABEL: name: add_abs_2_uses
    ; 6502: [[COPY:%[0-9]+]]:ac = COPY $x
    ; 6502-NEXT: [[LDAbs:%[0-9]+]]:gpr = LDAbs i16 1234 :: (load (s8))
    ; 6502-NEXT: [[LDCImm:%[0-9]+]]:cc = LDCImm 0
    ; 6502-NEXT: [[ADCAbs:%[0-9]+]]:ac, [[ADCAbs1:%[0-9]+]]:cc, [[ADCAbs2:%[0-9]+]]:vc = ADCAbs [[COPY]], i16 1234, [[LDCImm]] :: (load (s8))
    ; 6502-NEXT: [[COPY1:%[0-9]+]]:anyi8 = COPY [[LDAbs]]
    ; 6502-NEXT: RTS implicit [[ADCAbs]], implicit [[COPY1]]
    ;
    ; 65C02-LABEL: name: add_abs_2_uses
    ; 65C02: [[COPY:%[0-9]+]]:ac = COPY $x
    ; 65C02-NEXT: [[LDAbs:%[0-9]+]]:gpr = LDAbs i16 1234 :: (load (s8))
    ; 65C02-NEXT: [[LDCImm:%[0-9]+]]:cc = LDCImm 0
    ; 65C02-NEXT: [[ADCAbs:%[0-9]+]]:ac, [[ADCAbs1:%[0-9]+]]:cc, [[ADCAbs2:%[0-9]+]]:vc = ADCAbs [[COPY]], i16 1234, [[LDCImm]] :: (load (s8))
    ; 65C02-NEXT: [[COPY1:%[0-9]+]]:anyi8 = COPY [[LDAbs]]
    ; 65C02-NEXT: RTS implicit [[ADCAbs]], implicit [[COPY1]]
    %0:any(s8) = COPY $x
    %1:any(s8) = G_LOAD_ABS i16 1234 :: (load (s8))
    %2:any(s8) = G_ADD %1, %0
    %3:any(s8) = COPY %1
    RTS implicit %2, implicit %3
...
---
name: add_abs_3_uses
legalized: true
regBankSelected: true
body: |
  bb.0.entry:
    ; 6502-LABEL: name: add_abs_3_uses
    ; 6502: [[COPY:%[0-9]+]]:imag8 = COPY $x
    ; 6502-NEXT: [[LDAbs:%[0-9]+]]:ac = LDAbs i16 1234 :: (load (s8))
    ; 6502-NEXT: [[LDCImm:%[0-9]+]]:cc = LDCImm 0
    ; 6502-NEXT: [[ADCImag8_:%[0-9]+]]:ac, dead [[ADCImag8_1:%[0-9]+]]:cc, dead [[ADCImag8_2:%[0-9]+]]:vc = ADCImag8 [[LDAbs]], [[COPY]], [[LDCImm]]
    ; 6502-NEXT: [[COPY1:%[0-9]+]]:anyi8 = COPY [[LDAbs]]
    ; 6502-NEXT: [[COPY2:%[0-9]+]]:anyi8 = COPY [[LDAbs]]
    ; 6502-NEXT: RTS implicit [[ADCImag8_]], implicit [[COPY1]], implicit [[COPY2]]
    ;
    ; 65C02-LABEL: name: add_abs_3_uses
    ; 65C02: [[COPY:%[0-9]+]]:imag8 = COPY $x
    ; 65C02-NEXT: [[LDAbs:%[0-9]+]]:ac = LDAbs i16 1234 :: (load (s8))
    ; 65C02-NEXT: [[LDCImm:%[0-9]+]]:cc = LDCImm 0
    ; 65C02-NEXT: [[ADCImag8_:%[0-9]+]]:ac, dead [[ADCImag8_1:%[0-9]+]]:cc, dead [[ADCImag8_2:%[0-9]+]]:vc = ADCImag8 [[LDAbs]], [[COPY]], [[LDCImm]]
    ; 65C02-NEXT: [[COPY1:%[0-9]+]]:anyi8 = COPY [[LDAbs]]
    ; 65C02-NEXT: [[COPY2:%[0-9]+]]:anyi8 = COPY [[LDAbs]]
    ; 65C02-NEXT: RTS implicit [[ADCImag8_]], implicit [[COPY1]], implicit [[COPY2]]
    %0:any(s8) = COPY $x
    %1:any(s8) = G_LOAD_ABS i16 1234 :: (load (s8))
    %2:any(s8) = G_ADD %1, %0
    %3:any(s8) = COPY %1
    %4:any(s8) = COPY %1
    RTS implicit %2, implicit %3, implicit %4
...
---
name: add_abs_across_store
legalized: true
regBankSelected: true
body: |
  bb.0.entry:
    ; 6502-LABEL: name: add_abs_across_store
    ; 6502: [[COPY:%[0-9]+]]:ac = COPY $x
    ; 6502-NEXT: [[LDAbs:%[0-9]+]]:gpr = LDAbs i16 1234 :: (load (s8))
    ; 6502-NEXT: [[COPY1:%[0-9]+]]:imag8 = COPY [[LDAbs]]
    ; 6502-NEXT: STAbs [[COPY]], i16 1234 :: (store (s8))
    ; 6502-NEXT: [[LDCImm:%[0-9]+]]:cc = LDCImm 0
    ; 6502-NEXT: [[ADCImag8_:%[0-9]+]]:ac, dead [[ADCImag8_1:%[0-9]+]]:cc, dead [[ADCImag8_2:%[0-9]+]]:vc = ADCImag8 [[COPY]], [[COPY1]], [[LDCImm]]
    ; 6502-NEXT: RTS implicit [[ADCImag8_]]
    ;
    ; 65C02-LABEL: name: add_abs_across_store
    ; 65C02: [[COPY:%[0-9]+]]:ac = COPY $x
    ; 65C02-NEXT: [[LDAbs:%[0-9]+]]:gpr = LDAbs i16 1234 :: (load (s8))
    ; 65C02-NEXT: [[COPY1:%[0-9]+]]:imag8 = COPY [[LDAbs]]
    ; 65C02-NEXT: STAbs [[COPY]], i16 1234 :: (store (s8))
    ; 65C02-NEXT: [[LDCImm:%[0-9]+]]:cc = LDCImm 0
    ; 65C02-NEXT: [[ADCImag8_:%[0-9]+]]:ac, dead [[ADCImag8_1:%[0-9]+]]:cc, dead [[ADCImag8_2:%[0-9]+]]:vc = ADCImag8 [[COPY]], [[COPY1]], [[LDCImm]]
    ; 65C02-NEXT: RTS implicit [[ADCImag8_]]
    %0:any(s8) = COPY $x
    %1:any(s8) = G_LOAD_ABS i16 1234 :: (load (s8))
    G_STORE_ABS %0, i16 1234 :: (store (s8))
    %3:any(s8) = G_ADD %0, %1
    RTS implicit %3
...
---
name: add_abs_one
legalized: true
regBankSelected: true
body: |
  bb.0.entry:
    ; 6502-LABEL: name: add_abs_one
    ; 6502: [[LDAbs:%[0-9]+]]:gpr = LDAbs i16 1234 :: (load (s8))
    ; 6502-NEXT: [[IncNMOS:%[0-9]+]]:anyi8 = IncNMOS [[LDAbs]], implicit-def dead $c, implicit-def dead $v
    ; 6502-NEXT: RTS implicit [[IncNMOS]]
    ;
    ; 65C02-LABEL: name: add_abs_one
    ; 65C02: [[LDAbs:%[0-9]+]]:gpr = LDAbs i16 1234 :: (load (s8))
    ; 65C02-NEXT: [[INC:%[0-9]+]]:anyi8 = INC [[LDAbs]]
    ; 65C02-NEXT: RTS implicit [[INC]]
    %0:any(s8) = G_LOAD_ABS i16 1234 :: (load (s8))
    %1:any(s8) = G_CONSTANT i8 1
    %2:any(s8) = G_ADD %0, %1
    RTS implicit %2
...
---
name: add_zp_idx
legalized: true
regBankSelected: true
body: |
  bb.0.entry:
    ; 6502-LABEL: name: add_zp_idx
    ; 6502: [[COPY:%[0-9]+]]:ac = COPY $x
    ; 6502-NEXT: [[LDCImm:%[0-9]+]]:cc = LDCImm 0
    ; 6502-NEXT: [[COPY1:%[0-9]+]]:xc = COPY [[COPY]]
    ; 6502-NEXT: [[ADCZpIdx:%[0-9]+]]:ac, [[ADCZpIdx1:%[0-9]+]]:cc, [[ADCZpIdx2:%[0-9]+]]:vc = ADCZpIdx [[COPY]], i16 123, [[COPY1]], [[LDCImm]] :: (load (s8))
    ; 6502-NEXT: RTS implicit [[ADCZpIdx]]
    ;
    ; 65C02-LABEL: name: add_zp_idx
    ; 65C02: [[COPY:%[0-9]+]]:ac = COPY $x
    ; 65C02-NEXT: [[LDCImm:%[0-9]+]]:cc = LDCImm 0
    ; 65C02-NEXT: [[COPY1:%[0-9]+]]:xc = COPY [[COPY]]
    ; 65C02-NEXT: [[ADCZpIdx:%[0-9]+]]:ac, [[ADCZpIdx1:%[0-9]+]]:cc, [[ADCZpIdx2:%[0-9]+]]:vc = ADCZpIdx [[COPY]], i16 123, [[COPY1]], [[LDCImm]] :: (load (s8))
    ; 65C02-NEXT: RTS implicit [[ADCZpIdx]]
    %0:any(s8) = COPY $x
    %1:any(s8) = G_LOAD_ZP_IDX i16 123, %0 :: (load (s8))
    %2:any(s8) = G_ADD %0, %1
    RTS implicit %2
...
---
name: add_abs_idx
legalized: true
regBankSelected: true
body: |
  bb.0.entry:
    ; 6502-LABEL: name: add_abs_idx
    ; 6502: [[COPY:%[0-9]+]]:ac = COPY $x
    ; 6502-NEXT: [[LDCImm:%[0-9]+]]:cc = LDCImm 0
    ; 6502-NEXT: [[COPY1:%[0-9]+]]:xy = COPY [[COPY]]
    ; 6502-NEXT: [[ADCAbsIdx:%[0-9]+]]:ac, [[ADCAbsIdx1:%[0-9]+]]:cc, [[ADCAbsIdx2:%[0-9]+]]:vc = ADCAbsIdx [[COPY]], i16 1234, [[COPY1]], [[LDCImm]] :: (load (s8))
    ; 6502-NEXT: RTS implicit [[ADCAbsIdx]]
    ;
    ; 65C02-LABEL: name: add_abs_idx
    ; 65C02: [[COPY:%[0-9]+]]:ac = COPY $x
    ; 65C02-NEXT: [[LDCImm:%[0-9]+]]:cc = LDCImm 0
    ; 65C02-NEXT: [[COPY1:%[0-9]+]]:xy = COPY [[COPY]]
    ; 65C02-NEXT: [[ADCAbsIdx:%[0-9]+]]:ac, [[ADCAbsIdx1:%[0-9]+]]:cc, [[ADCAbsIdx2:%[0-9]+]]:vc = ADCAbsIdx [[COPY]], i16 1234, [[COPY1]], [[LDCImm]] :: (load (s8))
    ; 65C02-NEXT: RTS implicit [[ADCAbsIdx]]
    %0:any(s8) = COPY $x
    %1:any(s8) = G_LOAD_ABS_IDX i16 1234, %0 :: (load (s8))
    %2:any(s8) = G_ADD %0, %1
    RTS implicit %2
...
---
name: add_y_indir
legalized: true
regBankSelected: true
body: |
  bb.0.entry:
    ; 6502-LABEL: name: add_y_indir
    ; 6502: [[COPY:%[0-9]+]]:imag16 = COPY $rs1
    ; 6502-NEXT: [[COPY1:%[0-9]+]]:ac = COPY $x
    ; 6502-NEXT: [[LDCImm:%[0-9]+]]:cc = LDCImm 0
    ; 6502-NEXT: [[ADCIndir:%[0-9]+]]:ac, [[ADCIndir1:%[0-9]+]]:cc, [[ADCIndir2:%[0-9]+]]:vc = ADCIndir [[COPY1]], [[COPY]], [[LDCImm]] :: (load (s8))
    ; 6502-NEXT: RTS implicit [[ADCIndir]]
    ;
    ; 65C02-LABEL: name: add_y_indir
    ; 65C02: [[COPY:%[0-9]+]]:imag16 = COPY $rs1
    ; 65C02-NEXT: [[COPY1:%[0-9]+]]:ac = COPY $x
    ; 65C02-NEXT: [[LDCImm:%[0-9]+]]:cc = LDCImm 0
    ; 65C02-NEXT: [[ADCIndir:%[0-9]+]]:ac, [[ADCIndir1:%[0-9]+]]:cc, [[ADCIndir2:%[0-9]+]]:vc = ADCIndir [[COPY1]], [[COPY]], [[LDCImm]] :: (load (s8))
    ; 65C02-NEXT: RTS implicit [[ADCIndir]]
    %0:any(s16) = COPY $rs1
    %1:any(s8) = COPY $x
    %2:any(s8) = G_LOAD_INDIR %0 :: (load (s8))
    %3:any(s8) = G_ADD %1, %2
    RTS implicit %3
...
---
name: add_y_indir_idx
legalized: true
regBankSelected: true
body: |
  bb.0.entry:
    ; 6502-LABEL: name: add_y_indir_idx
    ; 6502: [[COPY:%[0-9]+]]:imag16 = COPY $rs1
    ; 6502-NEXT: [[COPY1:%[0-9]+]]:ac = COPY $x
    ; 6502-NEXT: [[LDCImm:%[0-9]+]]:cc = LDCImm 0
    ; 6502-NEXT: [[COPY2:%[0-9]+]]:yc = COPY [[COPY1]]
    ; 6502-NEXT: [[ADCIndirIdx:%[0-9]+]]:ac, [[ADCIndirIdx1:%[0-9]+]]:cc, [[ADCIndirIdx2:%[0-9]+]]:vc = ADCIndirIdx [[COPY1]], [[COPY]], [[COPY2]], [[LDCImm]] :: (load (s8))
    ; 6502-NEXT: RTS implicit [[ADCIndirIdx]]
    ;
    ; 65C02-LABEL: name: add_y_indir_idx
    ; 65C02: [[COPY:%[0-9]+]]:imag16 = COPY $rs1
    ; 65C02-NEXT: [[COPY1:%[0-9]+]]:ac = COPY $x
    ; 65C02-NEXT: [[LDCImm:%[0-9]+]]:cc = LDCImm 0
    ; 65C02-NEXT: [[COPY2:%[0-9]+]]:yc = COPY [[COPY1]]
    ; 65C02-NEXT: [[ADCIndirIdx:%[0-9]+]]:ac, [[ADCIndirIdx1:%[0-9]+]]:cc, [[ADCIndirIdx2:%[0-9]+]]:vc = ADCIndirIdx [[COPY1]], [[COPY]], [[COPY2]], [[LDCImm]] :: (load (s8))
    ; 65C02-NEXT: RTS implicit [[ADCIndirIdx]]
    %0:any(s16) = COPY $rs1
    %1:any(s8) = COPY $x
    %2:any(s8) = G_LOAD_INDIR_IDX %0, %1 :: (load (s8))
    %3:any(s8) = G_ADD %1, %2
    RTS implicit %3
...
---
name: and_abs
legalized: true
regBankSelected: true
body: |
  bb.0.entry:
    ; 6502-LABEL: name: and_abs
    ; 6502: [[COPY:%[0-9]+]]:ac = COPY $x
    ; 6502-NEXT: [[ANDAbs:%[0-9]+]]:ac = ANDAbs [[COPY]], i16 1234 :: (load (s8))
    ; 6502-NEXT: RTS implicit [[ANDAbs]]
    ;
    ; 65C02-LABEL: name: and_abs
    ; 65C02: [[COPY:%[0-9]+]]:ac = COPY $x
    ; 65C02-NEXT: [[ANDAbs:%[0-9]+]]:ac = ANDAbs [[COPY]], i16 1234 :: (load (s8))
    ; 65C02-NEXT: RTS implicit [[ANDAbs]]
    %0:any(s8) = COPY $x
    %1:any(s8) = G_LOAD_ABS i16 1234 :: (load (s8))
    %2:any(s8) = G_AND %0, %1
    RTS implicit %2
...
---
name: and_zp_idx
legalized: true
regBankSelected: true
body: |
  bb.0.entry:
    ; 6502-LABEL: name: and_zp_idx
    ; 6502: [[COPY:%[0-9]+]]:ac = COPY $x
    ; 6502-NEXT: [[COPY1:%[0-9]+]]:xc = COPY [[COPY]]
    ; 6502-NEXT: [[ANDZpIdx:%[0-9]+]]:ac = ANDZpIdx [[COPY]], i8 123, [[COPY1]] :: (load (s8))
    ; 6502-NEXT: RTS implicit [[ANDZpIdx]]
    ;
    ; 65C02-LABEL: name: and_zp_idx
    ; 65C02: [[COPY:%[0-9]+]]:ac = COPY $x
    ; 65C02-NEXT: [[COPY1:%[0-9]+]]:xc = COPY [[COPY]]
    ; 65C02-NEXT: [[ANDZpIdx:%[0-9]+]]:ac = ANDZpIdx [[COPY]], i8 123, [[COPY1]] :: (load (s8))
    ; 65C02-NEXT: RTS implicit [[ANDZpIdx]]
    %0:any(s8) = COPY $x
    %1:any(s8) = G_LOAD_ZP_IDX i8 123, %0 :: (load (s8))
    %2:any(s8) = G_AND %0, %1
    RTS implicit %2
...
---
name: and_abs_idx
legalized: true
regBankSelected: true
body: |
  bb.0.entry:
    ; 6502-LABEL: name: and_abs_idx
    ; 6502: [[COPY:%[0-9]+]]:ac = COPY $x
    ; 6502-NEXT: [[COPY1:%[0-9]+]]:xy = COPY [[COPY]]
    ; 6502-NEXT: [[ANDAbsIdx:%[0-9]+]]:ac = ANDAbsIdx [[COPY]], i16 1234, [[COPY1]] :: (load (s8))
    ; 6502-NEXT: RTS implicit [[ANDAbsIdx]]
    ;
    ; 65C02-LABEL: name: and_abs_idx
    ; 65C02: [[COPY:%[0-9]+]]:ac = COPY $x
    ; 65C02-NEXT: [[COPY1:%[0-9]+]]:xy = COPY [[COPY]]
    ; 65C02-NEXT: [[ANDAbsIdx:%[0-9]+]]:ac = ANDAbsIdx [[COPY]], i16 1234, [[COPY1]] :: (load (s8))
    ; 65C02-NEXT: RTS implicit [[ANDAbsIdx]]
    %0:any(s8) = COPY $x
    %1:any(s8) = G_LOAD_ABS_IDX i16 1234, %0 :: (load (s8))
    %2:any(s8) = G_AND %0, %1
    RTS implicit %2
...
---
name: and_y_indir
legalized: true
regBankSelected: true
body: |
  bb.0.entry:
    ; 6502-LABEL: name: and_y_indir
    ; 6502: [[COPY:%[0-9]+]]:imag16 = COPY $rs1
    ; 6502-NEXT: [[COPY1:%[0-9]+]]:ac = COPY $x
    ; 6502-NEXT: [[ANDIndir:%[0-9]+]]:ac = ANDIndir [[COPY1]], [[COPY]] :: (load (s8))
    ; 6502-NEXT: RTS implicit [[ANDIndir]]
    ;
    ; 65C02-LABEL: name: and_y_indir
    ; 65C02: [[COPY:%[0-9]+]]:imag16 = COPY $rs1
    ; 65C02-NEXT: [[COPY1:%[0-9]+]]:ac = COPY $x
    ; 65C02-NEXT: [[ANDIndir:%[0-9]+]]:ac = ANDIndir [[COPY1]], [[COPY]] :: (load (s8))
    ; 65C02-NEXT: RTS implicit [[ANDIndir]]
    %0:any(s16) = COPY $rs1
    %1:any(s8) = COPY $x
    %2:any(s8) = G_LOAD_INDIR %0 :: (load (s8))
    %3:any(s8) = G_AND %1, %2
    RTS implicit %3
...
---
name: and_y_indir_idx
legalized: true
regBankSelected: true
body: |
  bb.0.entry:
    ; 6502-LABEL: name: and_y_indir_idx
    ; 6502: [[COPY:%[0-9]+]]:imag16 = COPY $rs1
    ; 6502-NEXT: [[COPY1:%[0-9]+]]:ac = COPY $x
    ; 6502-NEXT: [[COPY2:%[0-9]+]]:yc = COPY [[COPY1]]
    ; 6502-NEXT: [[ANDIndirIdx:%[0-9]+]]:ac = ANDIndirIdx [[COPY1]], [[COPY]], [[COPY2]] :: (load (s8))
    ; 6502-NEXT: RTS implicit [[ANDIndirIdx]]
    ;
    ; 65C02-LABEL: name: and_y_indir_idx
    ; 65C02: [[COPY:%[0-9]+]]:imag16 = COPY $rs1
    ; 65C02-NEXT: [[COPY1:%[0-9]+]]:ac = COPY $x
    ; 65C02-NEXT: [[COPY2:%[0-9]+]]:yc = COPY [[COPY1]]
    ; 65C02-NEXT: [[ANDIndirIdx:%[0-9]+]]:ac = ANDIndirIdx [[COPY1]], [[COPY]], [[COPY2]] :: (load (s8))
    ; 65C02-NEXT: RTS implicit [[ANDIndirIdx]]
    %0:any(s16) = COPY $rs1
    %1:any(s8) = COPY $x
    %2:any(s8) = G_LOAD_INDIR_IDX %0, %1 :: (load (s8))
    %3:any(s8) = G_AND %1, %2
    RTS implicit %3
...
---
name: eor_abs
legalized: true
regBankSelected: true
body: |
  bb.0.entry:
    ; 6502-LABEL: name: eor_abs
    ; 6502: [[COPY:%[0-9]+]]:ac = COPY $x
    ; 6502-NEXT: [[EORAbs:%[0-9]+]]:ac = EORAbs [[COPY]], i16 1234 :: (load (s8))
    ; 6502-NEXT: RTS implicit [[EORAbs]]
    ;
    ; 65C02-LABEL: name: eor_abs
    ; 65C02: [[COPY:%[0-9]+]]:ac = COPY $x
    ; 65C02-NEXT: [[EORAbs:%[0-9]+]]:ac = EORAbs [[COPY]], i16 1234 :: (load (s8))
    ; 65C02-NEXT: RTS implicit [[EORAbs]]
    %0:any(s8) = COPY $x
    %1:any(s8) = G_LOAD_ABS i16 1234 :: (load (s8))
    %2:any(s8) = G_XOR %0, %1
    RTS implicit %2
...
---
name: eor_zp_idx
legalized: true
regBankSelected: true
body: |
  bb.0.entry:
    ; 6502-LABEL: name: eor_zp_idx
    ; 6502: [[COPY:%[0-9]+]]:ac = COPY $x
    ; 6502-NEXT: [[COPY1:%[0-9]+]]:xc = COPY [[COPY]]
    ; 6502-NEXT: [[EORZpIdx:%[0-9]+]]:ac = EORZpIdx [[COPY]], i16 123, [[COPY1]] :: (load (s8))
    ; 6502-NEXT: RTS implicit [[EORZpIdx]]
    ;
    ; 65C02-LABEL: name: eor_zp_idx
    ; 65C02: [[COPY:%[0-9]+]]:ac = COPY $x
    ; 65C02-NEXT: [[COPY1:%[0-9]+]]:xc = COPY [[COPY]]
    ; 65C02-NEXT: [[EORZpIdx:%[0-9]+]]:ac = EORZpIdx [[COPY]], i16 123, [[COPY1]] :: (load (s8))
    ; 65C02-NEXT: RTS implicit [[EORZpIdx]]
    %0:any(s8) = COPY $x
    %1:any(s8) = G_LOAD_ZP_IDX i16 123, %0 :: (load (s8))
    %2:any(s8) = G_XOR %0, %1
    RTS implicit %2
...
---
name: eor_abs_idx
legalized: true
regBankSelected: true
body: |
  bb.0.entry:
    ; 6502-LABEL: name: eor_abs_idx
    ; 6502: [[COPY:%[0-9]+]]:ac = COPY $x
    ; 6502-NEXT: [[COPY1:%[0-9]+]]:xy = COPY [[COPY]]
    ; 6502-NEXT: [[EORAbsIdx:%[0-9]+]]:ac = EORAbsIdx [[COPY]], i16 1234, [[COPY1]] :: (load (s8))
    ; 6502-NEXT: RTS implicit [[EORAbsIdx]]
    ;
    ; 65C02-LABEL: name: eor_abs_idx
    ; 65C02: [[COPY:%[0-9]+]]:ac = COPY $x
    ; 65C02-NEXT: [[COPY1:%[0-9]+]]:xy = COPY [[COPY]]
    ; 65C02-NEXT: [[EORAbsIdx:%[0-9]+]]:ac = EORAbsIdx [[COPY]], i16 1234, [[COPY1]] :: (load (s8))
    ; 65C02-NEXT: RTS implicit [[EORAbsIdx]]
    %0:any(s8) = COPY $x
    %1:any(s8) = G_LOAD_ABS_IDX i16 1234, %0 :: (load (s8))
    %2:any(s8) = G_XOR %0, %1
    RTS implicit %2
...
---
name: eor_y_indir
legalized: true
regBankSelected: true
body: |
  bb.0.entry:
    ; 6502-LABEL: name: eor_y_indir
    ; 6502: [[COPY:%[0-9]+]]:imag16 = COPY $rs1
    ; 6502-NEXT: [[COPY1:%[0-9]+]]:ac = COPY $x
    ; 6502-NEXT: [[EORIndir:%[0-9]+]]:ac = EORIndir [[COPY1]], [[COPY]] :: (load (s8))
    ; 6502-NEXT: RTS implicit [[EORIndir]]
    ;
    ; 65C02-LABEL: name: eor_y_indir
    ; 65C02: [[COPY:%[0-9]+]]:imag16 = COPY $rs1
    ; 65C02-NEXT: [[COPY1:%[0-9]+]]:ac = COPY $x
    ; 65C02-NEXT: [[EORIndir:%[0-9]+]]:ac = EORIndir [[COPY1]], [[COPY]] :: (load (s8))
    ; 65C02-NEXT: RTS implicit [[EORIndir]]
    %0:any(s16) = COPY $rs1
    %1:any(s8) = COPY $x
    %2:any(s8) = G_LOAD_INDIR %0 :: (load (s8))
    %3:any(s8) = G_XOR %1, %2
    RTS implicit %3
...
---
name: eor_y_indir_idx
legalized: true
regBankSelected: true
body: |
  bb.0.entry:
    ; 6502-LABEL: name: eor_y_indir_idx
    ; 6502: [[COPY:%[0-9]+]]:imag16 = COPY $rs1
    ; 6502-NEXT: [[COPY1:%[0-9]+]]:ac = COPY $x
    ; 6502-NEXT: [[COPY2:%[0-9]+]]:yc = COPY [[COPY1]]
    ; 6502-NEXT: [[EORIndirIdx:%[0-9]+]]:ac = EORIndirIdx [[COPY1]], [[COPY]], [[COPY2]] :: (load (s8))
    ; 6502-NEXT: RTS implicit [[EORIndirIdx]]
    ;
    ; 65C02-LABEL: name: eor_y_indir_idx
    ; 65C02: [[COPY:%[0-9]+]]:imag16 = COPY $rs1
    ; 65C02-NEXT: [[COPY1:%[0-9]+]]:ac = COPY $x
    ; 65C02-NEXT: [[COPY2:%[0-9]+]]:yc = COPY [[COPY1]]
    ; 65C02-NEXT: [[EORIndirIdx:%[0-9]+]]:ac = EORIndirIdx [[COPY1]], [[COPY]], [[COPY2]] :: (load (s8))
    ; 65C02-NEXT: RTS implicit [[EORIndirIdx]]
    %0:any(s16) = COPY $rs1
    %1:any(s8) = COPY $x
    %2:any(s8) = G_LOAD_INDIR_IDX %0, %1 :: (load (s8))
    %3:any(s8) = G_XOR %1, %2
    RTS implicit %3
...
---
name: ora_abs
legalized: true
regBankSelected: true
body: |
  bb.0.entry:
    ; 6502-LABEL: name: ora_abs
    ; 6502: [[COPY:%[0-9]+]]:ac = COPY $x
    ; 6502-NEXT: [[ORAAbs:%[0-9]+]]:ac = ORAAbs [[COPY]], i16 1234 :: (load (s8))
    ; 6502-NEXT: RTS implicit [[ORAAbs]]
    ;
    ; 65C02-LABEL: name: ora_abs
    ; 65C02: [[COPY:%[0-9]+]]:ac = COPY $x
    ; 65C02-NEXT: [[ORAAbs:%[0-9]+]]:ac = ORAAbs [[COPY]], i16 1234 :: (load (s8))
    ; 65C02-NEXT: RTS implicit [[ORAAbs]]
    %0:any(s8) = COPY $x
    %1:any(s8) = G_LOAD_ABS i16 1234 :: (load (s8))
    %2:any(s8) = G_OR %0, %1
    RTS implicit %2
...
---
name: ora_zp_idx
legalized: true
regBankSelected: true
body: |
  bb.0.entry:
    ; 6502-LABEL: name: ora_zp_idx
    ; 6502: [[COPY:%[0-9]+]]:ac = COPY $x
    ; 6502-NEXT: [[COPY1:%[0-9]+]]:xc = COPY [[COPY]]
    ; 6502-NEXT: [[ORAZpIdx:%[0-9]+]]:ac = ORAZpIdx [[COPY]], i8 123, [[COPY1]] :: (load (s8))
    ; 6502-NEXT: RTS implicit [[ORAZpIdx]]
    ;
    ; 65C02-LABEL: name: ora_zp_idx
    ; 65C02: [[COPY:%[0-9]+]]:ac = COPY $x
    ; 65C02-NEXT: [[COPY1:%[0-9]+]]:xc = COPY [[COPY]]
    ; 65C02-NEXT: [[ORAZpIdx:%[0-9]+]]:ac = ORAZpIdx [[COPY]], i8 123, [[COPY1]] :: (load (s8))
    ; 65C02-NEXT: RTS implicit [[ORAZpIdx]]
    %0:any(s8) = COPY $x
    %1:any(s8) = G_LOAD_ZP_IDX i8 123, %0 :: (load (s8))
    %2:any(s8) = G_OR %0, %1
    RTS implicit %2
...
---
name: ora_abs_idx
legalized: true
regBankSelected: true
body: |
  bb.0.entry:
    ; 6502-LABEL: name: ora_abs_idx
    ; 6502: [[COPY:%[0-9]+]]:ac = COPY $x
    ; 6502-NEXT: [[COPY1:%[0-9]+]]:xy = COPY [[COPY]]
    ; 6502-NEXT: [[ORAAbsIdx:%[0-9]+]]:ac = ORAAbsIdx [[COPY]], i16 1234, [[COPY1]] :: (load (s8))
    ; 6502-NEXT: RTS implicit [[ORAAbsIdx]]
    ;
    ; 65C02-LABEL: name: ora_abs_idx
    ; 65C02: [[COPY:%[0-9]+]]:ac = COPY $x
    ; 65C02-NEXT: [[COPY1:%[0-9]+]]:xy = COPY [[COPY]]
    ; 65C02-NEXT: [[ORAAbsIdx:%[0-9]+]]:ac = ORAAbsIdx [[COPY]], i16 1234, [[COPY1]] :: (load (s8))
    ; 65C02-NEXT: RTS implicit [[ORAAbsIdx]]
    %0:any(s8) = COPY $x
    %1:any(s8) = G_LOAD_ABS_IDX i16 1234, %0 :: (load (s8))
    %2:any(s8) = G_OR %0, %1
    RTS implicit %2
...
---
name: ora_y_indir
legalized: true
regBankSelected: true
body: |
  bb.0.entry:
    ; 6502-LABEL: name: ora_y_indir
    ; 6502: [[COPY:%[0-9]+]]:imag16 = COPY $rs1
    ; 6502-NEXT: [[COPY1:%[0-9]+]]:ac = COPY $x
    ; 6502-NEXT: [[ORAIndir:%[0-9]+]]:ac = ORAIndir [[COPY1]], [[COPY]] :: (load (s8))
    ; 6502-NEXT: RTS implicit [[ORAIndir]]
    ;
    ; 65C02-LABEL: name: ora_y_indir
    ; 65C02: [[COPY:%[0-9]+]]:imag16 = COPY $rs1
    ; 65C02-NEXT: [[COPY1:%[0-9]+]]:ac = COPY $x
    ; 65C02-NEXT: [[ORAIndir:%[0-9]+]]:ac = ORAIndir [[COPY1]], [[COPY]] :: (load (s8))
    ; 65C02-NEXT: RTS implicit [[ORAIndir]]
    %0:any(s16) = COPY $rs1
    %1:any(s8) = COPY $x
    %2:any(s8) = G_LOAD_INDIR %0 :: (load (s8))
    %3:any(s8) = G_OR %1, %2
    RTS implicit %3
...
---
name: ora_y_indir_idx
legalized: true
regBankSelected: true
body: |
  bb.0.entry:
    ; 6502-LABEL: name: ora_y_indir_idx
    ; 6502: [[COPY:%[0-9]+]]:imag16 = COPY $rs1
    ; 6502-NEXT: [[COPY1:%[0-9]+]]:ac = COPY $x
    ; 6502-NEXT: [[COPY2:%[0-9]+]]:yc = COPY [[COPY1]]
    ; 6502-NEXT: [[ORAIndirIdx:%[0-9]+]]:ac = ORAIndirIdx [[COPY1]], [[COPY]], [[COPY2]] :: (load (s8))
    ; 6502-NEXT: RTS implicit [[ORAIndirIdx]]
    ;
    ; 65C02-LABEL: name: ora_y_indir_idx
    ; 65C02: [[COPY:%[0-9]+]]:imag16 = COPY $rs1
    ; 65C02-NEXT: [[COPY1:%[0-9]+]]:ac = COPY $x
    ; 65C02-NEXT: [[COPY2:%[0-9]+]]:yc = COPY [[COPY1]]
    ; 65C02-NEXT: [[ORAIndirIdx:%[0-9]+]]:ac = ORAIndirIdx [[COPY1]], [[COPY]], [[COPY2]] :: (load (s8))
    ; 65C02-NEXT: RTS implicit [[ORAIndirIdx]]
    %0:any(s16) = COPY $rs1
    %1:any(s8) = COPY $x
    %2:any(s8) = G_LOAD_INDIR_IDX %0, %1 :: (load (s8))
    %3:any(s8) = G_OR %1, %2
    RTS implicit %3
...
---
name: asl_abs
legalized: true
regBankSelected: true
body: |
  bb.0.entry:
    ; 6502-LABEL: name: asl_abs
    ; 6502: [[ASLAbs:%[0-9]+]]:cc = ASLAbs i16 1234 :: (store (s8)), (load (s8))
    ; 6502-NEXT: RTS implicit [[ASLAbs]]
    ;
    ; 65C02-LABEL: name: asl_abs
    ; 65C02: [[ASLAbs:%[0-9]+]]:cc = ASLAbs i16 1234 :: (store (s8)), (load (s8))
    ; 65C02-NEXT: RTS implicit [[ASLAbs]]
    %0:any(s8) = G_LOAD_ABS i16 1234 :: (load (s8))
    %1:any(s1) = G_CONSTANT i1 0
    %2:any(s8), %3:any(s1) = G_SHLE %0, %1
    G_STORE_ABS %2, i16 1234 :: (store (s8))
    RTS implicit %3
...
---
name: asl_abs_c_used_between
legalized: true
regBankSelected: true
body: |
  bb.0.entry:
    ; 6502-LABEL: name: asl_abs_c_used_between
    ; 6502: [[LDAbs:%[0-9]+]]:ac = LDAbs i16 1234 :: (load (s8))
    ; 6502-NEXT: [[ASL:%[0-9]+]]:aimag8, [[ASL1:%[0-9]+]]:cc = ASL [[LDAbs]]
    ; 6502-NEXT: [[COPY:%[0-9]+]]:anyi1 = COPY [[ASL1]]
    ; 6502-NEXT: [[ASLAbs:%[0-9]+]]:cc = ASLAbs i16 1234 :: (store (s8)), (load (s8))
    ; 6502-NEXT: RTS implicit [[COPY]]
    ;
    ; 65C02-LABEL: name: asl_abs_c_used_between
    ; 65C02: [[LDAbs:%[0-9]+]]:ac = LDAbs i16 1234 :: (load (s8))
    ; 65C02-NEXT: [[ASL:%[0-9]+]]:aimag8, [[ASL1:%[0-9]+]]:cc = ASL [[LDAbs]]
    ; 65C02-NEXT: [[COPY:%[0-9]+]]:anyi1 = COPY [[ASL1]]
    ; 65C02-NEXT: [[ASLAbs:%[0-9]+]]:cc = ASLAbs i16 1234 :: (store (s8)), (load (s8))
    ; 65C02-NEXT: RTS implicit [[COPY]]
    %0:any(s8) = G_LOAD_ABS i16 1234 :: (load (s8))
    %1:any(s1) = G_CONSTANT i1 0
    %2:any(s8), %3:any(s1) = G_SHLE %0, %1
    %4:any(s1) = COPY %3
    G_STORE_ABS %2, i16 1234 :: (store (s8))
    RTS implicit %4
...
---
name: asl_absidx
legalized: true
regBankSelected: true
body: |
  bb.0.entry:
    liveins: $x
    ; 6502-LABEL: name: asl_absidx
    ; 6502: liveins: $x
    ; 6502-NEXT: {{  $}}
    ; 6502-NEXT: [[COPY:%[0-9]+]]:xc = COPY $x
    ; 6502-NEXT: [[ASLIdx:%[0-9]+]]:cc = ASLIdx i16 1234, [[COPY]] :: (store (s8)), (load (s8))
    ; 6502-NEXT: RTS implicit [[ASLIdx]]
    ;
    ; 65C02-LABEL: name: asl_absidx
    ; 65C02: liveins: $x
    ; 65C02-NEXT: {{  $}}
    ; 65C02-NEXT: [[COPY:%[0-9]+]]:xc = COPY $x
    ; 65C02-NEXT: [[ASLIdx:%[0-9]+]]:cc = ASLIdx i16 1234, [[COPY]] :: (store (s8)), (load (s8))
    ; 65C02-NEXT: RTS implicit [[ASLIdx]]
    %0:any(s8) = COPY $x
    %1:any(s8) = G_LOAD_ABS_IDX i16 1234, %0 :: (load (s8))
    %2:any(s8) = G_CONSTANT i8 0
    %3:any(s8), %4:any(s1) = G_SHLE %1, %2
    G_STORE_ABS_IDX %3, i16 1234, %0 :: (store (s8))
    RTS implicit %4
...
---
name: inc_abs
legalized: true
regBankSelected: true
body: |
  bb.0.entry:
    ; 6502-LABEL: name: inc_abs
    ; 6502: INCAbs i16 1234 :: (store (s8)), (load (s8))
    ; 6502-NEXT: RTS
    ;
    ; 65C02-LABEL: name: inc_abs
    ; 65C02: INCAbs i16 1234 :: (store (s8)), (load (s8))
    ; 65C02-NEXT: RTS
    %0:any(s8) = G_LOAD_ABS i16 1234 :: (load (s8))
    %1:any(s8) = G_CONSTANT i8 1
    %2:any(s8) = G_ADD %0, %1
    G_STORE_ABS %2, i16 1234 :: (store (s8))
    RTS
...
---
name: inc_abs_across_store
legalized: true
regBankSelected: true
body: |
  bb.0.entry:
    ; 6502-LABEL: name: inc_abs_across_store
    ; 6502: [[LDAbs:%[0-9]+]]:gpr = LDAbs i16 1234 :: (load (s8))
    ; 6502-NEXT: [[LDImm:%[0-9]+]]:gpr = LDImm 1
    ; 6502-NEXT: [[IncNMOS:%[0-9]+]]:gpr = IncNMOS [[LDAbs]], implicit-def dead $c, implicit-def dead $v
    ; 6502-NEXT: STAbs [[LDImm]], i16 1234 :: (store (s8))
    ; 6502-NEXT: STAbs [[IncNMOS]], i16 1234 :: (store (s8))
    ; 6502-NEXT: RTS
    ;
    ; 65C02-LABEL: name: inc_abs_across_store
    ; 65C02: [[LDAbs:%[0-9]+]]:gpr = LDAbs i16 1234 :: (load (s8))
    ; 65C02-NEXT: [[LDImm:%[0-9]+]]:gpr = LDImm 1
    ; 65C02-NEXT: [[INC:%[0-9]+]]:gpr = INC [[LDAbs]]
    ; 65C02-NEXT: STAbs [[LDImm]], i16 1234 :: (store (s8))
    ; 65C02-NEXT: STAbs [[INC]], i16 1234 :: (store (s8))
    ; 65C02-NEXT: RTS
    %0:any(s8) = G_LOAD_ABS i16 1234 :: (load (s8))
    %1:any(s8) = G_CONSTANT i8 1
    %2:any(s8) = G_ADD %0, %1
    G_STORE_ABS %1, i16 1234 :: (store (s8))
    G_STORE_ABS %2, i16 1234 :: (store (s8))
    RTS
...
---
name: inc_absidx
legalized: true
regBankSelected: true
body: |
  bb.0.entry:
    liveins: $x
    ; 6502-LABEL: name: inc_absidx
    ; 6502: liveins: $x
    ; 6502-NEXT: {{  $}}
    ; 6502-NEXT: [[COPY:%[0-9]+]]:xc = COPY $x
    ; 6502-NEXT: INCIdx i16 1234, [[COPY]] :: (store (s8)), (load (s8))
    ; 6502-NEXT: RTS
    ;
    ; 65C02-LABEL: name: inc_absidx
    ; 65C02: liveins: $x
    ; 65C02-NEXT: {{  $}}
    ; 65C02-NEXT: [[COPY:%[0-9]+]]:xc = COPY $x
    ; 65C02-NEXT: INCIdx i16 1234, [[COPY]] :: (store (s8)), (load (s8))
    ; 65C02-NEXT: RTS
    %0:any(s8) = COPY $x
    %1:any(s8) = G_LOAD_ABS_IDX i16 1234, %0 :: (load (s8))
    %2:any(s8) = G_CONSTANT i8 1
    %3:any(s8) = G_ADD %1, %2
    G_STORE_ABS_IDX %3, i16 1234, %0 :: (store (s8))
    RTS
...
---
name: inc_abs_volatile_load
legalized: true
regBankSelected: true
body: |
  bb.0.entry:
    ; 6502-LABEL: name: inc_abs_volatile_load
    ; 6502: [[LDAbs:%[0-9]+]]:gpr = LDAbs i16 1234 :: (volatile load (s8))
    ; 6502-NEXT: [[IncNMOS:%[0-9]+]]:gpr = IncNMOS [[LDAbs]], implicit-def dead $c, implicit-def dead $v
    ; 6502-NEXT: STAbs [[IncNMOS]], i16 1234 :: (store (s8))
    ; 6502-NEXT: RTS
    ;
    ; 65C02-LABEL: name: inc_abs_volatile_load
    ; 65C02: [[LDAbs:%[0-9]+]]:gpr = LDAbs i16 1234 :: (volatile load (s8))
    ; 65C02-NEXT: [[INC:%[0-9]+]]:gpr = INC [[LDAbs]]
    ; 65C02-NEXT: STAbs [[INC]], i16 1234 :: (store (s8))
    ; 65C02-NEXT: RTS
    %0:any(s8) = G_LOAD_ABS i16 1234 :: (volatile load (s8))
    %1:any(s8) = G_CONSTANT i8 1
    %2:any(s8) = G_ADD %0, %1
    G_STORE_ABS %2, i16 1234 :: (store (s8))
    RTS
...
---
name: inc_abs_volatile_store
legalized: true
regBankSelected: true
body: |
  bb.0.entry:
    ; 6502-LABEL: name: inc_abs_volatile_store
    ; 6502: [[LDAbs:%[0-9]+]]:gpr = LDAbs i16 1234 :: (load (s8))
    ; 6502-NEXT: [[IncNMOS:%[0-9]+]]:gpr = IncNMOS [[LDAbs]], implicit-def dead $c, implicit-def dead $v
    ; 6502-NEXT: STAbs [[IncNMOS]], i16 1234 :: (volatile store (s8))
    ; 6502-NEXT: RTS
    ;
    ; 65C02-LABEL: name: inc_abs_volatile_store
    ; 65C02: [[LDAbs:%[0-9]+]]:gpr = LDAbs i16 1234 :: (load (s8))
    ; 65C02-NEXT: [[INC:%[0-9]+]]:gpr = INC [[LDAbs]]
    ; 65C02-NEXT: STAbs [[INC]], i16 1234 :: (volatile store (s8))
    ; 65C02-NEXT: RTS
    %0:any(s8) = G_LOAD_ABS i16 1234 :: (load (s8))
    %1:any(s8) = G_CONSTANT i8 1
    %2:any(s8) = G_ADD %0, %1
    G_STORE_ABS %2, i16 1234 :: (volatile store (s8))
    RTS
...
---
name: dec_abs
legalized: true
regBankSelected: true
body: |
  bb.0.entry:
    ; 6502-LABEL: name: dec_abs
    ; 6502: DECAbs i16 1234 :: (store (s8)), (load (s8))
    ; 6502-NEXT: RTS
    ;
    ; 65C02-LABEL: name: dec_abs
    ; 65C02: DECAbs i16 1234 :: (store (s8)), (load (s8))
    ; 65C02-NEXT: RTS
    %0:any(s8) = G_LOAD_ABS i16 1234 :: (load (s8))
    %1:any(s8) = G_CONSTANT i8 -1
    %2:any(s8) = G_ADD %0, %1
    G_STORE_ABS %2, i16 1234 :: (store (s8))
    RTS
...
---
name: dec_absidx
legalized: true
regBankSelected: true
body: |
  bb.0.entry:
    liveins: $x
    ; 6502-LABEL: name: dec_absidx
    ; 6502: liveins: $x
    ; 6502-NEXT: {{  $}}
    ; 6502-NEXT: [[COPY:%[0-9]+]]:xc = COPY $x
    ; 6502-NEXT: DECIdx i16 1234, [[COPY]] :: (store (s8)), (load (s8))
    ; 6502-NEXT: RTS
    ;
    ; 65C02-LABEL: name: dec_absidx
    ; 65C02: liveins: $x
    ; 65C02-NEXT: {{  $}}
    ; 65C02-NEXT: [[COPY:%[0-9]+]]:xc = COPY $x
    ; 65C02-NEXT: DECIdx i16 1234, [[COPY]] :: (store (s8)), (load (s8))
    ; 65C02-NEXT: RTS
    %0:any(s8) = COPY $x
    %1:any(s8) = G_LOAD_ABS_IDX i16 1234, %0 :: (load (s8))
    %2:any(s8) = G_CONSTANT i8 -1
    %3:any(s8) = G_ADD %1, %2
    G_STORE_ABS_IDX %3, i16 1234, %0 :: (store (s8))
    RTS
...
---
name: lsr_abs
legalized: true
regBankSelected: true
body: |
  bb.0.entry:
    ; 6502-LABEL: name: lsr_abs
    ; 6502: [[LSRAbs:%[0-9]+]]:cc = LSRAbs i16 1234 :: (store (s8)), (load (s8))
    ; 6502-NEXT: RTS implicit [[LSRAbs]]
    ;
    ; 65C02-LABEL: name: lsr_abs
    ; 65C02: [[LSRAbs:%[0-9]+]]:cc = LSRAbs i16 1234 :: (store (s8)), (load (s8))
    ; 65C02-NEXT: RTS implicit [[LSRAbs]]
    %0:any(s8) = G_LOAD_ABS i16 1234 :: (load (s8))
    %1:any(s1) = G_CONSTANT i1 0
    %2:any(s8), %3:any(s1) = G_LSHRE %0, %1
    G_STORE_ABS %2, i16 1234 :: (store (s8))
    RTS implicit %3
...
---
name: lsr_absidx
legalized: true
regBankSelected: true
body: |
  bb.0.entry:
    liveins: $x
    ; 6502-LABEL: name: lsr_absidx
    ; 6502: liveins: $x
    ; 6502-NEXT: {{  $}}
    ; 6502-NEXT: [[COPY:%[0-9]+]]:xc = COPY $x
    ; 6502-NEXT: [[LSRIdx:%[0-9]+]]:cc = LSRIdx i16 1234, [[COPY]] :: (store (s8)), (load (s8))
    ; 6502-NEXT: RTS implicit [[LSRIdx]]
    ;
    ; 65C02-LABEL: name: lsr_absidx
    ; 65C02: liveins: $x
    ; 65C02-NEXT: {{  $}}
    ; 65C02-NEXT: [[COPY:%[0-9]+]]:xc = COPY $x
    ; 65C02-NEXT: [[LSRIdx:%[0-9]+]]:cc = LSRIdx i16 1234, [[COPY]] :: (store (s8)), (load (s8))
    ; 65C02-NEXT: RTS implicit [[LSRIdx]]
    %0:any(s8) = COPY $x
    %1:any(s8) = G_LOAD_ABS_IDX i16 1234, %0 :: (load (s8))
    %2:any(s8) = G_CONSTANT i8 0
    %3:any(s8), %4:any(s1) = G_LSHRE %1, %2
    G_STORE_ABS_IDX %3, i16 1234, %0 :: (store (s8))
    RTS implicit %4
...
---
name: rol_abs
legalized: true
regBankSelected: true
body: |
  bb.0.entry:
    ; 6502-LABEL: name: rol_abs
    ; 6502: [[COPY:%[0-9]+]]:cc = COPY $v
    ; 6502-NEXT: [[ROLAbs:%[0-9]+]]:cc = ROLAbs i16 1234, [[COPY]] :: (store (s8)), (load (s8))
    ; 6502-NEXT: RTS implicit [[ROLAbs]]
    ;
    ; 65C02-LABEL: name: rol_abs
    ; 65C02: [[COPY:%[0-9]+]]:cc = COPY $v
    ; 65C02-NEXT: [[ROLAbs:%[0-9]+]]:cc = ROLAbs i16 1234, [[COPY]] :: (store (s8)), (load (s8))
    ; 65C02-NEXT: RTS implicit [[ROLAbs]]
    %0:any(s8) = G_LOAD_ABS i16 1234 :: (load (s8))
    %1:any(s1) = COPY $v
    %2:any(s8), %3:any(s1) = G_SHLE %0, %1
    G_STORE_ABS %2, i16 1234 :: (store (s8))
    RTS implicit %3
...
---
name: rol_absidx
legalized: true
regBankSelected: true
body: |
  bb.0.entry:
    liveins: $x
    ; 6502-LABEL: name: rol_absidx
    ; 6502: liveins: $x
    ; 6502-NEXT: {{  $}}
    ; 6502-NEXT: [[COPY:%[0-9]+]]:xc = COPY $x
    ; 6502-NEXT: [[COPY1:%[0-9]+]]:cc = COPY $v
    ; 6502-NEXT: [[ROLIdx:%[0-9]+]]:cc = ROLIdx i16 1234, [[COPY]], [[COPY1]] :: (store (s8)), (load (s8))
    ; 6502-NEXT: RTS implicit [[ROLIdx]]
    ;
    ; 65C02-LABEL: name: rol_absidx
    ; 65C02: liveins: $x
    ; 65C02-NEXT: {{  $}}
    ; 65C02-NEXT: [[COPY:%[0-9]+]]:xc = COPY $x
    ; 65C02-NEXT: [[COPY1:%[0-9]+]]:cc = COPY $v
    ; 65C02-NEXT: [[ROLIdx:%[0-9]+]]:cc = ROLIdx i16 1234, [[COPY]], [[COPY1]] :: (store (s8)), (load (s8))
    ; 65C02-NEXT: RTS implicit [[ROLIdx]]
    %0:any(s8) = COPY $x
    %1:any(s8) = G_LOAD_ABS_IDX i16 1234, %0 :: (load (s8))
    %2:any(s1) = COPY $v
    %3:any(s8), %4:any(s1) = G_SHLE %1, %2
    G_STORE_ABS_IDX %3, i16 1234, %0 :: (store (s8))
    RTS implicit %4
...
---
name: ror_abs
legalized: true
regBankSelected: true
body: |
  bb.0.entry:
    ; 6502-LABEL: name: ror_abs
    ; 6502: [[COPY:%[0-9]+]]:cc = COPY $v
    ; 6502-NEXT: [[RORAbs:%[0-9]+]]:cc = RORAbs i16 1234, [[COPY]] :: (store (s8)), (load (s8))
    ; 6502-NEXT: RTS implicit [[RORAbs]]
    ;
    ; 65C02-LABEL: name: ror_abs
    ; 65C02: [[COPY:%[0-9]+]]:cc = COPY $v
    ; 65C02-NEXT: [[RORAbs:%[0-9]+]]:cc = RORAbs i16 1234, [[COPY]] :: (store (s8)), (load (s8))
    ; 65C02-NEXT: RTS implicit [[RORAbs]]
    %0:any(s8) = G_LOAD_ABS i16 1234 :: (load (s8))
    %1:any(s1) = COPY $v
    %2:any(s8), %3:any(s1) = G_LSHRE %0, %1
    G_STORE_ABS %2, i16 1234 :: (store (s8))
    RTS implicit %3
...
---
name: ror_absidx
legalized: true
regBankSelected: true
body: |
  bb.0.entry:
    liveins: $x
    ; 6502-LABEL: name: ror_absidx
    ; 6502: liveins: $x
    ; 6502-NEXT: {{  $}}
    ; 6502-NEXT: [[COPY:%[0-9]+]]:xc = COPY $x
    ; 6502-NEXT: [[COPY1:%[0-9]+]]:cc = COPY $v
    ; 6502-NEXT: [[RORIdx:%[0-9]+]]:cc = RORIdx i16 1234, [[COPY]], [[COPY1]] :: (store (s8)), (load (s8))
    ; 6502-NEXT: RTS implicit [[RORIdx]]
    ;
    ; 65C02-LABEL: name: ror_absidx
    ; 65C02: liveins: $x
    ; 65C02-NEXT: {{  $}}
    ; 65C02-NEXT: [[COPY:%[0-9]+]]:xc = COPY $x
    ; 65C02-NEXT: [[COPY1:%[0-9]+]]:cc = COPY $v
    ; 65C02-NEXT: [[RORIdx:%[0-9]+]]:cc = RORIdx i16 1234, [[COPY]], [[COPY1]] :: (store (s8)), (load (s8))
    ; 65C02-NEXT: RTS implicit [[RORIdx]]
    %0:any(s8) = COPY $x
    %1:any(s8) = G_LOAD_ABS_IDX i16 1234, %0 :: (load (s8))
    %2:any(s1) = COPY $v
    %3:any(s8), %4:any(s1) = G_LSHRE %1, %2
    G_STORE_ABS_IDX %3, i16 1234, %0 :: (store (s8))
    RTS implicit %4
...
---
name: sub
legalized: true
regBankSelected: true
body: |
  bb.0.entry:
    ; 6502-LABEL: name: sub
    ; 6502: [[COPY:%[0-9]+]]:ac = COPY $x
    ; 6502-NEXT: [[COPY1:%[0-9]+]]:imag8 = COPY $a
    ; 6502-NEXT: [[LDCImm:%[0-9]+]]:cc = LDCImm -1
    ; 6502-NEXT: [[SBCImag8_:%[0-9]+]]:ac, dead [[SBCImag8_1:%[0-9]+]]:cc, dead [[SBCImag8_2:%[0-9]+]]:vc = SBCImag8 [[COPY]], [[COPY1]], [[LDCImm]]
    ; 6502-NEXT: RTS implicit [[SBCImag8_]]
    ;
    ; 65C02-LABEL: name: sub
    ; 65C02: [[COPY:%[0-9]+]]:ac = COPY $x
    ; 65C02-NEXT: [[COPY1:%[0-9]+]]:imag8 = COPY $a
    ; 65C02-NEXT: [[LDCImm:%[0-9]+]]:cc = LDCImm -1
    ; 65C02-NEXT: [[SBCImag8_:%[0-9]+]]:ac, dead [[SBCImag8_1:%[0-9]+]]:cc, dead [[SBCImag8_2:%[0-9]+]]:vc = SBCImag8 [[COPY]], [[COPY1]], [[LDCImm]]
    ; 65C02-NEXT: RTS implicit [[SBCImag8_]]
    %0:any(s8) = COPY $x
    %1:any(s8) = COPY $a
    %2:any(s8) = G_SUB %0, %1
    RTS implicit %2
...
---
name: sub_imm
legalized: true
regBankSelected: true
body: |
  bb.0.entry:
    ; 6502-LABEL: name: sub_imm
    ; 6502: [[COPY:%[0-9]+]]:ac = COPY $x
    ; 6502-NEXT: [[LDCImm:%[0-9]+]]:cc = LDCImm -1
    ; 6502-NEXT: [[SBCImm:%[0-9]+]]:ac, dead [[SBCImm1:%[0-9]+]]:cc, dead [[SBCImm2:%[0-9]+]]:vc = SBCImm [[COPY]], 42, [[LDCImm]]
    ; 6502-NEXT: RTS implicit [[SBCImm]]
    ;
    ; 65C02-LABEL: name: sub_imm
    ; 65C02: [[COPY:%[0-9]+]]:ac = COPY $x
    ; 65C02-NEXT: [[LDCImm:%[0-9]+]]:cc = LDCImm -1
    ; 65C02-NEXT: [[SBCImm:%[0-9]+]]:ac, dead [[SBCImm1:%[0-9]+]]:cc, dead [[SBCImm2:%[0-9]+]]:vc = SBCImm [[COPY]], 42, [[LDCImm]]
    ; 65C02-NEXT: RTS implicit [[SBCImm]]
    %0:any(s8) = COPY $x
    %1:any(s8) = G_CONSTANT i8 42
    %2:any(s8) = G_SUB %0, %1
    RTS implicit %2
...
---
name: sub_abs
legalized: true
regBankSelected: true
body: |
  bb.0.entry:
    ; 6502-LABEL: name: sub_abs
    ; 6502: [[COPY:%[0-9]+]]:ac = COPY $x
    ; 6502-NEXT: [[LDCImm:%[0-9]+]]:cc = LDCImm -1
    ; 6502-NEXT: [[SBCAbs:%[0-9]+]]:ac, [[SBCAbs1:%[0-9]+]]:cc, [[SBCAbs2:%[0-9]+]]:vc = SBCAbs [[COPY]], i16 1234, [[LDCImm]] :: (load (s8))
    ; 6502-NEXT: RTS implicit [[SBCAbs]]
    ;
    ; 65C02-LABEL: name: sub_abs
    ; 65C02: [[COPY:%[0-9]+]]:ac = COPY $x
    ; 65C02-NEXT: [[LDCImm:%[0-9]+]]:cc = LDCImm -1
    ; 65C02-NEXT: [[SBCAbs:%[0-9]+]]:ac, [[SBCAbs1:%[0-9]+]]:cc, [[SBCAbs2:%[0-9]+]]:vc = SBCAbs [[COPY]], i16 1234, [[LDCImm]] :: (load (s8))
    ; 65C02-NEXT: RTS implicit [[SBCAbs]]
    %0:any(s8) = COPY $x
    %1:any(s8) = G_LOAD_ABS i16 1234 :: (load (s8))
    %2:any(s8) = G_SUB %0, %1
    RTS implicit %2
...
---
name: sub_zp_idx
legalized: true
regBankSelected: true
body: |
  bb.0.entry:
    ; 6502-LABEL: name: sub_zp_idx
    ; 6502: [[COPY:%[0-9]+]]:ac = COPY $x
    ; 6502-NEXT: [[COPY1:%[0-9]+]]:xc = COPY $a
    ; 6502-NEXT: [[LDCImm:%[0-9]+]]:cc = LDCImm -1
    ; 6502-NEXT: [[SBCZpIdx:%[0-9]+]]:ac, [[SBCZpIdx1:%[0-9]+]]:cc, [[SBCZpIdx2:%[0-9]+]]:vc = SBCZpIdx [[COPY]], i8 123, [[COPY1]], [[LDCImm]] :: (load (s8))
    ; 6502-NEXT: RTS implicit [[SBCZpIdx]]
    ;
    ; 65C02-LABEL: name: sub_zp_idx
    ; 65C02: [[COPY:%[0-9]+]]:ac = COPY $x
    ; 65C02-NEXT: [[COPY1:%[0-9]+]]:xc = COPY $a
    ; 65C02-NEXT: [[LDCImm:%[0-9]+]]:cc = LDCImm -1
    ; 65C02-NEXT: [[SBCZpIdx:%[0-9]+]]:ac, [[SBCZpIdx1:%[0-9]+]]:cc, [[SBCZpIdx2:%[0-9]+]]:vc = SBCZpIdx [[COPY]], i8 123, [[COPY1]], [[LDCImm]] :: (load (s8))
    ; 65C02-NEXT: RTS implicit [[SBCZpIdx]]
    %0:any(s8) = COPY $x
    %1:any(s8) = COPY $a
    %2:any(s8) = G_LOAD_ZP_IDX i8 123, %1 :: (load (s8))
    %3:any(s8) = G_SUB %0, %2
    RTS implicit %3
...
---
name: sub_abs_idx
legalized: true
regBankSelected: true
body: |
  bb.0.entry:
    ; 6502-LABEL: name: sub_abs_idx
    ; 6502: [[COPY:%[0-9]+]]:ac = COPY $x
    ; 6502-NEXT: [[COPY1:%[0-9]+]]:xy = COPY $a
    ; 6502-NEXT: [[LDCImm:%[0-9]+]]:cc = LDCImm -1
    ; 6502-NEXT: [[SBCAbsIdx:%[0-9]+]]:ac, [[SBCAbsIdx1:%[0-9]+]]:cc, [[SBCAbsIdx2:%[0-9]+]]:vc = SBCAbsIdx [[COPY]], i16 1234, [[COPY1]], [[LDCImm]] :: (load (s8))
    ; 6502-NEXT: RTS implicit [[SBCAbsIdx]]
    ;
    ; 65C02-LABEL: name: sub_abs_idx
    ; 65C02: [[COPY:%[0-9]+]]:ac = COPY $x
    ; 65C02-NEXT: [[COPY1:%[0-9]+]]:xy = COPY $a
    ; 65C02-NEXT: [[LDCImm:%[0-9]+]]:cc = LDCImm -1
    ; 65C02-NEXT: [[SBCAbsIdx:%[0-9]+]]:ac, [[SBCAbsIdx1:%[0-9]+]]:cc, [[SBCAbsIdx2:%[0-9]+]]:vc = SBCAbsIdx [[COPY]], i16 1234, [[COPY1]], [[LDCImm]] :: (load (s8))
    ; 65C02-NEXT: RTS implicit [[SBCAbsIdx]]
    %0:any(s8) = COPY $x
    %1:any(s8) = COPY $a
    %2:any(s8) = G_LOAD_ABS_IDX i16 1234, %1 :: (load (s8))
    %3:any(s8) = G_SUB %0, %2
    RTS implicit %3
...
---
name: sub_indir
legalized: true
regBankSelected: true
body: |
  bb.0.entry:
    ; 6502-LABEL: name: sub_indir
    ; 6502: [[COPY:%[0-9]+]]:ac = COPY $x
    ; 6502-NEXT: [[COPY1:%[0-9]+]]:imag16 = COPY $rs1
    ; 6502-NEXT: [[LDCImm:%[0-9]+]]:cc = LDCImm -1
    ; 6502-NEXT: [[SBCIndir:%[0-9]+]]:ac, [[SBCIndir1:%[0-9]+]]:cc, [[SBCIndir2:%[0-9]+]]:vc = SBCIndir [[COPY]], [[COPY1]], [[LDCImm]] :: (load (s8))
    ; 6502-NEXT: RTS implicit [[SBCIndir]]
    ;
    ; 65C02-LABEL: name: sub_indir
    ; 65C02: [[COPY:%[0-9]+]]:ac = COPY $x
    ; 65C02-NEXT: [[COPY1:%[0-9]+]]:imag16 = COPY $rs1
    ; 65C02-NEXT: [[LDCImm:%[0-9]+]]:cc = LDCImm -1
    ; 65C02-NEXT: [[SBCIndir:%[0-9]+]]:ac, [[SBCIndir1:%[0-9]+]]:cc, [[SBCIndir2:%[0-9]+]]:vc = SBCIndir [[COPY]], [[COPY1]], [[LDCImm]] :: (load (s8))
    ; 65C02-NEXT: RTS implicit [[SBCIndir]]
    %0:any(s8) = COPY $x
    %1:any(s16) = COPY $rs1
    %2:any(s8) = G_LOAD_INDIR %1 :: (load (s8))
    %3:any(s8) = G_SUB %0, %2
    RTS implicit %3
...
---
name: sub_indir_idx
legalized: true
regBankSelected: true
body: |
  bb.0.entry:
    ; 6502-LABEL: name: sub_indir_idx
    ; 6502: [[COPY:%[0-9]+]]:ac = COPY $x
    ; 6502-NEXT: [[COPY1:%[0-9]+]]:imag16 = COPY $rs1
    ; 6502-NEXT: [[COPY2:%[0-9]+]]:yc = COPY $a
    ; 6502-NEXT: [[LDCImm:%[0-9]+]]:cc = LDCImm -1
    ; 6502-NEXT: [[SBCIndirIdx:%[0-9]+]]:ac, [[SBCIndirIdx1:%[0-9]+]]:cc, [[SBCIndirIdx2:%[0-9]+]]:vc = SBCIndirIdx [[COPY]], [[COPY1]], [[COPY2]], [[LDCImm]] :: (load (s8))
    ; 6502-NEXT: RTS implicit [[SBCIndirIdx]]
    ;
    ; 65C02-LABEL: name: sub_indir_idx
    ; 65C02: [[COPY:%[0-9]+]]:ac = COPY $x
    ; 65C02-NEXT: [[COPY1:%[0-9]+]]:imag16 = COPY $rs1
    ; 65C02-NEXT: [[COPY2:%[0-9]+]]:yc = COPY $a
    ; 65C02-NEXT: [[LDCImm:%[0-9]+]]:cc = LDCImm -1
    ; 65C02-NEXT: [[SBCIndirIdx:%[0-9]+]]:ac, [[SBCIndirIdx1:%[0-9]+]]:cc, [[SBCIndirIdx2:%[0-9]+]]:vc = SBCIndirIdx [[COPY]], [[COPY1]], [[COPY2]], [[LDCImm]] :: (load (s8))
    ; 65C02-NEXT: RTS implicit [[SBCIndirIdx]]
    %0:any(s8) = COPY $x
    %1:any(s16) = COPY $rs1
    %2:any(s8) = COPY $a
    %3:any(s8) = G_LOAD_INDIR_IDX %1, %2 :: (load (s8))
    %4:any(s8) = G_SUB %0, %3
    RTS implicit %4
...
---
name: and
legalized: true
regBankSelected: true
body: |
  bb.0.entry:
    ; 6502-LABEL: name: and
    ; 6502: [[COPY:%[0-9]+]]:ac = COPY $x
    ; 6502-NEXT: [[COPY1:%[0-9]+]]:imag8 = COPY $a
    ; 6502-NEXT: [[ANDImag8_:%[0-9]+]]:ac = ANDImag8 [[COPY]], [[COPY1]]
    ; 6502-NEXT: RTS implicit [[ANDImag8_]]
    ;
    ; 65C02-LABEL: name: and
    ; 65C02: [[COPY:%[0-9]+]]:ac = COPY $x
    ; 65C02-NEXT: [[COPY1:%[0-9]+]]:imag8 = COPY $a
    ; 65C02-NEXT: [[ANDImag8_:%[0-9]+]]:ac = ANDImag8 [[COPY]], [[COPY1]]
    ; 65C02-NEXT: RTS implicit [[ANDImag8_]]
    %0:any(s8) = COPY $x
    %1:any(s8) = COPY $a
    %2:any(s8) = G_AND %0, %1
    RTS implicit %2
...
---
name: asl
legalized: true
regBankSelected: true
body: |
  bb.0.entry:
    ; 6502-LABEL: name: asl
    ; 6502: [[COPY:%[0-9]+]]:aimag8 = COPY $a
    ; 6502-NEXT: [[ASL:%[0-9]+]]:aimag8, [[ASL1:%[0-9]+]]:cc = ASL [[COPY]]
    ; 6502-NEXT: RTS implicit [[ASL]], implicit [[ASL1]]
    ;
    ; 65C02-LABEL: name: asl
    ; 65C02: [[COPY:%[0-9]+]]:aimag8 = COPY $a
    ; 65C02-NEXT: [[ASL:%[0-9]+]]:aimag8, [[ASL1:%[0-9]+]]:cc = ASL [[COPY]]
    ; 65C02-NEXT: RTS implicit [[ASL]], implicit [[ASL1]]
    %0:any(s8) = COPY $a
    %1:any(s1) = G_CONSTANT i1 0
    %2:any(s8), %3:any(s1) = G_SHLE %0, %1
    RTS implicit %2, implicit %3
...
---
name: anyext_16_8
legalized: true
regBankSelected: true
body: |
  bb.0.entry:
    ; 6502-LABEL: name: anyext_16_8
    ; 6502: [[COPY:%[0-9]+]]:anyi8 = COPY $a
    ; 6502-NEXT: [[DEF:%[0-9]+]]:imag16 = IMPLICIT_DEF
    ; 6502-NEXT: [[INSERT_SUBREG:%[0-9]+]]:imag16 = INSERT_SUBREG [[DEF]], [[COPY]], %subreg.sublo
    ; 6502-NEXT: RTS implicit [[INSERT_SUBREG]]
    ;
    ; 65C02-LABEL: name: anyext_16_8
    ; 65C02: [[COPY:%[0-9]+]]:anyi8 = COPY $a
    ; 65C02-NEXT: [[DEF:%[0-9]+]]:imag16 = IMPLICIT_DEF
    ; 65C02-NEXT: [[INSERT_SUBREG:%[0-9]+]]:imag16 = INSERT_SUBREG [[DEF]], [[COPY]], %subreg.sublo
    ; 65C02-NEXT: RTS implicit [[INSERT_SUBREG]]
    %0:any(s8) = COPY $a
    %1:any(s16) = G_ANYEXT %0
    RTS implicit %1
...
---
name: br
legalized: true
regBankSelected: true
body: |
  bb.0.entry:
    ; 6502-LABEL: name: br
    ; 6502: successors: %bb.0(0x80000000)
    ; 6502-NEXT: {{  $}}
    ; 6502-NEXT: JMP %bb.0
    ; 6502-NEXT: RTS
    ;
    ; 65C02-LABEL: name: br
    ; 65C02: successors: %bb.0(0x80000000)
    ; 65C02-NEXT: {{  $}}
    ; 65C02-NEXT: BRA %bb.0
    ; 65C02-NEXT: RTS
    G_BR %bb.0
    RTS
...
---
name: br_imm
legalized: true
regBankSelected: true
body: |
  bb.0.entry:
    ; 6502-LABEL: name: br_imm
    ; 6502: successors: %bb.0(0x80000000)
    ; 6502-NEXT: {{  $}}
    ; 6502-NEXT: [[COPY:%[0-9]+]]:anyi1 = COPY $c
    ; 6502-NEXT: GBR %bb.0, [[COPY]], 0, implicit-def $c
    ; 6502-NEXT: RTS
    ;
    ; 65C02-LABEL: name: br_imm
    ; 65C02: successors: %bb.0(0x80000000)
    ; 65C02-NEXT: {{  $}}
    ; 65C02-NEXT: [[COPY:%[0-9]+]]:anyi1 = COPY $c
    ; 65C02-NEXT: GBR %bb.0, [[COPY]], 0, implicit-def $c
    ; 65C02-NEXT: RTS
    %0:any(s1) = COPY $c
    G_BRCOND_IMM %0, %bb.0, 0
    RTS
...
---
name: cmpz_brn
legalized: true
regBankSelected: true
body: |
  bb.0.entry:
    ; 6502-LABEL: name: cmpz_brn
    ; 6502: successors: %bb.0(0x80000000)
    ; 6502-NEXT: {{  $}}
    ; 6502-NEXT: [[COPY:%[0-9]+]]:anyi8 = COPY $a
    ; 6502-NEXT: CmpBrZero %bb.0, undef $n, 1, [[COPY]], implicit-def $c
    ; 6502-NEXT: RTS
    ;
    ; 65C02-LABEL: name: cmpz_brn
    ; 65C02: successors: %bb.0(0x80000000)
    ; 65C02-NEXT: {{  $}}
    ; 65C02-NEXT: [[COPY:%[0-9]+]]:anyi8 = COPY $a
    ; 65C02-NEXT: CmpBrZero %bb.0, undef $n, 1, [[COPY]], implicit-def $c
    ; 65C02-NEXT: RTS
    %0:any(s8) = COPY $a
    %1:any(s8) = G_CONSTANT i8 0
    %2:any(s1) = G_CONSTANT i1 -1
    %3:any(s8), %4:any(s1), %5:any(s1), %6:any(s1), %7:any(s1) = G_SBC %0, %1, %2
    G_BRCOND_IMM %5, %bb.0, 1
    RTS
...
---
name: cmpz_brz
legalized: true
regBankSelected: true
body: |
  bb.0.entry:
    ; 6502-LABEL: name: cmpz_brz
    ; 6502: successors: %bb.0(0x80000000)
    ; 6502-NEXT: {{  $}}
    ; 6502-NEXT: [[COPY:%[0-9]+]]:anyi8 = COPY $a
    ; 6502-NEXT: CmpBrZero %bb.0, undef $z, 1, [[COPY]], implicit-def $c
    ; 6502-NEXT: RTS
    ;
    ; 65C02-LABEL: name: cmpz_brz
    ; 65C02: successors: %bb.0(0x80000000)
    ; 65C02-NEXT: {{  $}}
    ; 65C02-NEXT: [[COPY:%[0-9]+]]:anyi8 = COPY $a
    ; 65C02-NEXT: CmpBrZero %bb.0, undef $z, 1, [[COPY]], implicit-def $c
    ; 65C02-NEXT: RTS
    %0:any(s8) = COPY $a
    %1:any(s8) = G_CONSTANT i8 0
    %2:any(s1) = G_CONSTANT i1 -1
    %3:any(s8), %4:any(s1), %5:any(s1), %6:any(s1), %7:any(s1) = G_SBC %0, %1, %2
    G_BRCOND_IMM %7, %bb.0, 1
    RTS
...
---
name: cmpzmb_brz
legalized: true
regBankSelected: true
body: |
  bb.0.entry:
    ; 6502-LABEL: name: cmpzmb_brz
    ; 6502: successors: %bb.0(0x80000000)
    ; 6502-NEXT: {{  $}}
    ; 6502-NEXT: [[COPY:%[0-9]+]]:anyi8 = COPY $a
    ; 6502-NEXT: [[COPY1:%[0-9]+]]:anyi8 = COPY $x
    ; 6502-NEXT: [[COPY2:%[0-9]+]]:anyi8 = COPY $y
    ; 6502-NEXT: [[COPY3:%[0-9]+]]:anyi8 = COPY $rc2
    ; 6502-NEXT: CmpBrZeroMultiByte %bb.0, 1, [[COPY]], [[COPY1]], [[COPY2]], [[COPY3]], implicit-def $c
    ; 6502-NEXT: RTS
    ;
    ; 65C02-LABEL: name: cmpzmb_brz
    ; 65C02: successors: %bb.0(0x80000000)
    ; 65C02-NEXT: {{  $}}
    ; 65C02-NEXT: [[COPY:%[0-9]+]]:anyi8 = COPY $a
    ; 65C02-NEXT: [[COPY1:%[0-9]+]]:anyi8 = COPY $x
    ; 65C02-NEXT: [[COPY2:%[0-9]+]]:anyi8 = COPY $y
    ; 65C02-NEXT: [[COPY3:%[0-9]+]]:anyi8 = COPY $rc2
    ; 65C02-NEXT: CmpBrZeroMultiByte %bb.0, 1, [[COPY]], [[COPY1]], [[COPY2]], [[COPY3]], implicit-def $c
    ; 65C02-NEXT: RTS
    %0:any(s8) = COPY $a
    %1:any(s8) = COPY $x
    %2:any(s8) = COPY $y
    %3:any(s8) = COPY $rc2
    %4:any(s8) = G_CMPZ %0, %1, %2, %3
    G_BRCOND_IMM %4, %bb.0, 1
    RTS
...
---
name: cmpimm_brc
legalized: true
regBankSelected: true
body: |
  bb.0.entry:
    ; 6502-LABEL: name: cmpimm_brc
    ; 6502: successors: %bb.0(0x80000000)
    ; 6502-NEXT: {{  $}}
    ; 6502-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $a
    ; 6502-NEXT: [[CMPImm:%[0-9]+]]:cc = CMPImm [[COPY]], 42
    ; 6502-NEXT: GBR %bb.0, [[CMPImm]], 1, implicit-def $c
    ; 6502-NEXT: RTS
    ;
    ; 65C02-LABEL: name: cmpimm_brc
    ; 65C02: successors: %bb.0(0x80000000)
    ; 65C02-NEXT: {{  $}}
    ; 65C02-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $a
    ; 65C02-NEXT: [[CMPImm:%[0-9]+]]:cc = CMPImm [[COPY]], 42
    ; 65C02-NEXT: GBR %bb.0, [[CMPImm]], 1, implicit-def $c
    ; 65C02-NEXT: RTS
    %0:any(s8) = COPY $a
    %1:any(s8) = G_CONSTANT i8 42
    %2:any(s1) = G_CONSTANT i1 -1
    %3:any(s8), %4:any(s1), %5:any(s1), %6:any(s1), %7:any(s1) = G_SBC %0, %1, %2
    G_BRCOND_IMM %4, %bb.0, 1
    RTS
...
---
name: cmpimm_brn
legalized: true
regBankSelected: true
body: |
  bb.0.entry:
    ; 6502-LABEL: name: cmpimm_brn
    ; 6502: successors: %bb.0(0x80000000)
    ; 6502-NEXT: {{  $}}
    ; 6502-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $a
    ; 6502-NEXT: CmpBrImm %bb.0, undef $n, 1, [[COPY]], 42, implicit-def $c
    ; 6502-NEXT: RTS
    ;
    ; 65C02-LABEL: name: cmpimm_brn
    ; 65C02: successors: %bb.0(0x80000000)
    ; 65C02-NEXT: {{  $}}
    ; 65C02-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $a
    ; 65C02-NEXT: CmpBrImm %bb.0, undef $n, 1, [[COPY]], 42, implicit-def $c
    ; 65C02-NEXT: RTS
    %0:any(s8) = COPY $a
    %1:any(s8) = G_CONSTANT i8 42
    %2:any(s1) = G_CONSTANT i1 -1
    %3:any(s8), %4:any(s1), %5:any(s1), %6:any(s1), %7:any(s1) = G_SBC %0, %1, %2
    G_BRCOND_IMM %5, %bb.0, 1
    RTS
...
---
name: cmpimm_brz
legalized: true
regBankSelected: true
body: |
  bb.0.entry:
    ; 6502-LABEL: name: cmpimm_brz
    ; 6502: successors: %bb.0(0x80000000)
    ; 6502-NEXT: {{  $}}
    ; 6502-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $a
    ; 6502-NEXT: CmpBrImm %bb.0, undef $z, 1, [[COPY]], 42, implicit-def $c
    ; 6502-NEXT: RTS
    ;
    ; 65C02-LABEL: name: cmpimm_brz
    ; 65C02: successors: %bb.0(0x80000000)
    ; 65C02-NEXT: {{  $}}
    ; 65C02-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $a
    ; 65C02-NEXT: CmpBrImm %bb.0, undef $z, 1, [[COPY]], 42, implicit-def $c
    ; 65C02-NEXT: RTS
    %0:any(s8) = COPY $a
    %1:any(s8) = G_CONSTANT i8 42
    %2:any(s1) = G_CONSTANT i1 -1
    %3:any(s8), %4:any(s1), %5:any(s1), %6:any(s1), %7:any(s1) = G_SBC %0, %1, %2
    G_BRCOND_IMM %7, %bb.0, 1
    RTS
...
---
name: cmpimag8_brc
legalized: true
regBankSelected: true
body: |
  bb.0.entry:
    ; 6502-LABEL: name: cmpimag8_brc
    ; 6502: successors: %bb.0(0x80000000)
    ; 6502-NEXT: {{  $}}
    ; 6502-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $a
    ; 6502-NEXT: [[COPY1:%[0-9]+]]:imag8 = COPY $x
    ; 6502-NEXT: [[CMPImag8_:%[0-9]+]]:cc = CMPImag8 [[COPY]], [[COPY1]]
    ; 6502-NEXT: GBR %bb.0, [[CMPImag8_]], 1, implicit-def $c
    ; 6502-NEXT: RTS
    ;
    ; 65C02-LABEL: name: cmpimag8_brc
    ; 65C02: successors: %bb.0(0x80000000)
    ; 65C02-NEXT: {{  $}}
    ; 65C02-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $a
    ; 65C02-NEXT: [[COPY1:%[0-9]+]]:imag8 = COPY $x
    ; 65C02-NEXT: [[CMPImag8_:%[0-9]+]]:cc = CMPImag8 [[COPY]], [[COPY1]]
    ; 65C02-NEXT: GBR %bb.0, [[CMPImag8_]], 1, implicit-def $c
    ; 65C02-NEXT: RTS
    %0:any(s8) = COPY $a
    %1:any(s8) = COPY $x
    %2:any(s1) = G_CONSTANT i1 -1
    %3:any(s8), %4:any(s1), %5:any(s1), %6:any(s1), %7:any(s1) = G_SBC %0, %1, %2
    G_BRCOND_IMM %4, %bb.0, 1
    RTS
...
---
name: cmpimag8_brn
legalized: true
regBankSelected: true
body: |
  bb.0.entry:
    ; 6502-LABEL: name: cmpimag8_brn
    ; 6502: successors: %bb.0(0x80000000)
    ; 6502-NEXT: {{  $}}
    ; 6502-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $a
    ; 6502-NEXT: [[COPY1:%[0-9]+]]:imag8 = COPY $x
    ; 6502-NEXT: CmpBrImag8 %bb.0, undef $n, 1, [[COPY]], [[COPY1]], implicit-def $c
    ; 6502-NEXT: RTS
    ;
    ; 65C02-LABEL: name: cmpimag8_brn
    ; 65C02: successors: %bb.0(0x80000000)
    ; 65C02-NEXT: {{  $}}
    ; 65C02-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $a
    ; 65C02-NEXT: [[COPY1:%[0-9]+]]:imag8 = COPY $x
    ; 65C02-NEXT: CmpBrImag8 %bb.0, undef $n, 1, [[COPY]], [[COPY1]], implicit-def $c
    ; 65C02-NEXT: RTS
    %0:any(s8) = COPY $a
    %1:any(s8) = COPY $x
    %2:any(s1) = G_CONSTANT i1 -1
    %3:any(s8), %4:any(s1), %5:any(s1), %6:any(s1), %7:any(s1) = G_SBC %0, %1, %2
    G_BRCOND_IMM %5, %bb.0, 1
    RTS
...
---
name: cmpimag8_brz
legalized: true
regBankSelected: true
body: |
  bb.0.entry:
    ; 6502-LABEL: name: cmpimag8_brz
    ; 6502: successors: %bb.0(0x80000000)
    ; 6502-NEXT: {{  $}}
    ; 6502-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $a
    ; 6502-NEXT: [[COPY1:%[0-9]+]]:imag8 = COPY $x
    ; 6502-NEXT: CmpBrImag8 %bb.0, undef $z, 1, [[COPY]], [[COPY1]], implicit-def $c
    ; 6502-NEXT: RTS
    ;
    ; 65C02-LABEL: name: cmpimag8_brz
    ; 65C02: successors: %bb.0(0x80000000)
    ; 65C02-NEXT: {{  $}}
    ; 65C02-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $a
    ; 65C02-NEXT: [[COPY1:%[0-9]+]]:imag8 = COPY $x
    ; 65C02-NEXT: CmpBrImag8 %bb.0, undef $z, 1, [[COPY]], [[COPY1]], implicit-def $c
    ; 65C02-NEXT: RTS
    %0:any(s8) = COPY $a
    %1:any(s8) = COPY $x
    %2:any(s1) = G_CONSTANT i1 -1
    %3:any(s8), %4:any(s1), %5:any(s1), %6:any(s1), %7:any(s1) = G_SBC %0, %1, %2
    G_BRCOND_IMM %7, %bb.0, 1
    RTS
...
---
name: cmpabs_brc
legalized: true
regBankSelected: true
body: |
  bb.0.entry:
    ; 6502-LABEL: name: cmpabs_brc
    ; 6502: successors: %bb.0(0x80000000)
    ; 6502-NEXT: {{  $}}
    ; 6502-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $a
    ; 6502-NEXT: [[CMPAbs:%[0-9]+]]:cc = CMPAbs [[COPY]], i16 1234 :: (load (s8))
    ; 6502-NEXT: GBR %bb.0, [[CMPAbs]], 1, implicit-def $c
    ; 6502-NEXT: RTS
    ;
    ; 65C02-LABEL: name: cmpabs_brc
    ; 65C02: successors: %bb.0(0x80000000)
    ; 65C02-NEXT: {{  $}}
    ; 65C02-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $a
    ; 65C02-NEXT: [[CMPAbs:%[0-9]+]]:cc = CMPAbs [[COPY]], i16 1234 :: (load (s8))
    ; 65C02-NEXT: GBR %bb.0, [[CMPAbs]], 1, implicit-def $c
    ; 65C02-NEXT: RTS
    %0:any(s8) = COPY $a
    %1:any(s8) = G_LOAD_ABS i16 1234 :: (load (s8))
    %2:any(s1) = G_CONSTANT i1 -1
    %3:any(s8), %4:any(s1), %5:any(s1), %6:any(s1), %7:any(s1) = G_SBC %0, %1, %2
    G_BRCOND_IMM %4, %bb.0, 1
    RTS
...
---
name: cmpabs_brn
legalized: true
regBankSelected: true
body: |
  bb.0.entry:
    ; 6502-LABEL: name: cmpabs_brn
    ; 6502: successors: %bb.0(0x80000000)
    ; 6502-NEXT: {{  $}}
    ; 6502-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $a
    ; 6502-NEXT: CmpBrAbs %bb.0, undef $n, 1, [[COPY]], i16 1234, implicit-def $c :: (load (s8))
    ; 6502-NEXT: RTS
    ;
    ; 65C02-LABEL: name: cmpabs_brn
    ; 65C02: successors: %bb.0(0x80000000)
    ; 65C02-NEXT: {{  $}}
    ; 65C02-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $a
    ; 65C02-NEXT: CmpBrAbs %bb.0, undef $n, 1, [[COPY]], i16 1234, implicit-def $c :: (load (s8))
    ; 65C02-NEXT: RTS
    %0:any(s8) = COPY $a
    %1:any(s8) = G_LOAD_ABS i16 1234 :: (load (s8))
    %2:any(s1) = G_CONSTANT i1 -1
    %3:any(s8), %4:any(s1), %5:any(s1), %6:any(s1), %7:any(s1) = G_SBC %0, %1, %2
    G_BRCOND_IMM %5, %bb.0, 1
    RTS
...
---
name: cmpabs_brz
legalized: true
regBankSelected: true
body: |
  bb.0.entry:
    ; 6502-LABEL: name: cmpabs_brz
    ; 6502: successors: %bb.0(0x80000000)
    ; 6502-NEXT: {{  $}}
    ; 6502-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $a
    ; 6502-NEXT: CmpBrAbs %bb.0, undef $z, 1, [[COPY]], i16 1234, implicit-def $c :: (load (s8))
    ; 6502-NEXT: RTS
    ;
    ; 65C02-LABEL: name: cmpabs_brz
    ; 65C02: successors: %bb.0(0x80000000)
    ; 65C02-NEXT: {{  $}}
    ; 65C02-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $a
    ; 65C02-NEXT: CmpBrAbs %bb.0, undef $z, 1, [[COPY]], i16 1234, implicit-def $c :: (load (s8))
    ; 65C02-NEXT: RTS
    %0:any(s8) = COPY $a
    %1:any(s8) = G_LOAD_ABS i16 1234 :: (load (s8))
    %2:any(s1) = G_CONSTANT i1 -1
    %3:any(s8), %4:any(s1), %5:any(s1), %6:any(s1), %7:any(s1) = G_SBC %0, %1, %2
    G_BRCOND_IMM %7, %bb.0, 1
    RTS
...
---
name: cmpzpidx_brc
legalized: true
regBankSelected: true
body: |
  bb.0.entry:
    ; 6502-LABEL: name: cmpzpidx_brc
    ; 6502: successors: %bb.0(0x80000000)
    ; 6502-NEXT: {{  $}}
    ; 6502-NEXT: [[COPY:%[0-9]+]]:ac = COPY $a
    ; 6502-NEXT: [[COPY1:%[0-9]+]]:xc = COPY $x
    ; 6502-NEXT: [[CMPZpIdx:%[0-9]+]]:cc = CMPZpIdx [[COPY]], i8 123, [[COPY1]] :: (load (s8))
    ; 6502-NEXT: GBR %bb.0, [[CMPZpIdx]], 1, implicit-def $c
    ; 6502-NEXT: RTS
    ;
    ; 65C02-LABEL: name: cmpzpidx_brc
    ; 65C02: successors: %bb.0(0x80000000)
    ; 65C02-NEXT: {{  $}}
    ; 65C02-NEXT: [[COPY:%[0-9]+]]:ac = COPY $a
    ; 65C02-NEXT: [[COPY1:%[0-9]+]]:xc = COPY $x
    ; 65C02-NEXT: [[CMPZpIdx:%[0-9]+]]:cc = CMPZpIdx [[COPY]], i8 123, [[COPY1]] :: (load (s8))
    ; 65C02-NEXT: GBR %bb.0, [[CMPZpIdx]], 1, implicit-def $c
    ; 65C02-NEXT: RTS
    %0:any(s8) = COPY $a
    %1:any(s8) = COPY $x
    %2:any(s8) = G_LOAD_ZP_IDX i8 123, %1 :: (load (s8))
    %3:any(s1) = G_CONSTANT i1 -1
    %4:any(s8), %5:any(s1), %6:any(s1), %7:any(s1), %8:any(s1) = G_SBC %0, %2, %3
    G_BRCOND_IMM %5, %bb.0, 1
    RTS
...
---
name: cmpzpidx_brn
legalized: true
regBankSelected: true
body: |
  bb.0.entry:
    ; 6502-LABEL: name: cmpzpidx_brn
    ; 6502: successors: %bb.0(0x80000000)
    ; 6502-NEXT: {{  $}}
    ; 6502-NEXT: [[COPY:%[0-9]+]]:ac = COPY $a
    ; 6502-NEXT: [[COPY1:%[0-9]+]]:xc = COPY $x
    ; 6502-NEXT: CmpBrZpIdx %bb.0, undef $n, 1, [[COPY]], i8 123, [[COPY1]], implicit-def $c :: (load (s8))
    ; 6502-NEXT: RTS
    ;
    ; 65C02-LABEL: name: cmpzpidx_brn
    ; 65C02: successors: %bb.0(0x80000000)
    ; 65C02-NEXT: {{  $}}
    ; 65C02-NEXT: [[COPY:%[0-9]+]]:ac = COPY $a
    ; 65C02-NEXT: [[COPY1:%[0-9]+]]:xc = COPY $x
    ; 65C02-NEXT: CmpBrZpIdx %bb.0, undef $n, 1, [[COPY]], i8 123, [[COPY1]], implicit-def $c :: (load (s8))
    ; 65C02-NEXT: RTS
    %0:any(s8) = COPY $a
    %1:any(s8) = COPY $x
    %2:any(s8) = G_LOAD_ZP_IDX i8 123, %1 :: (load (s8))
    %3:any(s1) = G_CONSTANT i1 -1
    %4:any(s8), %5:any(s1), %6:any(s1), %7:any(s1), %8:any(s1) = G_SBC %0, %2, %3
    G_BRCOND_IMM %6, %bb.0, 1
    RTS
...
---
name: cmpzpidx_brz
legalized: true
regBankSelected: true
body: |
  bb.0.entry:
    ; 6502-LABEL: name: cmpzpidx_brz
    ; 6502: successors: %bb.0(0x80000000)
    ; 6502-NEXT: {{  $}}
    ; 6502-NEXT: [[COPY:%[0-9]+]]:ac = COPY $a
    ; 6502-NEXT: [[COPY1:%[0-9]+]]:xc = COPY $x
    ; 6502-NEXT: CmpBrZpIdx %bb.0, undef $z, 1, [[COPY]], i8 123, [[COPY1]], implicit-def $c :: (load (s8))
    ; 6502-NEXT: RTS
    ;
    ; 65C02-LABEL: name: cmpzpidx_brz
    ; 65C02: successors: %bb.0(0x80000000)
    ; 65C02-NEXT: {{  $}}
    ; 65C02-NEXT: [[COPY:%[0-9]+]]:ac = COPY $a
    ; 65C02-NEXT: [[COPY1:%[0-9]+]]:xc = COPY $x
    ; 65C02-NEXT: CmpBrZpIdx %bb.0, undef $z, 1, [[COPY]], i8 123, [[COPY1]], implicit-def $c :: (load (s8))
    ; 65C02-NEXT: RTS
    %0:any(s8) = COPY $a
    %1:any(s8) = COPY $x
    %2:any(s8) = G_LOAD_ZP_IDX i8 123, %1 :: (load (s8))
    %3:any(s1) = G_CONSTANT i1 -1
    %4:any(s8), %5:any(s1), %6:any(s1), %7:any(s1), %8:any(s1) = G_SBC %0, %2, %3
    G_BRCOND_IMM %8, %bb.0, 1
    RTS
...
---
name: cmpabsidx_brc
legalized: true
regBankSelected: true
body: |
  bb.0.entry:
    ; 6502-LABEL: name: cmpabsidx_brc
    ; 6502: successors: %bb.0(0x80000000)
    ; 6502-NEXT: {{  $}}
    ; 6502-NEXT: [[COPY:%[0-9]+]]:ac = COPY $a
    ; 6502-NEXT: [[COPY1:%[0-9]+]]:xy = COPY $x
    ; 6502-NEXT: [[CMPAbsIdx:%[0-9]+]]:cc = CMPAbsIdx [[COPY]], i16 1234, [[COPY1]] :: (load (s8))
    ; 6502-NEXT: GBR %bb.0, [[CMPAbsIdx]], 1, implicit-def $c
    ; 6502-NEXT: RTS
    ;
    ; 65C02-LABEL: name: cmpabsidx_brc
    ; 65C02: successors: %bb.0(0x80000000)
    ; 65C02-NEXT: {{  $}}
    ; 65C02-NEXT: [[COPY:%[0-9]+]]:ac = COPY $a
    ; 65C02-NEXT: [[COPY1:%[0-9]+]]:xy = COPY $x
    ; 65C02-NEXT: [[CMPAbsIdx:%[0-9]+]]:cc = CMPAbsIdx [[COPY]], i16 1234, [[COPY1]] :: (load (s8))
    ; 65C02-NEXT: GBR %bb.0, [[CMPAbsIdx]], 1, implicit-def $c
    ; 65C02-NEXT: RTS
    %0:any(s8) = COPY $a
    %1:any(s8) = COPY $x
    %2:any(s8) = G_LOAD_ABS_IDX i16 1234, %1 :: (load (s8))
    %3:any(s1) = G_CONSTANT i1 -1
    %4:any(s8), %5:any(s1), %6:any(s1), %7:any(s1), %8:any(s1) = G_SBC %0, %2, %3
    G_BRCOND_IMM %5, %bb.0, 1
    RTS
...
---
name: cmpabsidx_brn
legalized: true
regBankSelected: true
body: |
  bb.0.entry:
    ; 6502-LABEL: name: cmpabsidx_brn
    ; 6502: successors: %bb.0(0x80000000)
    ; 6502-NEXT: {{  $}}
    ; 6502-NEXT: [[COPY:%[0-9]+]]:ac = COPY $a
    ; 6502-NEXT: [[COPY1:%[0-9]+]]:xy = COPY $x
    ; 6502-NEXT: CmpBrAbsIdx %bb.0, undef $n, 1, [[COPY]], i16 1234, [[COPY1]], implicit-def $c :: (load (s8))
    ; 6502-NEXT: RTS
    ;
    ; 65C02-LABEL: name: cmpabsidx_brn
    ; 65C02: successors: %bb.0(0x80000000)
    ; 65C02-NEXT: {{  $}}
    ; 65C02-NEXT: [[COPY:%[0-9]+]]:ac = COPY $a
    ; 65C02-NEXT: [[COPY1:%[0-9]+]]:xy = COPY $x
    ; 65C02-NEXT: CmpBrAbsIdx %bb.0, undef $n, 1, [[COPY]], i16 1234, [[COPY1]], implicit-def $c :: (load (s8))
    ; 65C02-NEXT: RTS
    %0:any(s8) = COPY $a
    %1:any(s8) = COPY $x
    %2:any(s8) = G_LOAD_ABS_IDX i16 1234, %1 :: (load (s8))
    %3:any(s1) = G_CONSTANT i1 -1
    %4:any(s8), %5:any(s1), %6:any(s1), %7:any(s1), %8:any(s1) = G_SBC %0, %2, %3
    G_BRCOND_IMM %6, %bb.0, 1
    RTS
...
---
name: cmpabsidx_brz
legalized: true
regBankSelected: true
body: |
  bb.0.entry:
    ; 6502-LABEL: name: cmpabsidx_brz
    ; 6502: successors: %bb.0(0x80000000)
    ; 6502-NEXT: {{  $}}
    ; 6502-NEXT: [[COPY:%[0-9]+]]:ac = COPY $a
    ; 6502-NEXT: [[COPY1:%[0-9]+]]:xy = COPY $x
    ; 6502-NEXT: CmpBrAbsIdx %bb.0, undef $z, 1, [[COPY]], i16 1234, [[COPY1]], implicit-def $c :: (load (s8))
    ; 6502-NEXT: RTS
    ;
    ; 65C02-LABEL: name: cmpabsidx_brz
    ; 65C02: successors: %bb.0(0x80000000)
    ; 65C02-NEXT: {{  $}}
    ; 65C02-NEXT: [[COPY:%[0-9]+]]:ac = COPY $a
    ; 65C02-NEXT: [[COPY1:%[0-9]+]]:xy = COPY $x
    ; 65C02-NEXT: CmpBrAbsIdx %bb.0, undef $z, 1, [[COPY]], i16 1234, [[COPY1]], implicit-def $c :: (load (s8))
    ; 65C02-NEXT: RTS
    %0:any(s8) = COPY $a
    %1:any(s8) = COPY $x
    %2:any(s8) = G_LOAD_ABS_IDX i16 1234, %1 :: (load (s8))
    %3:any(s1) = G_CONSTANT i1 -1
    %4:any(s8), %5:any(s1), %6:any(s1), %7:any(s1), %8:any(s1) = G_SBC %0, %2, %3
    G_BRCOND_IMM %8, %bb.0, 1
    RTS
...
---
name: cmpindir_brc
legalized: true
regBankSelected: true
body: |
  bb.0.entry:
    ; 6502-LABEL: name: cmpindir_brc
    ; 6502: successors: %bb.0(0x80000000)
    ; 6502-NEXT: {{  $}}
    ; 6502-NEXT: [[COPY:%[0-9]+]]:ac = COPY $a
    ; 6502-NEXT: [[COPY1:%[0-9]+]]:imag16 = COPY $rs1
    ; 6502-NEXT: [[CMPIndir:%[0-9]+]]:cc = CMPIndir [[COPY]], [[COPY1]] :: (load (s8))
    ; 6502-NEXT: GBR %bb.0, [[CMPIndir]], 1, implicit-def $c
    ; 6502-NEXT: RTS
    ;
    ; 65C02-LABEL: name: cmpindir_brc
    ; 65C02: successors: %bb.0(0x80000000)
    ; 65C02-NEXT: {{  $}}
    ; 65C02-NEXT: [[COPY:%[0-9]+]]:ac = COPY $a
    ; 65C02-NEXT: [[COPY1:%[0-9]+]]:imag16 = COPY $rs1
    ; 65C02-NEXT: [[CMPIndir:%[0-9]+]]:cc = CMPIndir [[COPY]], [[COPY1]] :: (load (s8))
    ; 65C02-NEXT: GBR %bb.0, [[CMPIndir]], 1, implicit-def $c
    ; 65C02-NEXT: RTS
    %0:any(s8) = COPY $a
    %1:any(s16) = COPY $rs1
    %2:any(s8) = G_LOAD_INDIR %1 :: (load (s8))
    %3:any(s1) = G_CONSTANT i1 -1
    %4:any(s8), %5:any(s1), %6:any(s1), %7:any(s1), %8:any(s1) = G_SBC %0, %2, %3
    G_BRCOND_IMM %5, %bb.0, 1
    RTS
...
---
name: cmpindir_brn
legalized: true
regBankSelected: true
body: |
  bb.0.entry:
    ; 6502-LABEL: name: cmpindir_brn
    ; 6502: successors: %bb.0(0x80000000)
    ; 6502-NEXT: {{  $}}
    ; 6502-NEXT: [[COPY:%[0-9]+]]:ac = COPY $a
    ; 6502-NEXT: [[COPY1:%[0-9]+]]:imag16 = COPY $rs1
    ; 6502-NEXT: CmpBrIndir %bb.0, undef $n, 1, [[COPY]], [[COPY1]], implicit-def $c :: (load (s8))
    ; 6502-NEXT: RTS
    ;
    ; 65C02-LABEL: name: cmpindir_brn
    ; 65C02: successors: %bb.0(0x80000000)
    ; 65C02-NEXT: {{  $}}
    ; 65C02-NEXT: [[COPY:%[0-9]+]]:ac = COPY $a
    ; 65C02-NEXT: [[COPY1:%[0-9]+]]:imag16 = COPY $rs1
    ; 65C02-NEXT: CmpBrIndir %bb.0, undef $n, 1, [[COPY]], [[COPY1]], implicit-def $c :: (load (s8))
    ; 65C02-NEXT: RTS
    %0:any(s8) = COPY $a
    %1:any(s16) = COPY $rs1
    %2:any(s8) = G_LOAD_INDIR %1 :: (load (s8))
    %3:any(s1) = G_CONSTANT i1 -1
    %4:any(s8), %5:any(s1), %6:any(s1), %7:any(s1), %8:any(s1) = G_SBC %0, %2, %3
    G_BRCOND_IMM %6, %bb.0, 1
    RTS
...
---
name: cmpindir_brz
legalized: true
regBankSelected: true
body: |
  bb.0.entry:
    ; 6502-LABEL: name: cmpindir_brz
    ; 6502: successors: %bb.0(0x80000000)
    ; 6502-NEXT: {{  $}}
    ; 6502-NEXT: [[COPY:%[0-9]+]]:ac = COPY $a
    ; 6502-NEXT: [[COPY1:%[0-9]+]]:imag16 = COPY $rs1
    ; 6502-NEXT: CmpBrIndir %bb.0, undef $z, 1, [[COPY]], [[COPY1]], implicit-def $c :: (load (s8))
    ; 6502-NEXT: RTS
    ;
    ; 65C02-LABEL: name: cmpindir_brz
    ; 65C02: successors: %bb.0(0x80000000)
    ; 65C02-NEXT: {{  $}}
    ; 65C02-NEXT: [[COPY:%[0-9]+]]:ac = COPY $a
    ; 65C02-NEXT: [[COPY1:%[0-9]+]]:imag16 = COPY $rs1
    ; 65C02-NEXT: CmpBrIndir %bb.0, undef $z, 1, [[COPY]], [[COPY1]], implicit-def $c :: (load (s8))
    ; 65C02-NEXT: RTS
    %0:any(s8) = COPY $a
    %1:any(s16) = COPY $rs1
    %2:any(s8) = G_LOAD_INDIR %1 :: (load (s8))
    %3:any(s1) = G_CONSTANT i1 -1
    %4:any(s8), %5:any(s1), %6:any(s1), %7:any(s1), %8:any(s1) = G_SBC %0, %2, %3
    G_BRCOND_IMM %8, %bb.0, 1
    RTS
...
---
name: cmpindiridx_brc
legalized: true
regBankSelected: true
body: |
  bb.0.entry:
    ; 6502-LABEL: name: cmpindiridx_brc
    ; 6502: successors: %bb.0(0x80000000)
    ; 6502-NEXT: {{  $}}
    ; 6502-NEXT: [[COPY:%[0-9]+]]:ac = COPY $a
    ; 6502-NEXT: [[COPY1:%[0-9]+]]:imag16 = COPY $rs1
    ; 6502-NEXT: [[COPY2:%[0-9]+]]:yc = COPY $y
    ; 6502-NEXT: [[CMPIndirIdx:%[0-9]+]]:cc = CMPIndirIdx [[COPY]], [[COPY1]], [[COPY2]] :: (load (s8))
    ; 6502-NEXT: GBR %bb.0, [[CMPIndirIdx]], 1, implicit-def $c
    ; 6502-NEXT: RTS
    ;
    ; 65C02-LABEL: name: cmpindiridx_brc
    ; 65C02: successors: %bb.0(0x80000000)
    ; 65C02-NEXT: {{  $}}
    ; 65C02-NEXT: [[COPY:%[0-9]+]]:ac = COPY $a
    ; 65C02-NEXT: [[COPY1:%[0-9]+]]:imag16 = COPY $rs1
    ; 65C02-NEXT: [[COPY2:%[0-9]+]]:yc = COPY $y
    ; 65C02-NEXT: [[CMPIndirIdx:%[0-9]+]]:cc = CMPIndirIdx [[COPY]], [[COPY1]], [[COPY2]] :: (load (s8))
    ; 65C02-NEXT: GBR %bb.0, [[CMPIndirIdx]], 1, implicit-def $c
    ; 65C02-NEXT: RTS
    %0:any(s8) = COPY $a
    %1:any(s16) = COPY $rs1
    %2:any(s8) = COPY $y
    %3:any(s8) = G_LOAD_INDIR_IDX %1, %2 :: (load (s8))
    %4:any(s1) = G_CONSTANT i1 -1
    %5:any(s8), %6:any(s1), %7:any(s1), %8:any(s1), %9:any(s1) = G_SBC %0, %3, %4
    G_BRCOND_IMM %6, %bb.0, 1
    RTS
...
---
name: cmpindiridx_brn
legalized: true
regBankSelected: true
body: |
  bb.0.entry:
    ; 6502-LABEL: name: cmpindiridx_brn
    ; 6502: successors: %bb.0(0x80000000)
    ; 6502-NEXT: {{  $}}
    ; 6502-NEXT: [[COPY:%[0-9]+]]:ac = COPY $a
    ; 6502-NEXT: [[COPY1:%[0-9]+]]:imag16 = COPY $rs1
    ; 6502-NEXT: [[COPY2:%[0-9]+]]:yc = COPY $y
    ; 6502-NEXT: CmpBrIndirIdx %bb.0, undef $n, 1, [[COPY]], [[COPY1]], [[COPY2]], implicit-def $c :: (load (s8))
    ; 6502-NEXT: RTS
    ;
    ; 65C02-LABEL: name: cmpindiridx_brn
    ; 65C02: successors: %bb.0(0x80000000)
    ; 65C02-NEXT: {{  $}}
    ; 65C02-NEXT: [[COPY:%[0-9]+]]:ac = COPY $a
    ; 65C02-NEXT: [[COPY1:%[0-9]+]]:imag16 = COPY $rs1
    ; 65C02-NEXT: [[COPY2:%[0-9]+]]:yc = COPY $y
    ; 65C02-NEXT: CmpBrIndirIdx %bb.0, undef $n, 1, [[COPY]], [[COPY1]], [[COPY2]], implicit-def $c :: (load (s8))
    ; 65C02-NEXT: RTS
    %0:any(s8) = COPY $a
    %1:any(s16) = COPY $rs1
    %2:any(s8) = COPY $y
    %3:any(s8) = G_LOAD_INDIR_IDX %1, %2 :: (load (s8))
    %4:any(s1) = G_CONSTANT i1 -1
    %5:any(s8), %6:any(s1), %7:any(s1), %8:any(s1), %9:any(s1) = G_SBC %0, %3, %4
    G_BRCOND_IMM %7, %bb.0, 1
    RTS
...
---
name: cmpindiridx_brz
legalized: true
regBankSelected: true
body: |
  bb.0.entry:
    ; 6502-LABEL: name: cmpindiridx_brz
    ; 6502: successors: %bb.0(0x80000000)
    ; 6502-NEXT: {{  $}}
    ; 6502-NEXT: [[COPY:%[0-9]+]]:ac = COPY $a
    ; 6502-NEXT: [[COPY1:%[0-9]+]]:imag16 = COPY $rs1
    ; 6502-NEXT: [[COPY2:%[0-9]+]]:yc = COPY $y
    ; 6502-NEXT: CmpBrIndirIdx %bb.0, undef $z, 1, [[COPY]], [[COPY1]], [[COPY2]], implicit-def $c :: (load (s8))
    ; 6502-NEXT: RTS
    ;
    ; 65C02-LABEL: name: cmpindiridx_brz
    ; 65C02: successors: %bb.0(0x80000000)
    ; 65C02-NEXT: {{  $}}
    ; 65C02-NEXT: [[COPY:%[0-9]+]]:ac = COPY $a
    ; 65C02-NEXT: [[COPY1:%[0-9]+]]:imag16 = COPY $rs1
    ; 65C02-NEXT: [[COPY2:%[0-9]+]]:yc = COPY $y
    ; 65C02-NEXT: CmpBrIndirIdx %bb.0, undef $z, 1, [[COPY]], [[COPY1]], [[COPY2]], implicit-def $c :: (load (s8))
    ; 65C02-NEXT: RTS
    %0:any(s8) = COPY $a
    %1:any(s16) = COPY $rs1
    %2:any(s8) = COPY $y
    %3:any(s8) = G_LOAD_INDIR_IDX %1, %2 :: (load (s8))
    %4:any(s1) = G_CONSTANT i1 -1
    %5:any(s8), %6:any(s1), %7:any(s1), %8:any(s1), %9:any(s1) = G_SBC %0, %3, %4
    G_BRCOND_IMM %9, %bb.0, 1
    RTS
...
---
name: copy
legalized: true
regBankSelected: true
body: |
  bb.0.entry:
    liveins: $a
    ; 6502-LABEL: name: copy
    ; 6502: liveins: $a
    ; 6502-NEXT: {{  $}}
    ; 6502-NEXT: [[COPY:%[0-9]+]]:anyi8 = COPY $a
    ; 6502-NEXT: RTS implicit [[COPY]]
    ;
    ; 65C02-LABEL: name: copy
    ; 65C02: liveins: $a
    ; 65C02-NEXT: {{  $}}
    ; 65C02-NEXT: [[COPY:%[0-9]+]]:anyi8 = COPY $a
    ; 65C02-NEXT: RTS implicit [[COPY]]
    %0:any(s8) = COPY $a
    RTS implicit %0
...
---
name: eor
legalized: true
regBankSelected: true
body: |
  bb.0.entry:
    ; 6502-LABEL: name: eor
    ; 6502: [[COPY:%[0-9]+]]:ac = COPY $x
    ; 6502-NEXT: [[COPY1:%[0-9]+]]:imag8 = COPY $a
    ; 6502-NEXT: [[EORImag8_:%[0-9]+]]:ac = EORImag8 [[COPY]], [[COPY1]]
    ; 6502-NEXT: RTS implicit [[EORImag8_]]
    ;
    ; 65C02-LABEL: name: eor
    ; 65C02: [[COPY:%[0-9]+]]:ac = COPY $x
    ; 65C02-NEXT: [[COPY1:%[0-9]+]]:imag8 = COPY $a
    ; 65C02-NEXT: [[EORImag8_:%[0-9]+]]:ac = EORImag8 [[COPY]], [[COPY1]]
    ; 65C02-NEXT: RTS implicit [[EORImag8_]]
    %0:any(s8) = COPY $x
    %1:any(s8) = COPY $a
    %2:any(s8) = G_XOR %0, %1
    RTS implicit %2
...
---
name: implicit_def
legalized: true
regBankSelected: true
body: |
  bb.0.entry:
    ; 6502-LABEL: name: implicit_def
    ; 6502: [[DEF:%[0-9]+]]:anyi1 = IMPLICIT_DEF
    ; 6502-NEXT: RTS implicit [[DEF]]
    ;
    ; 65C02-LABEL: name: implicit_def
    ; 65C02: [[DEF:%[0-9]+]]:anyi1 = IMPLICIT_DEF
    ; 65C02-NEXT: RTS implicit [[DEF]]
    %0:any(s1) = G_IMPLICIT_DEF
    RTS implicit %0
...
---
name: ldimm1
legalized: true
regBankSelected: true
body: |
  bb.0.entry:
    ; 6502-LABEL: name: ldimm1
    ; 6502: [[LDImm1_:%[0-9]+]]:cv_gpr_lsb = LDImm1 -1
    ; 6502-NEXT: RTS implicit [[LDImm1_]]
    ;
    ; 65C02-LABEL: name: ldimm1
    ; 65C02: [[LDImm1_:%[0-9]+]]:cv_gpr_lsb = LDImm1 -1
    ; 65C02-NEXT: RTS implicit [[LDImm1_]]
    %0:any(s1) = G_CONSTANT i1 true
    RTS implicit %0
...
---
name: ldimm
legalized: true
regBankSelected: true
body: |
  bb.0.entry:
    ; 6502-LABEL: name: ldimm
    ; 6502: [[LDImm:%[0-9]+]]:gpr = LDImm 42
    ; 6502-NEXT: RTS implicit [[LDImm]]
    ;
    ; 65C02-LABEL: name: ldimm
    ; 65C02: [[LDImm:%[0-9]+]]:gpr = LDImm 42
    ; 65C02-NEXT: RTS implicit [[LDImm]]
    %0:any(s8) = G_CONSTANT i8 42
    RTS implicit %0
...
---
name: ldimm16
legalized: true
regBankSelected: true
body: |
  bb.0.entry:
    ; 6502-LABEL: name: ldimm16
    ; 6502: %0:imag16, early-clobber %1:gpr = LDImm16 1234
    ; 6502-NEXT: RTS implicit %0
    ;
    ; 65C02-LABEL: name: ldimm16
    ; 65C02: %0:imag16, early-clobber %1:gpr = LDImm16 1234
    ; 65C02-NEXT: RTS implicit %0
    %0:any(p0) = G_CONSTANT i16 1234
    RTS implicit %0
...
---
name: load_absolute_const
legalized: true
regBankSelected: true
body: |
  bb.0.entry:
    ; 6502-LABEL: name: load_absolute_const
    ; 6502: [[LDAbs:%[0-9]+]]:gpr = LDAbs i16 1234 :: (load (s8))
    ; 6502-NEXT: RTS implicit [[LDAbs]]
    ;
    ; 65C02-LABEL: name: load_absolute_const
    ; 65C02: [[LDAbs:%[0-9]+]]:gpr = LDAbs i16 1234 :: (load (s8))
    ; 65C02-NEXT: RTS implicit [[LDAbs]]
    %0:any(s8) = G_LOAD_ABS i16 1234 :: (load (s8))
    RTS implicit %0
...
---
name: store
legalized: true
regBankSelected: true
body: |
  bb.0.entry:
    ; 6502-LABEL: name: store
    ; 6502: [[COPY:%[0-9]+]]:gpr = COPY $a
    ; 6502-NEXT: STAbs [[COPY]], i16 1234 :: (store (s8))
    ; 6502-NEXT: RTS
    ;
    ; 65C02-LABEL: name: store
    ; 65C02: [[COPY:%[0-9]+]]:gpr = COPY $a
    ; 65C02-NEXT: STAbs [[COPY]], i16 1234 :: (store (s8))
    ; 65C02-NEXT: RTS
    %0:any(s8) = COPY $a
    G_STORE_ABS %0, i16 1234 :: (store (s8))
    RTS
...
---
name: load_zeropage_indexed
legalized: true
regBankSelected: true
body: |
  bb.0.entry:
    ; 6502-LABEL: name: load_zeropage_indexed
    ; 6502: [[COPY:%[0-9]+]]:xc = COPY $x
    ; 6502-NEXT: [[LDAZpIdx:%[0-9]+]]:ac = LDAZpIdx i8 123, [[COPY]] :: (load (s8))
    ; 6502-NEXT: RTS implicit [[LDAZpIdx]]
    ;
    ; 65C02-LABEL: name: load_zeropage_indexed
    ; 65C02: [[COPY:%[0-9]+]]:xc = COPY $x
    ; 65C02-NEXT: [[LDAZpIdx:%[0-9]+]]:ac = LDAZpIdx i8 123, [[COPY]] :: (load (s8))
    ; 65C02-NEXT: RTS implicit [[LDAZpIdx]]
    %0:any(s8) = COPY $x
    %1:any(s8) = G_LOAD_ZP_IDX i8 123, %0 :: (load (s8))
    RTS implicit %1
...
---
name: load_absolute_indexed
legalized: true
regBankSelected: true
body: |
  bb.0.entry:
    ; 6502-LABEL: name: load_absolute_indexed
    ; 6502: [[COPY:%[0-9]+]]:xy = COPY $x
    ; 6502-NEXT: [[LDAbsIdx:%[0-9]+]]:gpr = LDAbsIdx i16 1234, [[COPY]] :: (load (s8))
    ; 6502-NEXT: RTS implicit [[LDAbsIdx]]
    ;
    ; 65C02-LABEL: name: load_absolute_indexed
    ; 65C02: [[COPY:%[0-9]+]]:xy = COPY $x
    ; 65C02-NEXT: [[LDAbsIdx:%[0-9]+]]:gpr = LDAbsIdx i16 1234, [[COPY]] :: (load (s8))
    ; 65C02-NEXT: RTS implicit [[LDAbsIdx]]
    %0:any(s8) = COPY $x
    %1:any(s8) = G_LOAD_ABS_IDX i16 1234, %0 :: (load (s8))
    RTS implicit %1
...
---
name: load_indirect_indexed
legalized: true
regBankSelected: true
body: |
  bb.0.entry:
    ; 6502-LABEL: name: load_indirect_indexed
    ; 6502: [[COPY:%[0-9]+]]:imag16 = COPY $rs1
    ; 6502-NEXT: [[LDImm:%[0-9]+]]:yc = LDImm -1
    ; 6502-NEXT: [[LDIndirIdx:%[0-9]+]]:ac = LDIndirIdx [[COPY]], [[LDImm]] :: (load (s8))
    ; 6502-NEXT: RTS implicit [[LDIndirIdx]]
    ;
    ; 65C02-LABEL: name: load_indirect_indexed
    ; 65C02: [[COPY:%[0-9]+]]:imag16 = COPY $rs1
    ; 65C02-NEXT: [[LDImm:%[0-9]+]]:yc = LDImm -1
    ; 65C02-NEXT: [[LDIndirIdx:%[0-9]+]]:ac = LDIndirIdx [[COPY]], [[LDImm]] :: (load (s8))
    ; 65C02-NEXT: RTS implicit [[LDIndirIdx]]
    %0:any(p0) = COPY $rs1
    %1:any(s8) = G_CONSTANT i8 -1
    %2:any(s8) = G_LOAD_INDIR_IDX %0, %1 :: (load (s8))
    RTS implicit %2
...
---
name: lsr
legalized: true
regBankSelected: true
body: |
  bb.0.entry:
    ; 6502-LABEL: name: lsr
    ; 6502: [[COPY:%[0-9]+]]:aimag8 = COPY $a
    ; 6502-NEXT: [[LSR:%[0-9]+]]:aimag8, [[LSR1:%[0-9]+]]:cc = LSR [[COPY]]
    ; 6502-NEXT: RTS implicit [[LSR]], implicit [[LSR1]]
    ;
    ; 65C02-LABEL: name: lsr
    ; 65C02: [[COPY:%[0-9]+]]:aimag8 = COPY $a
    ; 65C02-NEXT: [[LSR:%[0-9]+]]:aimag8, [[LSR1:%[0-9]+]]:cc = LSR [[COPY]]
    ; 65C02-NEXT: RTS implicit [[LSR]], implicit [[LSR1]]
    %0:any(s8) = COPY $a
    %1:any(s1) = G_CONSTANT i1 0
    %2:any(s8), %3:any(s1) = G_LSHRE %0, %1
    RTS implicit %2, implicit %3
...
---
name: ora
legalized: true
regBankSelected: true
body: |
  bb.0.entry:
    ; 6502-LABEL: name: ora
    ; 6502: [[COPY:%[0-9]+]]:ac = COPY $x
    ; 6502-NEXT: [[COPY1:%[0-9]+]]:imag8 = COPY $a
    ; 6502-NEXT: [[ORAImag8_:%[0-9]+]]:ac = ORAImag8 [[COPY]], [[COPY1]]
    ; 6502-NEXT: RTS implicit [[ORAImag8_]]
    ;
    ; 65C02-LABEL: name: ora
    ; 65C02: [[COPY:%[0-9]+]]:ac = COPY $x
    ; 65C02-NEXT: [[COPY1:%[0-9]+]]:imag8 = COPY $a
    ; 65C02-NEXT: [[ORAImag8_:%[0-9]+]]:ac = ORAImag8 [[COPY]], [[COPY1]]
    ; 65C02-NEXT: RTS implicit [[ORAImag8_]]
    %0:any(s8) = COPY $x
    %1:any(s8) = COPY $a
    %2:any(s8) = G_OR %0, %1
    RTS implicit %2
...
---
name: rol
legalized: true
regBankSelected: true
body: |
  bb.0.entry:
    ; 6502-LABEL: name: rol
    ; 6502: [[COPY:%[0-9]+]]:aimag8 = COPY $a
    ; 6502-NEXT: [[COPY1:%[0-9]+]]:cc = COPY $v
    ; 6502-NEXT: [[ROL:%[0-9]+]]:aimag8, [[ROL1:%[0-9]+]]:cc = ROL [[COPY]], [[COPY1]]
    ; 6502-NEXT: RTS implicit [[ROL]], implicit [[ROL1]]
    ;
    ; 65C02-LABEL: name: rol
    ; 65C02: [[COPY:%[0-9]+]]:aimag8 = COPY $a
    ; 65C02-NEXT: [[COPY1:%[0-9]+]]:cc = COPY $v
    ; 65C02-NEXT: [[ROL:%[0-9]+]]:aimag8, [[ROL1:%[0-9]+]]:cc = ROL [[COPY]], [[COPY1]]
    ; 65C02-NEXT: RTS implicit [[ROL]], implicit [[ROL1]]
    %0:any(s8) = COPY $a
    %1:any(s1) = COPY $v
    %2:any(s8), %3:any(s1) = G_SHLE %0, %1
    RTS implicit %2, implicit %3
...
---
name: ror
legalized: true
regBankSelected: true
body: |
  bb.0.entry:
    ; 6502-LABEL: name: ror
    ; 6502: [[COPY:%[0-9]+]]:aimag8 = COPY $a
    ; 6502-NEXT: [[COPY1:%[0-9]+]]:cc = COPY $v
    ; 6502-NEXT: [[ROR:%[0-9]+]]:aimag8, [[ROR1:%[0-9]+]]:cc = ROR [[COPY]], [[COPY1]]
    ; 6502-NEXT: RTS implicit [[ROR]], implicit [[ROR1]]
    ;
    ; 65C02-LABEL: name: ror
    ; 65C02: [[COPY:%[0-9]+]]:aimag8 = COPY $a
    ; 65C02-NEXT: [[COPY1:%[0-9]+]]:cc = COPY $v
    ; 65C02-NEXT: [[ROR:%[0-9]+]]:aimag8, [[ROR1:%[0-9]+]]:cc = ROR [[COPY]], [[COPY1]]
    ; 65C02-NEXT: RTS implicit [[ROR]], implicit [[ROR1]]
    %0:any(s8) = COPY $a
    %1:any(s1) = COPY $v
    %2:any(s8), %3:any(s1) = G_LSHRE %0, %1
    RTS implicit %2, implicit %3
...
---
name: trunc_8_1
legalized: true
regBankSelected: true
body: |
  bb.0.entry:
    ; 6502-LABEL: name: trunc_8_1
    ; 6502: [[COPY:%[0-9]+]]:ac = COPY $a
    ; 6502-NEXT: [[ANDImm:%[0-9]+]]:ac = ANDImm [[COPY]], 1
    ; 6502-NEXT: [[COPY1:%[0-9]+]]:gpr_lsb = COPY [[ANDImm]].sublsb
    ; 6502-NEXT: RTS implicit [[COPY1]]
    ;
    ; 65C02-LABEL: name: trunc_8_1
    ; 65C02: [[COPY:%[0-9]+]]:ac = COPY $a
    ; 65C02-NEXT: [[ANDImm:%[0-9]+]]:ac = ANDImm [[COPY]], 1
    ; 65C02-NEXT: [[COPY1:%[0-9]+]]:gpr_lsb = COPY [[ANDImm]].sublsb
    ; 65C02-NEXT: RTS implicit [[COPY1]]
    %0:any(s8) = COPY $a
    %1:any(s1) = G_TRUNC %0
    RTS implicit %1
...
---
name: trunc_16_8
legalized: true
regBankSelected: true
body: |
  bb.0.entry:
    ; 6502-LABEL: name: trunc_16_8
    ; 6502: [[COPY:%[0-9]+]]:imag16 = COPY $rs1
    ; 6502-NEXT: [[COPY1:%[0-9]+]]:imag8 = COPY [[COPY]].sublo
    ; 6502-NEXT: RTS implicit [[COPY1]]
    ;
    ; 65C02-LABEL: name: trunc_16_8
    ; 65C02: [[COPY:%[0-9]+]]:imag16 = COPY $rs1
    ; 65C02-NEXT: [[COPY1:%[0-9]+]]:imag8 = COPY [[COPY]].sublo
    ; 65C02-NEXT: RTS implicit [[COPY1]]
    %0:any(s16) = COPY $rs1
    %1:any(s8) = G_TRUNC %0
    RTS implicit %1
...
---
name: trunc_16_1
legalized: true
regBankSelected: true
body: |
  bb.0.entry:
    ; 6502-LABEL: name: trunc_16_1
    ; 6502: [[COPY:%[0-9]+]]:imag16 = COPY $rs1
    ; 6502-NEXT: [[COPY1:%[0-9]+]]:imag8 = COPY [[COPY]].sublo
    ; 6502-NEXT: [[COPY2:%[0-9]+]]:ac = COPY [[COPY1]]
    ; 6502-NEXT: [[ANDImm:%[0-9]+]]:ac = ANDImm [[COPY2]], 1
    ; 6502-NEXT: [[COPY3:%[0-9]+]]:gpr_lsb = COPY [[ANDImm]].sublsb
    ; 6502-NEXT: RTS implicit [[COPY3]]
    ;
    ; 65C02-LABEL: name: trunc_16_1
    ; 65C02: [[COPY:%[0-9]+]]:imag16 = COPY $rs1
    ; 65C02-NEXT: [[COPY1:%[0-9]+]]:imag8 = COPY [[COPY]].sublo
    ; 65C02-NEXT: [[COPY2:%[0-9]+]]:ac = COPY [[COPY1]]
    ; 65C02-NEXT: [[ANDImm:%[0-9]+]]:ac = ANDImm [[COPY2]], 1
    ; 65C02-NEXT: [[COPY3:%[0-9]+]]:gpr_lsb = COPY [[ANDImm]].sublsb
    ; 65C02-NEXT: RTS implicit [[COPY3]]
    %0:any(s16) = COPY $rs1
    %1:any(s1) = G_TRUNC %0
    RTS implicit %1
...
---
name: uadde_imm
legalized: true
regBankSelected: true
body: |
  bb.0.entry:
    ; 6502-LABEL: name: uadde_imm
    ; 6502: [[COPY:%[0-9]+]]:ac = COPY $x
    ; 6502-NEXT: [[COPY1:%[0-9]+]]:cc = COPY $v
    ; 6502-NEXT: [[ADCImm:%[0-9]+]]:ac, [[ADCImm1:%[0-9]+]]:cc, [[ADCImm2:%[0-9]+]]:vc = ADCImm [[COPY]], 42, [[COPY1]]
    ; 6502-NEXT: RTS implicit [[ADCImm]], implicit [[ADCImm1]]
    ;
    ; 65C02-LABEL: name: uadde_imm
    ; 65C02: [[COPY:%[0-9]+]]:ac = COPY $x
    ; 65C02-NEXT: [[COPY1:%[0-9]+]]:cc = COPY $v
    ; 65C02-NEXT: [[ADCImm:%[0-9]+]]:ac, [[ADCImm1:%[0-9]+]]:cc, [[ADCImm2:%[0-9]+]]:vc = ADCImm [[COPY]], 42, [[COPY1]]
    ; 65C02-NEXT: RTS implicit [[ADCImm]], implicit [[ADCImm1]]
    %0:any(s8) = COPY $x
    %1:any(s8) = G_CONSTANT i8 42
    %2:any(s1) = COPY $v
    %3:any(s8), %4:any(s1) = G_UADDE %0:any(s8), %1:any(s8), %2:any(s1)
    RTS implicit %3, implicit %4
...
---
name: uadde_abs
legalized: true
regBankSelected: true
body: |
  bb.0.entry:
    ; 6502-LABEL: name: uadde_abs
    ; 6502: [[COPY:%[0-9]+]]:ac = COPY $x
    ; 6502-NEXT: [[COPY1:%[0-9]+]]:cc = COPY $v
    ; 6502-NEXT: [[ADCAbs:%[0-9]+]]:ac, [[ADCAbs1:%[0-9]+]]:cc, [[ADCAbs2:%[0-9]+]]:vc = ADCAbs [[COPY]], i16 1234, [[COPY1]]
    ; 6502-NEXT: RTS implicit [[ADCAbs]], implicit [[ADCAbs1]]
    ;
    ; 65C02-LABEL: name: uadde_abs
    ; 65C02: [[COPY:%[0-9]+]]:ac = COPY $x
    ; 65C02-NEXT: [[COPY1:%[0-9]+]]:cc = COPY $v
    ; 65C02-NEXT: [[ADCAbs:%[0-9]+]]:ac, [[ADCAbs1:%[0-9]+]]:cc, [[ADCAbs2:%[0-9]+]]:vc = ADCAbs [[COPY]], i16 1234, [[COPY1]]
    ; 65C02-NEXT: RTS implicit [[ADCAbs]], implicit [[ADCAbs1]]
    %0:any(s8) = COPY $x
    %1:any(s8) = G_LOAD_ABS i16 1234 :: (load (s8))
    %2:any(s1) = COPY $v
    %3:any(s8), %4:any(s1) = G_UADDE %0:any(s8), %1:any(s8), %2:any(s1)
    RTS implicit %3, implicit %4
...
---
name: uadde_abs_commute
legalized: true
regBankSelected: true
body: |
  bb.0.entry:
    ; 6502-LABEL: name: uadde_abs_commute
    ; 6502: [[COPY:%[0-9]+]]:ac = COPY $x
    ; 6502-NEXT: [[COPY1:%[0-9]+]]:cc = COPY $v
    ; 6502-NEXT: [[ADCAbs:%[0-9]+]]:ac, [[ADCAbs1:%[0-9]+]]:cc, [[ADCAbs2:%[0-9]+]]:vc = ADCAbs [[COPY]], i16 1234, [[COPY1]]
    ; 6502-NEXT: RTS implicit [[ADCAbs]], implicit [[ADCAbs1]]
    ;
    ; 65C02-LABEL: name: uadde_abs_commute
    ; 65C02: [[COPY:%[0-9]+]]:ac = COPY $x
    ; 65C02-NEXT: [[COPY1:%[0-9]+]]:cc = COPY $v
    ; 65C02-NEXT: [[ADCAbs:%[0-9]+]]:ac, [[ADCAbs1:%[0-9]+]]:cc, [[ADCAbs2:%[0-9]+]]:vc = ADCAbs [[COPY]], i16 1234, [[COPY1]]
    ; 65C02-NEXT: RTS implicit [[ADCAbs]], implicit [[ADCAbs1]]
    %0:any(s8) = COPY $x
    %1:any(s8) = G_LOAD_ABS i16 1234 :: (load (s8))
    %2:any(s1) = COPY $v
    %3:any(s8), %4:any(s1) = G_UADDE %1:any(s8), %0:any(s8), %2:any(s1)
    RTS implicit %3, implicit %4
...
---
name: uadde_idx
legalized: true
regBankSelected: true
body: |
  bb.0.entry:
    ; 6502-LABEL: name: uadde_idx
    ; 6502: [[COPY:%[0-9]+]]:ac = COPY $x
    ; 6502-NEXT: [[COPY1:%[0-9]+]]:cc = COPY $v
    ; 6502-NEXT: [[COPY2:%[0-9]+]]:xy = COPY [[COPY]]
    ; 6502-NEXT: [[ADCAbsIdx:%[0-9]+]]:ac, [[ADCAbsIdx1:%[0-9]+]]:cc, [[ADCAbsIdx2:%[0-9]+]]:vc = ADCAbsIdx [[COPY]], i16 1234, [[COPY2]], [[COPY1]]
    ; 6502-NEXT: RTS implicit [[ADCAbsIdx]], implicit [[ADCAbsIdx1]]
    ;
    ; 65C02-LABEL: name: uadde_idx
    ; 65C02: [[COPY:%[0-9]+]]:ac = COPY $x
    ; 65C02-NEXT: [[COPY1:%[0-9]+]]:cc = COPY $v
    ; 65C02-NEXT: [[COPY2:%[0-9]+]]:xy = COPY [[COPY]]
    ; 65C02-NEXT: [[ADCAbsIdx:%[0-9]+]]:ac, [[ADCAbsIdx1:%[0-9]+]]:cc, [[ADCAbsIdx2:%[0-9]+]]:vc = ADCAbsIdx [[COPY]], i16 1234, [[COPY2]], [[COPY1]]
    ; 65C02-NEXT: RTS implicit [[ADCAbsIdx]], implicit [[ADCAbsIdx1]]
    %0:any(s8) = COPY $x
    %1:any(s8) = G_LOAD_ABS_IDX i16 1234, %0 :: (load (s8))
    %2:any(s1) = COPY $v
    %3:any(s8), %4:any(s1) = G_UADDE %0:any(s8), %1:any(s8), %2:any(s1)
    RTS implicit %3, implicit %4
...
---
name: uadde_indiridx
legalized: true
regBankSelected: true
body: |
  bb.0.entry:
    ; 6502-LABEL: name: uadde_indiridx
    ; 6502: [[COPY:%[0-9]+]]:imag16 = COPY $rs1
    ; 6502-NEXT: [[COPY1:%[0-9]+]]:ac = COPY $x
    ; 6502-NEXT: [[COPY2:%[0-9]+]]:cc = COPY $v
    ; 6502-NEXT: [[COPY3:%[0-9]+]]:yc = COPY [[COPY1]]
    ; 6502-NEXT: [[ADCIndirIdx:%[0-9]+]]:ac, [[ADCIndirIdx1:%[0-9]+]]:cc, [[ADCIndirIdx2:%[0-9]+]]:vc = ADCIndirIdx [[COPY1]], [[COPY]], [[COPY3]], [[COPY2]]
    ; 6502-NEXT: RTS implicit [[ADCIndirIdx]], implicit [[ADCIndirIdx1]]
    ;
    ; 65C02-LABEL: name: uadde_indiridx
    ; 65C02: [[COPY:%[0-9]+]]:imag16 = COPY $rs1
    ; 65C02-NEXT: [[COPY1:%[0-9]+]]:ac = COPY $x
    ; 65C02-NEXT: [[COPY2:%[0-9]+]]:cc = COPY $v
    ; 65C02-NEXT: [[COPY3:%[0-9]+]]:yc = COPY [[COPY1]]
    ; 65C02-NEXT: [[ADCIndirIdx:%[0-9]+]]:ac, [[ADCIndirIdx1:%[0-9]+]]:cc, [[ADCIndirIdx2:%[0-9]+]]:vc = ADCIndirIdx [[COPY1]], [[COPY]], [[COPY3]], [[COPY2]]
    ; 65C02-NEXT: RTS implicit [[ADCIndirIdx]], implicit [[ADCIndirIdx1]]
    %0:any(s16) = COPY $rs1
    %1:any(s8) = COPY $x
    %2:any(s8) = G_LOAD_INDIR_IDX %0, %1 :: (load (s8))
    %3:any(s1) = COPY $v
    %4:any(s8), %5:any(s1) = G_UADDE %1:any(s8), %2:any(s8), %3:any(s1)
    RTS implicit %4, implicit %5
...
---
name: uadde
legalized: true
regBankSelected: true
body: |
  bb.0.entry:
    ; 6502-LABEL: name: uadde
    ; 6502: [[COPY:%[0-9]+]]:ac = COPY $x
    ; 6502-NEXT: [[COPY1:%[0-9]+]]:imag8 = COPY $a
    ; 6502-NEXT: [[COPY2:%[0-9]+]]:cc = COPY $v
    ; 6502-NEXT: [[ADCImag8_:%[0-9]+]]:ac, [[ADCImag8_1:%[0-9]+]]:cc, [[ADCImag8_2:%[0-9]+]]:vc = ADCImag8 [[COPY]], [[COPY1]], [[COPY2]]
    ; 6502-NEXT: RTS implicit [[ADCImag8_]], implicit [[ADCImag8_1]]
    ;
    ; 65C02-LABEL: name: uadde
    ; 65C02: [[COPY:%[0-9]+]]:ac = COPY $x
    ; 65C02-NEXT: [[COPY1:%[0-9]+]]:imag8 = COPY $a
    ; 65C02-NEXT: [[COPY2:%[0-9]+]]:cc = COPY $v
    ; 65C02-NEXT: [[ADCImag8_:%[0-9]+]]:ac, [[ADCImag8_1:%[0-9]+]]:cc, [[ADCImag8_2:%[0-9]+]]:vc = ADCImag8 [[COPY]], [[COPY1]], [[COPY2]]
    ; 65C02-NEXT: RTS implicit [[ADCImag8_]], implicit [[ADCImag8_1]]
    %0:any(s8) = COPY $x
    %1:any(s8) = COPY $a
    %2:any(s1) = COPY $v
    %3:any(s8), %4:any(s1) = G_UADDE %0:any(s8), %1:any(s8), %2:any(s1)
    RTS implicit %3, implicit %4
...
---
name: sadde_imm
legalized: true
regBankSelected: true
body: |
  bb.0.entry:
    ; 6502-LABEL: name: sadde_imm
    ; 6502: [[COPY:%[0-9]+]]:ac = COPY $x
    ; 6502-NEXT: [[COPY1:%[0-9]+]]:cc = COPY $v
    ; 6502-NEXT: [[ADCImm:%[0-9]+]]:ac, [[ADCImm1:%[0-9]+]]:cc, [[ADCImm2:%[0-9]+]]:vc = ADCImm [[COPY]], 42, [[COPY1]]
    ; 6502-NEXT: RTS implicit [[ADCImm]], implicit [[ADCImm2]]
    ;
    ; 65C02-LABEL: name: sadde_imm
    ; 65C02: [[COPY:%[0-9]+]]:ac = COPY $x
    ; 65C02-NEXT: [[COPY1:%[0-9]+]]:cc = COPY $v
    ; 65C02-NEXT: [[ADCImm:%[0-9]+]]:ac, [[ADCImm1:%[0-9]+]]:cc, [[ADCImm2:%[0-9]+]]:vc = ADCImm [[COPY]], 42, [[COPY1]]
    ; 65C02-NEXT: RTS implicit [[ADCImm]], implicit [[ADCImm2]]
    %0:any(s8) = COPY $x
    %1:any(s8) = G_CONSTANT i8 42
    %2:any(s1) = COPY $v
    %3:any(s8), %4:any(s1) = G_SADDE %0:any(s8), %1:any(s8), %2:any(s1)
    RTS implicit %3, implicit %4
...
---
name: sadde
legalized: true
regBankSelected: true
body: |
  bb.0.entry:
    ; 6502-LABEL: name: sadde
    ; 6502: [[COPY:%[0-9]+]]:ac = COPY $x
    ; 6502-NEXT: [[COPY1:%[0-9]+]]:imag8 = COPY $a
    ; 6502-NEXT: [[COPY2:%[0-9]+]]:cc = COPY $v
    ; 6502-NEXT: [[ADCImag8_:%[0-9]+]]:ac, [[ADCImag8_1:%[0-9]+]]:cc, [[ADCImag8_2:%[0-9]+]]:vc = ADCImag8 [[COPY]], [[COPY1]], [[COPY2]]
    ; 6502-NEXT: RTS implicit [[ADCImag8_]], implicit [[ADCImag8_2]]
    ;
    ; 65C02-LABEL: name: sadde
    ; 65C02: [[COPY:%[0-9]+]]:ac = COPY $x
    ; 65C02-NEXT: [[COPY1:%[0-9]+]]:imag8 = COPY $a
    ; 65C02-NEXT: [[COPY2:%[0-9]+]]:cc = COPY $v
    ; 65C02-NEXT: [[ADCImag8_:%[0-9]+]]:ac, [[ADCImag8_1:%[0-9]+]]:cc, [[ADCImag8_2:%[0-9]+]]:vc = ADCImag8 [[COPY]], [[COPY1]], [[COPY2]]
    ; 65C02-NEXT: RTS implicit [[ADCImag8_]], implicit [[ADCImag8_2]]
    %0:any(s8) = COPY $x
    %1:any(s8) = COPY $a
    %2:any(s1) = COPY $v
    %3:any(s8), %4:any(s1) = G_SADDE %0:any(s8), %1:any(s8), %2:any(s1)
    RTS implicit %3, implicit %4
...
---
name: inc_mb
legalized: true
regBankSelected: true
body: |
  bb.0.entry:
    ; 6502-LABEL: name: inc_mb
    ; 6502: [[COPY:%[0-9]+]]:anyi8 = COPY $a
    ; 6502-NEXT: [[COPY1:%[0-9]+]]:anyi8 = COPY $x
    ; 6502-NEXT: [[COPY2:%[0-9]+]]:anyi8 = COPY $y
    ; 6502-NEXT: [[COPY3:%[0-9]+]]:anyi8 = COPY $rc2
    ; 6502-NEXT: [[IncMB:%[0-9]+]]:anyi8, [[IncMB1:%[0-9]+]]:anyi8, [[IncMB2:%[0-9]+]]:anyi8, [[IncMB3:%[0-9]+]]:anyi8 = IncMB [[COPY]](tied-def 0), [[COPY1]](tied-def 1), [[COPY2]](tied-def 2), [[COPY3]](tied-def 3), implicit-def $c, implicit-def $v
    ; 6502-NEXT: RTS implicit [[IncMB]], implicit [[IncMB1]], implicit [[IncMB2]], implicit [[IncMB3]]
    ;
    ; 65C02-LABEL: name: inc_mb
    ; 65C02: [[COPY:%[0-9]+]]:anyi8 = COPY $a
    ; 65C02-NEXT: [[COPY1:%[0-9]+]]:anyi8 = COPY $x
    ; 65C02-NEXT: [[COPY2:%[0-9]+]]:anyi8 = COPY $y
    ; 65C02-NEXT: [[COPY3:%[0-9]+]]:anyi8 = COPY $rc2
    ; 65C02-NEXT: [[IncMB:%[0-9]+]]:anyi8, [[IncMB1:%[0-9]+]]:anyi8, [[IncMB2:%[0-9]+]]:anyi8, [[IncMB3:%[0-9]+]]:anyi8 = IncMB [[COPY]](tied-def 0), [[COPY1]](tied-def 1), [[COPY2]](tied-def 2), [[COPY3]](tied-def 3), implicit-def $c, implicit-def $v
    ; 65C02-NEXT: RTS implicit [[IncMB]], implicit [[IncMB1]], implicit [[IncMB2]], implicit [[IncMB3]]
    %0:any(s8) = COPY $a
    %1:any(s8) = COPY $x
    %2:any(s8) = COPY $y
    %3:any(s8) = COPY $rc2
    %4:any(s8), %5:any(s8), %6:any(s8), %7:any(s8) = G_INC %0, %1, %2, %3
    RTS implicit %4, implicit %5, implicit %6, implicit %7
...
---
name: dec_mb
legalized: true
regBankSelected: true
body: |
  bb.0.entry:
    ; 6502-LABEL: name: dec_mb
    ; 6502: [[COPY:%[0-9]+]]:anyi8 = COPY $a
    ; 6502-NEXT: [[COPY1:%[0-9]+]]:anyi8 = COPY $x
    ; 6502-NEXT: [[COPY2:%[0-9]+]]:anyi8 = COPY $y
    ; 6502-NEXT: [[COPY3:%[0-9]+]]:anyi8 = COPY $rc2
    ; 6502-NEXT: early-clobber %8:gpr, %4:anyi8, %5:anyi8, %6:anyi8, %7:anyi8 = DecMB [[COPY]](tied-def 1), [[COPY1]](tied-def 2), [[COPY2]](tied-def 3), [[COPY3]](tied-def 4), implicit-def $c, implicit-def $v
    ; 6502-NEXT: RTS implicit %4, implicit %5, implicit %6, implicit %7
    ;
    ; 65C02-LABEL: name: dec_mb
    ; 65C02: [[COPY:%[0-9]+]]:anyi8 = COPY $a
    ; 65C02-NEXT: [[COPY1:%[0-9]+]]:anyi8 = COPY $x
    ; 65C02-NEXT: [[COPY2:%[0-9]+]]:anyi8 = COPY $y
    ; 65C02-NEXT: [[COPY3:%[0-9]+]]:anyi8 = COPY $rc2
    ; 65C02-NEXT: early-clobber %8:gpr, %4:anyi8, %5:anyi8, %6:anyi8, %7:anyi8 = DecMB [[COPY]](tied-def 1), [[COPY1]](tied-def 2), [[COPY2]](tied-def 3), [[COPY3]](tied-def 4), implicit-def $c, implicit-def $v
    ; 65C02-NEXT: RTS implicit %4, implicit %5, implicit %6, implicit %7
    %0:any(s8) = COPY $a
    %1:any(s8) = COPY $x
    %2:any(s8) = COPY $y
    %3:any(s8) = COPY $rc2
    %4:any(s8), %5:any(s8), %6:any(s8), %7:any(s8) = G_DEC %0, %1, %2, %3
    RTS implicit %4, implicit %5, implicit %6, implicit %7
...
---
name: inc_abs_mb
legalized: true
regBankSelected: true
body: |
  bb.0.entry:
    ; 6502-LABEL: name: inc_abs_mb
    ; 6502: [[COPY:%[0-9]+]]:anyi8 = COPY $a
    ; 6502-NEXT: [[COPY1:%[0-9]+]]:anyi8 = COPY $y
    ; 6502-NEXT: [[COPY2:%[0-9]+]]:anyi8 = COPY $x
    ; 6502-NEXT: [[IncMB:%[0-9]+]]:anyi8, [[IncMB1:%[0-9]+]]:anyi8, [[IncMB2:%[0-9]+]]:anyi8 = IncMB [[COPY]](tied-def 0), i16 1234, [[COPY1]](tied-def 1), [[COPY2]](tied-def 2), implicit-def $c, implicit-def $v
    ; 6502-NEXT: RTS implicit [[IncMB]], implicit [[IncMB1]], implicit [[IncMB2]]
    ;
    ; 65C02-LABEL: name: inc_abs_mb
    ; 65C02: [[COPY:%[0-9]+]]:anyi8 = COPY $a
    ; 65C02-NEXT: [[COPY1:%[0-9]+]]:anyi8 = COPY $y
    ; 65C02-NEXT: [[COPY2:%[0-9]+]]:anyi8 = COPY $x
    ; 65C02-NEXT: [[IncMB:%[0-9]+]]:anyi8, [[IncMB1:%[0-9]+]]:anyi8, [[IncMB2:%[0-9]+]]:anyi8 = IncMB [[COPY]](tied-def 0), i16 1234, [[COPY1]](tied-def 1), [[COPY2]](tied-def 2), implicit-def $c, implicit-def $v
    ; 65C02-NEXT: RTS implicit [[IncMB]], implicit [[IncMB1]], implicit [[IncMB2]]
    %0:any(s8) = COPY $a
    %1:any(s8) = G_LOAD_ABS i16 1234 :: (load (s8))
    %2:any(s8) = COPY $y
    %3:any(s8) = COPY $x
    %4:any(s8), %5:any(s8), %6:any(s8), %7:any(s8) = G_INC %0, %1, %2, %3
    G_STORE_ABS %5, i16 1234 :: (store (s8))
    RTS implicit %4, implicit %6, implicit %7
...
---
name: dec_abs_mb
legalized: true
regBankSelected: true
body: |
  bb.0.entry:
    ; 6502-LABEL: name: dec_abs_mb
    ; 6502: [[COPY:%[0-9]+]]:anyi8 = COPY $a
    ; 6502-NEXT: [[COPY1:%[0-9]+]]:anyi8 = COPY $y
    ; 6502-NEXT: [[COPY2:%[0-9]+]]:anyi8 = COPY $x
    ; 6502-NEXT: early-clobber %8:gpr, %4:anyi8, %6:anyi8, %7:anyi8 = DecMB [[COPY]](tied-def 1), i16 1234, [[COPY1]](tied-def 2), [[COPY2]](tied-def 3), implicit-def $c, implicit-def $v
    ; 6502-NEXT: RTS implicit %4, implicit %6, implicit %7
    ;
    ; 65C02-LABEL: name: dec_abs_mb
    ; 65C02: [[COPY:%[0-9]+]]:anyi8 = COPY $a
    ; 65C02-NEXT: [[COPY1:%[0-9]+]]:anyi8 = COPY $y
    ; 65C02-NEXT: [[COPY2:%[0-9]+]]:anyi8 = COPY $x
    ; 65C02-NEXT: early-clobber %8:gpr, %4:anyi8, %6:anyi8, %7:anyi8 = DecMB [[COPY]](tied-def 1), i16 1234, [[COPY1]](tied-def 2), [[COPY2]](tied-def 3), implicit-def $c, implicit-def $v
    ; 65C02-NEXT: RTS implicit %4, implicit %6, implicit %7
    %0:any(s8) = COPY $a
    %1:any(s8) = G_LOAD_ABS i16 1234 :: (load (s8))
    %2:any(s8) = COPY $y
    %3:any(s8) = COPY $x
    %4:any(s8), %5:any(s8), %6:any(s8), %7:any(s8) = G_DEC %0, %1, %2, %3
    G_STORE_ABS %5, i16 1234 :: (store (s8))
    RTS implicit %4, implicit %6, implicit %7
...
---
name: inc_ptr
legalized: true
regBankSelected: true
body: |
  bb.0.entry:
    ; 6502-LABEL: name: inc_ptr
    ; 6502: [[COPY:%[0-9]+]]:imag16 = COPY $rs1
    ; 6502-NEXT: [[IncPtr:%[0-9]+]]:imag16 = IncPtr [[COPY]], implicit-def $c, implicit-def $v
    ; 6502-NEXT: RTS implicit [[IncPtr]]
    ;
    ; 65C02-LABEL: name: inc_ptr
    ; 65C02: [[COPY:%[0-9]+]]:imag16 = COPY $rs1
    ; 65C02-NEXT: [[IncPtr:%[0-9]+]]:imag16 = IncPtr [[COPY]], implicit-def $c, implicit-def $v
    ; 65C02-NEXT: RTS implicit [[IncPtr]]
    %0:any(p0) = COPY $rs1
    %1:any(p0) = G_INC %0
    RTS implicit %1
...
---
name: dec_ptr
legalized: true
regBankSelected: true
body: |
  bb.0.entry:
    ; 6502-LABEL: name: dec_ptr
    ; 6502: [[COPY:%[0-9]+]]:imag16 = COPY $rs1
    ; 6502-NEXT: early-clobber %2:gpr, %1:imag16 = DecPtr [[COPY]], implicit-def $c, implicit-def $v
    ; 6502-NEXT: RTS implicit %1
    ;
    ; 65C02-LABEL: name: dec_ptr
    ; 65C02: [[COPY:%[0-9]+]]:imag16 = COPY $rs1
    ; 65C02-NEXT: early-clobber %2:gpr, %1:imag16 = DecPtr [[COPY]], implicit-def $c, implicit-def $v
    ; 65C02-NEXT: RTS implicit %1
    %0:any(p0) = COPY $rs1
    %1:any(p0) = G_DEC %0
    RTS implicit %1
...
---
name: sbc_imm_c
legalized: true
regBankSelected: true
body: |
  bb.0.entry:
    ; 6502-LABEL: name: sbc_imm_c
    ; 6502: [[COPY:%[0-9]+]]:ac = COPY $x
    ; 6502-NEXT: [[COPY1:%[0-9]+]]:cc = COPY $v
    ; 6502-NEXT: [[SBCImm:%[0-9]+]]:ac, [[SBCImm1:%[0-9]+]]:cc, [[SBCImm2:%[0-9]+]]:vc = SBCImm [[COPY]], 42, [[COPY1]]
    ; 6502-NEXT: RTS implicit [[SBCImm]], implicit [[SBCImm1]]
    ;
    ; 65C02-LABEL: name: sbc_imm_c
    ; 65C02: [[COPY:%[0-9]+]]:ac = COPY $x
    ; 65C02-NEXT: [[COPY1:%[0-9]+]]:cc = COPY $v
    ; 65C02-NEXT: [[SBCImm:%[0-9]+]]:ac, [[SBCImm1:%[0-9]+]]:cc, [[SBCImm2:%[0-9]+]]:vc = SBCImm [[COPY]], 42, [[COPY1]]
    ; 65C02-NEXT: RTS implicit [[SBCImm]], implicit [[SBCImm1]]
    %0:any(s8) = COPY $x
    %1:any(s8) = G_CONSTANT i8 42
    %2:any(s1) = COPY $v
    %3:any(s8), %4:any(s1), %5:any(s1), %6:any(s1), %7:any(s1) = G_SBC %0:any(s8), %1:any(s8), %2:any(s1)
    RTS implicit %3, implicit %4
...
---
name: sbc_c
legalized: true
regBankSelected: true
body: |
  bb.0.entry:
    ; 6502-LABEL: name: sbc_c
    ; 6502: [[COPY:%[0-9]+]]:ac = COPY $x
    ; 6502-NEXT: [[COPY1:%[0-9]+]]:imag8 = COPY $a
    ; 6502-NEXT: [[COPY2:%[0-9]+]]:cc = COPY $v
    ; 6502-NEXT: [[SBCImag8_:%[0-9]+]]:ac, [[SBCImag8_1:%[0-9]+]]:cc, [[SBCImag8_2:%[0-9]+]]:vc = SBCImag8 [[COPY]], [[COPY1]], [[COPY2]]
    ; 6502-NEXT: RTS implicit [[SBCImag8_]], implicit [[SBCImag8_1]]
    ;
    ; 65C02-LABEL: name: sbc_c
    ; 65C02: [[COPY:%[0-9]+]]:ac = COPY $x
    ; 65C02-NEXT: [[COPY1:%[0-9]+]]:imag8 = COPY $a
    ; 65C02-NEXT: [[COPY2:%[0-9]+]]:cc = COPY $v
    ; 65C02-NEXT: [[SBCImag8_:%[0-9]+]]:ac, [[SBCImag8_1:%[0-9]+]]:cc, [[SBCImag8_2:%[0-9]+]]:vc = SBCImag8 [[COPY]], [[COPY1]], [[COPY2]]
    ; 65C02-NEXT: RTS implicit [[SBCImag8_]], implicit [[SBCImag8_1]]
    %0:any(s8) = COPY $x
    %1:any(s8) = COPY $a
    %2:any(s1) = COPY $v
    %3:any(s8), %4:any(s1), %5:any(s1), %6:any(s1), %7:any(s1) = G_SBC %0:any(s8), %1:any(s8), %2:any(s1)
    RTS implicit %3, implicit %4
...
---
name: sbc_imm_v
legalized: true
regBankSelected: true
body: |
  bb.0.entry:
    ; 6502-LABEL: name: sbc_imm_v
    ; 6502: [[COPY:%[0-9]+]]:ac = COPY $x
    ; 6502-NEXT: [[COPY1:%[0-9]+]]:cc = COPY $v
    ; 6502-NEXT: [[SBCImm:%[0-9]+]]:ac, [[SBCImm1:%[0-9]+]]:cc, [[SBCImm2:%[0-9]+]]:vc = SBCImm [[COPY]], 42, [[COPY1]]
    ; 6502-NEXT: RTS implicit [[SBCImm]], implicit [[SBCImm2]]
    ;
    ; 65C02-LABEL: name: sbc_imm_v
    ; 65C02: [[COPY:%[0-9]+]]:ac = COPY $x
    ; 65C02-NEXT: [[COPY1:%[0-9]+]]:cc = COPY $v
    ; 65C02-NEXT: [[SBCImm:%[0-9]+]]:ac, [[SBCImm1:%[0-9]+]]:cc, [[SBCImm2:%[0-9]+]]:vc = SBCImm [[COPY]], 42, [[COPY1]]
    ; 65C02-NEXT: RTS implicit [[SBCImm]], implicit [[SBCImm2]]
    %0:any(s8) = COPY $x
    %1:any(s8) = G_CONSTANT i8 42
    %2:any(s1) = COPY $v
    %3:any(s8), %4:any(s1), %5:any(s1), %6:any(s1), %7:any(s1) = G_SBC %0:any(s8), %1:any(s8), %2:any(s1)
    RTS implicit %3, implicit %6
...
---
name: sbc_v
legalized: true
regBankSelected: true
body: |
  bb.0.entry:
    ; 6502-LABEL: name: sbc_v
    ; 6502: [[COPY:%[0-9]+]]:ac = COPY $x
    ; 6502-NEXT: [[COPY1:%[0-9]+]]:imag8 = COPY $a
    ; 6502-NEXT: [[COPY2:%[0-9]+]]:cc = COPY $v
    ; 6502-NEXT: [[SBCImag8_:%[0-9]+]]:ac, [[SBCImag8_1:%[0-9]+]]:cc, [[SBCImag8_2:%[0-9]+]]:vc = SBCImag8 [[COPY]], [[COPY1]], [[COPY2]]
    ; 6502-NEXT: RTS implicit [[SBCImag8_]], implicit [[SBCImag8_2]]
    ;
    ; 65C02-LABEL: name: sbc_v
    ; 65C02: [[COPY:%[0-9]+]]:ac = COPY $x
    ; 65C02-NEXT: [[COPY1:%[0-9]+]]:imag8 = COPY $a
    ; 65C02-NEXT: [[COPY2:%[0-9]+]]:cc = COPY $v
    ; 65C02-NEXT: [[SBCImag8_:%[0-9]+]]:ac, [[SBCImag8_1:%[0-9]+]]:cc, [[SBCImag8_2:%[0-9]+]]:vc = SBCImag8 [[COPY]], [[COPY1]], [[COPY2]]
    ; 65C02-NEXT: RTS implicit [[SBCImag8_]], implicit [[SBCImag8_2]]
    %0:any(s8) = COPY $x
    %1:any(s8) = COPY $a
    %2:any(s1) = COPY $v
    %3:any(s8), %4:any(s1), %5:any(s1), %6:any(s1), %7:any(s1) = G_SBC %0:any(s8), %1:any(s8), %2:any(s1)
    RTS implicit %3, implicit %6
...
---
name: merge_constants_to_ptr
legalized: true
regBankSelected: true
body: |
  bb.0.entry:
    ; 6502-LABEL: name: merge_constants_to_ptr
    ; 6502: %2:imag16, early-clobber %4:gpr = LDImm16 8716
    ; 6502-NEXT: RTS implicit %2
    ;
    ; 65C02-LABEL: name: merge_constants_to_ptr
    ; 65C02: %2:imag16, early-clobber %4:gpr = LDImm16 8716
    ; 65C02-NEXT: RTS implicit %2
    %0:any(s8) = G_CONSTANT i8 12
    %1:any(s8) = G_CONSTANT i8 34
    %2:any(s16) = G_MERGE_VALUES %0, %1
    %3:any(p0) = G_INTTOPTR %2
    RTS implicit %3
...
---
name: unmerge
legalized: true
regBankSelected: true
body: |
  bb.0.entry:
    ; 6502-LABEL: name: unmerge
    ; 6502: [[COPY:%[0-9]+]]:imag16 = COPY $rs1
    ; 6502-NEXT: [[COPY1:%[0-9]+]]:anyi8 = COPY [[COPY]].sublo
    ; 6502-NEXT: [[COPY2:%[0-9]+]]:anyi8 = COPY [[COPY]].subhi
    ; 6502-NEXT: RTS implicit [[COPY1]], implicit [[COPY2]]
    ;
    ; 65C02-LABEL: name: unmerge
    ; 65C02: [[COPY:%[0-9]+]]:imag16 = COPY $rs1
    ; 65C02-NEXT: [[COPY1:%[0-9]+]]:anyi8 = COPY [[COPY]].sublo
    ; 65C02-NEXT: [[COPY2:%[0-9]+]]:anyi8 = COPY [[COPY]].subhi
    ; 65C02-NEXT: RTS implicit [[COPY1]], implicit [[COPY2]]
    %0:any(s16) = COPY $rs1
    %1:any(s8), %2:any(s8) = G_UNMERGE_VALUES %0
    RTS implicit %1, implicit %2
...
