# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -mtriple=mos -run-pass=instruction-select -verify-machineinstrs -o - %s | FileCheck %s
---
name: and
legalized: true
regBankSelected: true
body: |
  bb.0.entry:
    ; CHECK-LABEL: name: and
    ; CHECK: [[COPY:%[0-9]+]]:ac = COPY $x
    ; CHECK: [[COPY1:%[0-9]+]]:imag8 = COPY $a
    ; CHECK: [[ANDImag8_:%[0-9]+]]:ac = ANDImag8 [[COPY]], [[COPY1]], implicit-def $nz
    ; CHECK: RTS implicit [[ANDImag8_]]
    %0:any(s8) = COPY $x
    %1:any(s8) = COPY $a
    %2:any(s8) = G_AND %0, %1
    RTS implicit %2
...
---
name: asl
legalized: true
regBankSelected: true
body: |
  bb.0.entry:
    ; CHECK-LABEL: name: asl
    ; CHECK: [[COPY:%[0-9]+]]:aimag8 = COPY $a
    ; CHECK: [[ASL:%[0-9]+]]:aimag8, [[ASL1:%[0-9]+]]:cc = ASL [[COPY]], implicit-def $nz
    ; CHECK: RTS implicit [[ASL]], implicit [[ASL1]]
    %0:any(s8) = COPY $a
    %1:any(s1) = G_CONSTANT i1 0
    %2:any(s8), %3:any(s1) = G_SHLE %0, %1
    RTS implicit %2, implicit %3
...
---
name: anyext_8_1
legalized: true
regBankSelected: true
body: |
  bb.0.entry:
    ; CHECK-LABEL: name: anyext_8_1
    ; CHECK: [[COPY:%[0-9]+]]:anyi1 = COPY $c
    ; CHECK: [[DEF:%[0-9]+]]:anyi8 = IMPLICIT_DEF
    ; CHECK: [[INSERT_SUBREG:%[0-9]+]]:anyi8 = INSERT_SUBREG [[DEF]], [[COPY]], %subreg.sublsb
    ; CHECK: RTS implicit [[INSERT_SUBREG]]
    %0:any(s1) = COPY $c
    %1:any(s8) = G_ANYEXT %0
    RTS implicit %1
...
---
name: anyext_16_8
legalized: true
regBankSelected: true
body: |
  bb.0.entry:
    ; CHECK-LABEL: name: anyext_16_8
    ; CHECK: [[COPY:%[0-9]+]]:anyi8 = COPY $a
    ; CHECK: [[DEF:%[0-9]+]]:imag16 = IMPLICIT_DEF
    ; CHECK: [[INSERT_SUBREG:%[0-9]+]]:imag16 = INSERT_SUBREG [[DEF]], [[COPY]], %subreg.sublo
    ; CHECK: RTS implicit [[INSERT_SUBREG]]
    %0:any(s8) = COPY $a
    %1:any(s16) = G_ANYEXT %0
    RTS implicit %1
...
---
name: anyext_16_1
legalized: true
regBankSelected: true
body: |
  bb.0.entry:
    ; CHECK-LABEL: name: anyext_16_1
    ; CHECK: [[COPY:%[0-9]+]]:anyi1 = COPY $c
    ; CHECK: [[DEF:%[0-9]+]]:anyi8 = IMPLICIT_DEF
    ; CHECK: [[INSERT_SUBREG:%[0-9]+]]:anyi8 = INSERT_SUBREG [[DEF]], [[COPY]], %subreg.sublsb
    ; CHECK: [[DEF1:%[0-9]+]]:imag16 = IMPLICIT_DEF
    ; CHECK: [[INSERT_SUBREG1:%[0-9]+]]:imag16 = INSERT_SUBREG [[DEF1]], [[INSERT_SUBREG]], %subreg.sublo
    ; CHECK: RTS implicit [[INSERT_SUBREG1]]
    %0:any(s1) = COPY $c
    %1:any(s16) = G_ANYEXT %0
    RTS implicit %1
...
---
name: br_imm
legalized: true
regBankSelected: true
body: |
  bb.0.entry:
    ; CHECK-LABEL: name: br_imm
    ; CHECK: successors: %bb.0(0x80000000)
    ; CHECK: [[COPY:%[0-9]+]]:anyi1 = COPY $c
    ; CHECK: [[DEF:%[0-9]+]]:anyi8 = IMPLICIT_DEF
    ; CHECK: [[INSERT_SUBREG:%[0-9]+]]:anyi8 = INSERT_SUBREG [[DEF]], [[COPY]], %subreg.sublsb
    ; CHECK: [[COPY1:%[0-9]+]]:gpr = COPY [[INSERT_SUBREG]]
    ; CHECK: [[CMPImm:%[0-9]+]]:cc = CMPImm [[COPY1]], 0, implicit-def $nz
    ; CHECK: BR %bb.0, $z, 1
    ; CHECK: RTS
    %0:any(s1) = COPY $c
    G_BRCOND_IMM %0, %bb.0, 0
    RTS
...
---
name: cmpimm_brc
legalized: true
regBankSelected: true
body: |
  bb.0.entry:
    ; CHECK-LABEL: name: cmpimm_brc
    ; CHECK: successors: %bb.0(0x80000000)
    ; CHECK: [[COPY:%[0-9]+]]:gpr = COPY $a
    ; CHECK: [[CMPImm:%[0-9]+]]:cc = CMPImm [[COPY]], 42, implicit-def $nz
    ; CHECK: BR %bb.0, [[CMPImm]], 1
    ; CHECK: RTS
    %0:any(s8) = COPY $a
    %1:any(s8) = G_CONSTANT i8 42
    %2:any(s1), %3:any(s1), %4:any(s1), %5:any(s1) = G_CMP %0, %1
    G_BRCOND_IMM %2, %bb.0, 1
    RTS
...
---
name: cmpimm_brn
legalized: true
regBankSelected: true
body: |
  bb.0.entry:
    ; CHECK-LABEL: name: cmpimm_brn
    ; CHECK: successors: %bb.0(0x80000000)
    ; CHECK: [[COPY:%[0-9]+]]:gpr = COPY $a
    ; CHECK: [[CMPImm:%[0-9]+]]:cc = CMPImm [[COPY]], 42, implicit-def $nz
    ; CHECK: BR %bb.0, $n, 1
    ; CHECK: RTS
    %0:any(s8) = COPY $a
    %1:any(s8) = G_CONSTANT i8 42
    %2:any(s1), %3:any(s1), %4:any(s1), %5:any(s1) = G_CMP %0, %1
    G_BRCOND_IMM %3, %bb.0, 1
    RTS
...
---
name: cmpimm_brz
legalized: true
regBankSelected: true
body: |
  bb.0.entry:
    ; CHECK-LABEL: name: cmpimm_brz
    ; CHECK: successors: %bb.0(0x80000000)
    ; CHECK: [[COPY:%[0-9]+]]:gpr = COPY $a
    ; CHECK: [[CMPImm:%[0-9]+]]:cc = CMPImm [[COPY]], 42, implicit-def $nz
    ; CHECK: BR %bb.0, $z, 1
    ; CHECK: RTS
    %0:any(s8) = COPY $a
    %1:any(s8) = G_CONSTANT i8 42
    %2:any(s1), %3:any(s1), %4:any(s1), %5:any(s1) = G_CMP %0, %1
    G_BRCOND_IMM %5, %bb.0, 1
    RTS
...
---
name: cmp
legalized: true
regBankSelected: true
body: |
  bb.0.entry:
    ; CHECK-LABEL: name: cmp
    ; CHECK: [[COPY:%[0-9]+]]:ac = COPY $a
    ; CHECK: [[LDImm:%[0-9]+]]:gpr = LDImm 42, implicit-def $nz
    ; CHECK: [[COPY1:%[0-9]+]]:imag8 = COPY [[LDImm]]
    ; CHECK: [[LDCImm:%[0-9]+]]:cc = LDCImm 1
    ; CHECK: [[SBCNZImag8_:%[0-9]+]]:ac, [[SBCNZImag8_1:%[0-9]+]]:cc, [[SBCNZImag8_2:%[0-9]+]]:anyi1, [[SBCNZImag8_3:%[0-9]+]]:vc, [[SBCNZImag8_4:%[0-9]+]]:anyi1 = SBCNZImag8 [[COPY]], [[COPY1]], [[LDCImm]]
    ; CHECK: RTS implicit [[SBCNZImag8_1]], implicit [[SBCNZImag8_2]], implicit [[SBCNZImag8_3]], implicit [[SBCNZImag8_4]]
    %0:any(s8) = COPY $a
    %1:any(s8) = G_CONSTANT i8 42
    %2:any(s1), %3:any(s1), %4:any(s1), %5:any(s1) = G_CMP %0, %1
    RTS implicit %2, implicit %3, implicit %4, implicit %5
...
---
name: copy
legalized: true
regBankSelected: true
body: |
  bb.0.entry:
    liveins: $a
    ; CHECK-LABEL: name: copy
    ; CHECK: [[COPY:%[0-9]+]]:anyi8 = COPY $a
    ; CHECK: RTS implicit [[COPY]]
    %0:any(s8) = COPY $a
    RTS implicit %0
...
---
name: eor
legalized: true
regBankSelected: true
body: |
  bb.0.entry:
    ; CHECK-LABEL: name: eor
    ; CHECK: [[COPY:%[0-9]+]]:ac = COPY $x
    ; CHECK: [[COPY1:%[0-9]+]]:imag8 = COPY $a
    ; CHECK: [[EORImag8_:%[0-9]+]]:ac = EORImag8 [[COPY]], [[COPY1]], implicit-def $nz
    ; CHECK: RTS implicit [[EORImag8_]]
    %0:any(s8) = COPY $x
    %1:any(s8) = COPY $a
    %2:any(s8) = G_XOR %0, %1
    RTS implicit %2
...
---
name: ldcimm
legalized: true
regBankSelected: true
body: |
  bb.0.entry:
    ; CHECK-LABEL: name: ldcimm
    ; CHECK: [[LDCImm:%[0-9]+]]:cc = LDCImm 1
    ; CHECK: RTS implicit [[LDCImm]]
    %0:any(s1) = G_CONSTANT i1 true
    RTS implicit %0
...
---
name: ldimm
legalized: true
regBankSelected: true
body: |
  bb.0.entry:
    ; CHECK-LABEL: name: ldimm
    ; CHECK: [[LDImm:%[0-9]+]]:gpr = LDImm 42, implicit-def $nz
    ; CHECK: RTS implicit [[LDImm]]
    %0:any(s8) = G_CONSTANT i8 42
    RTS implicit %0
...
---
name: ldimm_16
legalized: true
regBankSelected: true
body: |
  bb.0.entry:
    ; CHECK-LABEL: name: ldimm_16
    ; CHECK: [[LDImm:%[0-9]+]]:gpr = LDImm 210, implicit-def $nz
    ; CHECK: [[LDImm1:%[0-9]+]]:gpr = LDImm 4, implicit-def $nz
    ; CHECK: [[REG_SEQUENCE:%[0-9]+]]:imag16 = REG_SEQUENCE [[LDImm]], %subreg.sublo, [[LDImm1]], %subreg.subhi
    ; CHECK: RTS implicit [[REG_SEQUENCE]]
    %0:any(s16) = G_CONSTANT i16 1234
    RTS implicit %0
...
---
name: load
legalized: true
regBankSelected: true
body: |
  bb.0.entry:
    ; CHECK-LABEL: name: load
    ; CHECK: [[COPY:%[0-9]+]]:imag16 = COPY $rs1
    ; CHECK: [[LDImm:%[0-9]+]]:yc = LDImm 0, implicit-def $nz
    ; CHECK: [[LDYIndir:%[0-9]+]]:ac = LDYIndir [[COPY]], [[LDImm]], implicit-def $nz :: (load 1)
    ; CHECK: RTS implicit [[LDYIndir]]
    %0:imag16(p0) = COPY $rs1
    %1:any(s8) = G_LOAD %0:imag16(p0) :: (load 1)
    RTS implicit %1
...
---
name: load_indexed_indir
legalized: true
regBankSelected: true
body: |
  bb.0.entry:
    ; CHECK-LABEL: name: load_indexed_indir
    ; CHECK: [[COPY:%[0-9]+]]:imag16 = COPY $rs1
    ; CHECK: [[LDImm:%[0-9]+]]:yc = LDImm 0, implicit-def $nz
    ; CHECK: [[LDYIndir:%[0-9]+]]:ac = LDYIndir [[COPY]], [[LDImm]], implicit-def $nz :: (load 1)
    ; CHECK: RTS implicit [[LDYIndir]]
    %0:any(p0) = COPY $rs1
    %1:any(s8) = G_LOAD %0 :: (load 1)
    RTS implicit %1
...
---
name: load_indexed_indir_ptr_add
legalized: true
regBankSelected: true
body: |
  bb.0.entry:
    ; CHECK-LABEL: name: load_indexed_indir_ptr_add
    ; CHECK: [[COPY:%[0-9]+]]:imag16 = COPY $rs1
    ; CHECK: [[LDImm:%[0-9]+]]:yc = LDImm 255, implicit-def $nz
    ; CHECK: [[LDYIndir:%[0-9]+]]:ac = LDYIndir [[COPY]], [[LDImm]], implicit-def $nz :: (load 1)
    ; CHECK: RTS implicit [[LDYIndir]]
    %0:any(p0) = COPY $rs1
    %1:any(s8) = G_CONSTANT i8 -1
    %2:any(p0) = G_PTR_ADD %0, %1
    %3:any(s8) = G_LOAD %2 :: (load 1)
    RTS implicit %3
...
---
name: lsr
legalized: true
regBankSelected: true
body: |
  bb.0.entry:
    ; CHECK-LABEL: name: lsr
    ; CHECK: [[COPY:%[0-9]+]]:aimag8 = COPY $a
    ; CHECK: [[LSR:%[0-9]+]]:aimag8, [[LSR1:%[0-9]+]]:cc = LSR [[COPY]], implicit-def $nz
    ; CHECK: RTS implicit [[LSR]], implicit [[LSR1]]
    %0:any(s8) = COPY $a
    %1:any(s1) = G_CONSTANT i1 0
    %2:any(s8), %3:any(s1) = G_LSHRE %0, %1
    RTS implicit %2, implicit %3
...
---
name: ora
legalized: true
regBankSelected: true
body: |
  bb.0.entry:
    ; CHECK-LABEL: name: ora
    ; CHECK: [[COPY:%[0-9]+]]:ac = COPY $x
    ; CHECK: [[COPY1:%[0-9]+]]:imag8 = COPY $a
    ; CHECK: [[ORAImag8_:%[0-9]+]]:ac = ORAImag8 [[COPY]], [[COPY1]], implicit-def $nz
    ; CHECK: RTS implicit [[ORAImag8_]]
    %0:any(s8) = COPY $x
    %1:any(s8) = COPY $a
    %2:any(s8) = G_OR %0, %1
    RTS implicit %2
...
---
name: ptr_add
legalized: true
regBankSelected: true
body: |
  bb.0.entry:
    ; CHECK-LABEL: name: ptr_add
    ; CHECK: [[COPY:%[0-9]+]]:imag16 = COPY $rs1
    ; CHECK: [[COPY1:%[0-9]+]]:imag8 = COPY $x
    ; CHECK: [[COPY2:%[0-9]+]]:ac = COPY [[COPY]].sublo
    ; CHECK: [[COPY3:%[0-9]+]]:ac = COPY [[COPY]].subhi
    ; CHECK: [[LDCImm:%[0-9]+]]:cc = LDCImm 0
    ; CHECK: [[ADCImag8_:%[0-9]+]]:ac, [[ADCImag8_1:%[0-9]+]]:cc, [[ADCImag8_2:%[0-9]+]]:vc = ADCImag8 [[COPY2]], [[COPY1]], [[LDCImm]], implicit-def $nz
    ; CHECK: [[ADCImm:%[0-9]+]]:ac, [[ADCImm1:%[0-9]+]]:cc, [[ADCImm2:%[0-9]+]]:vc = ADCImm [[COPY3]], 0, [[ADCImag8_1]], implicit-def $nz
    ; CHECK: [[REG_SEQUENCE:%[0-9]+]]:imag16 = REG_SEQUENCE [[ADCImag8_]], %subreg.sublo, [[ADCImm]], %subreg.subhi
    ; CHECK: RTS implicit [[REG_SEQUENCE]]
    %0:any(p0) = COPY $rs1
    %1:any(s8) = COPY $x
    %2:any(p0) = G_PTR_ADD %0, %1
    RTS implicit %2
...
---
name: rol
legalized: true
regBankSelected: true
body: |
  bb.0.entry:
    ; CHECK-LABEL: name: rol
    ; CHECK: [[COPY:%[0-9]+]]:aimag8 = COPY $a
    ; CHECK: [[COPY1:%[0-9]+]]:cc = COPY $v
    ; CHECK: [[ROL:%[0-9]+]]:aimag8, [[ROL1:%[0-9]+]]:cc = ROL [[COPY]], [[COPY1]], implicit-def $nz
    ; CHECK: RTS implicit [[ROL]], implicit [[ROL1]]
    %0:any(s8) = COPY $a
    %1:any(s1) = COPY $v
    %2:any(s8), %3:any(s1) = G_SHLE %0, %1
    RTS implicit %2, implicit %3
...
---
name: ror
legalized: true
regBankSelected: true
body: |
  bb.0.entry:
    ; CHECK-LABEL: name: ror
    ; CHECK: [[COPY:%[0-9]+]]:aimag8 = COPY $a
    ; CHECK: [[COPY1:%[0-9]+]]:cc = COPY $v
    ; CHECK: [[ROR:%[0-9]+]]:aimag8, [[ROR1:%[0-9]+]]:cc = ROR [[COPY]], [[COPY1]], implicit-def $nz
    ; CHECK: RTS implicit [[ROR]], implicit [[ROR1]]
    %0:any(s8) = COPY $a
    %1:any(s1) = COPY $v
    %2:any(s8), %3:any(s1) = G_LSHRE %0, %1
    RTS implicit %2, implicit %3
...
---
name: store
legalized: true
regBankSelected: true
body: |
  bb.0.entry:
    ; CHECK-LABEL: name: store
    ; CHECK: [[COPY:%[0-9]+]]:ac = COPY $x
    ; CHECK: [[COPY1:%[0-9]+]]:imag16 = COPY $rs1
    ; CHECK: [[LDImm:%[0-9]+]]:yc = LDImm 0, implicit-def $nz
    ; CHECK: STYIndir [[COPY]], [[COPY1]], [[LDImm]] :: (store 1)
    ; CHECK: RTS
    %0:any(s8) = COPY $x
    %1:any(p0) = COPY $rs1
    G_STORE %0, %1 :: (store 1)
    RTS
...
---
name: trunc_8_1
legalized: true
regBankSelected: true
body: |
  bb.0.entry:
    ; CHECK-LABEL: name: trunc_8_1
    ; CHECK: [[COPY:%[0-9]+]]:anyi8 = COPY $a
    ; CHECK: [[COPY1:%[0-9]+]]:anyi1 = COPY [[COPY]].sublsb
    ; CHECK: RTS implicit [[COPY1]]
    %0:any(s8) = COPY $a
    %1:any(s1) = G_TRUNC %0
    RTS implicit %1
...
---
name: trunc_16_8
legalized: true
regBankSelected: true
body: |
  bb.0.entry:
    ; CHECK-LABEL: name: trunc_16_8
    ; CHECK: [[COPY:%[0-9]+]]:imag16 = COPY $rs1
    ; CHECK: [[COPY1:%[0-9]+]]:anyi8 = COPY [[COPY]].sublo
    ; CHECK: RTS implicit [[COPY1]]
    %0:any(s16) = COPY $rs1
    %1:any(s8) = G_TRUNC %0
    RTS implicit %1
...
---
name: trunc_16_1
legalized: true
regBankSelected: true
body: |
  bb.0.entry:
    ; CHECK-LABEL: name: trunc_16_1
    ; CHECK: [[COPY:%[0-9]+]]:imag16 = COPY $rs1
    ; CHECK: [[COPY1:%[0-9]+]]:anyi8 = COPY [[COPY]].sublo
    ; CHECK: [[COPY2:%[0-9]+]]:anyi1 = COPY [[COPY1]].sublsb
    ; CHECK: RTS implicit [[COPY2]]
    %0:any(s16) = COPY $rs1
    %1:any(s1) = G_TRUNC %0
    RTS implicit %1
...
---
name: uadde_imm
legalized: true
regBankSelected: true
body: |
  bb.0.entry:
    ; CHECK-LABEL: name: uadde_imm
    ; CHECK: [[COPY:%[0-9]+]]:ac = COPY $x
    ; CHECK: [[COPY1:%[0-9]+]]:cc = COPY $v
    ; CHECK: [[ADCImm:%[0-9]+]]:ac, [[ADCImm1:%[0-9]+]]:cc, [[ADCImm2:%[0-9]+]]:vc = ADCImm [[COPY]], 42, [[COPY1]], implicit-def $nz
    ; CHECK: RTS implicit [[ADCImm]], implicit [[ADCImm1]]
    %0:any(s8) = COPY $x
    %1:any(s8) = G_CONSTANT i8 42
    %2:any(s1) = COPY $v
    %3:any(s8), %4:any(s1) = G_UADDE %0:any(s8), %1:any(s8), %2:any(s1)
    RTS implicit %3, implicit %4
...
---
name: uadde
legalized: true
regBankSelected: true
body: |
  bb.0.entry:
    ; CHECK-LABEL: name: uadde
    ; CHECK: [[COPY:%[0-9]+]]:ac = COPY $x
    ; CHECK: [[COPY1:%[0-9]+]]:imag8 = COPY $a
    ; CHECK: [[COPY2:%[0-9]+]]:cc = COPY $v
    ; CHECK: [[ADCImag8_:%[0-9]+]]:ac, [[ADCImag8_1:%[0-9]+]]:cc, [[ADCImag8_2:%[0-9]+]]:vc = ADCImag8 [[COPY]], [[COPY1]], [[COPY2]], implicit-def $nz
    ; CHECK: RTS implicit [[ADCImag8_]], implicit [[ADCImag8_1]]
    %0:any(s8) = COPY $x
    %1:any(s8) = COPY $a
    %2:any(s1) = COPY $v
    %3:any(s8), %4:any(s1) = G_UADDE %0:any(s8), %1:any(s8), %2:any(s1)
    RTS implicit %3, implicit %4
...
---
name: unmerge
legalized: true
regBankSelected: true
body: |
  bb.0.entry:
    ; CHECK-LABEL: name: unmerge
    ; CHECK: [[COPY:%[0-9]+]]:anyi8 = COPY %2.sublo:imag16
    ; CHECK: [[COPY1:%[0-9]+]]:anyi8 = COPY %2.subhi:imag16
    ; CHECK: RTS implicit [[COPY]], implicit [[COPY1]]
    %1:any(s8), %2:any(s8) = G_UNMERGE_VALUES %0:imag16(s16)
    RTS implicit %1, implicit %2
...
