# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -mtriple=mos -mcpu=mosw65816 -run-pass=mos-late-opt -verify-machineinstrs -o - %s | FileCheck %s
---
name: cmpzero_x_a_busy
body: |
  bb.0.entry:
    liveins: $x, $a
    ; CHECK-LABEL: name: cmpzero_x_a_busy
    ; CHECK: liveins: $x, $a
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: dead $y = TX $x, implicit-def $nz
    ; CHECK-NEXT: RTS implicit $n, implicit $a
    CmpZero $x, implicit-def $n, implicit-def $c
    RTS implicit $n, implicit $a
...
---
name: cmpzero_y_a_busy
body: |
  bb.0.entry:
    liveins: $x, $a
    ; CHECK-LABEL: name: cmpzero_y_a_busy
    ; CHECK: liveins: $x, $a
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: dead $x = TX $y, implicit-def $nz
    ; CHECK-NEXT: RTS implicit $n, implicit $a
    CmpZero $y, implicit-def $n, implicit-def $c
    RTS implicit $n, implicit $a
...
---
name: ldimm_to_txy
body: |
  bb.0.entry:
    ; CHECK-LABEL: name: ldimm_to_txy
    ; CHECK: $x = LDImm 1
    ; CHECK-NEXT: $rc0 = STImag8 $x
    ; CHECK-NEXT: $y = TX $x
    ; CHECK-NEXT: RTS implicit $y
    $x = LDImm 1
    $rc0 = STImag8 killed $x
    $y = LDImm 1
    RTS implicit $y
...
---
name: ldimm_to_tyx
body: |
  bb.0.entry:
    ; CHECK-LABEL: name: ldimm_to_tyx
    ; CHECK: $y = LDImm 1
    ; CHECK-NEXT: $rc0 = STImag8 $y
    ; CHECK-NEXT: $x = TX $y
    ; CHECK-NEXT: RTS implicit $x
    $y = LDImm 1
    $rc0 = STImag8 killed $y
    $x = LDImm 1
    RTS implicit $x
...
---
# When the transfer source is a dead LDImm (e.g. an RA-rematerialized constant whose
# value was otherwise unused), reusing it as a TXY/TYX must clear the dead flag, else
# the new transfer reads a register the verifier considers undefined. Before the fix
# these crashed with "Bad machine code: Using an undefined physical register".
name: ldimm_to_txy_clears_dead_source
body: |
  bb.0.entry:
    ; CHECK-LABEL: name: ldimm_to_txy_clears_dead_source
    ; CHECK: $x = LDImm 1
    ; CHECK-NEXT: $y = TX $x
    ; CHECK-NEXT: RTS implicit $y
    dead $x = LDImm 1
    $y = LDImm 1
    RTS implicit $y
...
---
name: ldimm_to_tyx_clears_dead_source
body: |
  bb.0.entry:
    ; CHECK-LABEL: name: ldimm_to_tyx_clears_dead_source
    ; CHECK: $y = LDImm 1
    ; CHECK-NEXT: $x = TX $y
    ; CHECK-NEXT: RTS implicit $x
    dead $y = LDImm 1
    $x = LDImm 1
    RTS implicit $x
...
