# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -mtriple=mos -run-pass=mos-late-opt -verify-machineinstrs -o - %s | FileCheck %s
---
name: cmpzero_alone
body: |
  bb.0.entry:
    liveins: $a
    ; CHECK-LABEL: name: cmpzero_alone
    ; CHECK: liveins: $a
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: dead $x = TA $a, implicit-def $nz
    ; CHECK-NEXT: RTS implicit $n
    CmpZero $a, implicit-def $n, implicit-def $c
    RTS implicit $n
...
---
name: cmpzero_elision
body: |
  bb.0.entry:
    liveins: $x
    ; CHECK-LABEL: name: cmpzero_elision
    ; CHECK: liveins: $x
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: $a = T_A killed $x, implicit-def $nz
    ; CHECK-NEXT: RTS implicit $n
    $a = T_A killed $x
    CmpZero $a, implicit-def $n, implicit-def $c
    RTS implicit $n
...
---
name: cmpzero_copy_elision
body: |
  bb.0.entry:
    liveins: $a
    ; CHECK-LABEL: name: cmpzero_copy_elision
    ; CHECK: liveins: $a
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: $x = TA killed $a, implicit-def $nz
    ; CHECK-NEXT: RTS implicit $n
    $x = TA killed $a
    CmpZero $a, implicit-def $n, implicit-def $c
    RTS implicit $n
...
---
name: cmpzero_stimag8
body: |
  bb.0.entry:
    liveins: $x
    ; CHECK-LABEL: name: cmpzero_stimag8
    ; CHECK: liveins: $x
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: $rc1 = STImag8 $x
    ; CHECK-NEXT: dead $a = LDImag8 $rc1, implicit-def $nz
    ; CHECK-NEXT: RTS implicit $n
    $rc1 = STImag8 $x
    CmpZero $rc1, implicit-def $n, implicit-def $c
    RTS implicit $n
...
---
name: cmpzero_clobbered
body: |
  bb.0.entry:
    liveins: $a, $rc2
    ; CHECK-LABEL: name: cmpzero_clobbered
    ; CHECK: liveins: $a, $rc2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: $a = T_A killed $x
    ; CHECK-NEXT: $y = LDImag8 $rc2
    ; CHECK-NEXT: dead $x = TA $a, implicit-def $nz
    ; CHECK-NEXT: RTS implicit $n
    $a = T_A killed $x
    $y = LDImag8 $rc2
    CmpZero $a, implicit-def $n, implicit-def $c
    RTS implicit $n
...
---
name: cmpzero_clobbered_rmw
body: |
  bb.0.entry:
    liveins: $a, $rc2
    ; CHECK-LABEL: name: cmpzero_clobbered_rmw
    ; CHECK: liveins: $a, $rc2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: $a = T_A killed $x
    ; CHECK-NEXT: INCAbs 1234
    ; CHECK-NEXT: dead $x = TA $a, implicit-def $nz
    ; CHECK-NEXT: RTS implicit $n
    $a = T_A killed $x
    INCAbs 1234
    CmpZero $a, implicit-def $n, implicit-def $c
    RTS implicit $n
...
---
name: cmpzero_not_clobbered
body: |
  bb.0.entry:
    liveins: $a, $y
    ; CHECK-LABEL: name: cmpzero_not_clobbered
    ; CHECK: liveins: $a, $y
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: $a = T_A killed $x, implicit-def $nz
    ; CHECK-NEXT: $rc2 = STImag8 $y
    ; CHECK-NEXT: RTS implicit $n
    $a = T_A killed $x
    $rc2 = STImag8 $y
    CmpZero $a, implicit-def $n, implicit-def $c
    RTS implicit $n
...
---
name: cmpzero_a_x_busy
body: |
  bb.0.entry:
    liveins: $a, $x
    ; CHECK-LABEL: name: cmpzero_a_x_busy
    ; CHECK: liveins: $a, $x
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: dead $y = TA $a, implicit-def $nz
    ; CHECK-NEXT: RTS implicit $n, implicit $x
    CmpZero $a, implicit-def $n, implicit-def $c
    RTS implicit $n, implicit $x
...
---
name: cmpzero_a_xy_busy
body: |
  bb.0.entry:
    liveins: $a, $x, $y
    ; CHECK-LABEL: name: cmpzero_a_xy_busy
    ; CHECK: liveins: $a, $x, $y
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: dead $c = CMPImm $a, 0, implicit-def $nz
    ; CHECK-NEXT: RTS implicit $n, implicit $x, implicit $y
    CmpZero $a, implicit-def $n, implicit-def $c
    RTS implicit $n, implicit $x, implicit $y
...
---
name: cmpzero_x
body: |
  bb.0.entry:
    liveins: $x
    ; CHECK-LABEL: name: cmpzero_x
    ; CHECK: liveins: $x
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: dead $a = T_A $x, implicit-def $nz
    ; CHECK-NEXT: RTS implicit $n
    CmpZero $x, implicit-def $n, implicit-def $c
    RTS implicit $n
...
---
name: cmpzero_x_a_busy
body: |
  bb.0.entry:
    liveins: $x, $a
    ; CHECK-LABEL: name: cmpzero_x_a_busy
    ; CHECK: liveins: $x, $a
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: dead $c = CMPImm $x, 0, implicit-def $nz
    ; CHECK-NEXT: RTS implicit $n, implicit $a
    CmpZero $x, implicit-def $n, implicit-def $c
    RTS implicit $n, implicit $a
...
---
name: cmpzero_y
body: |
  bb.0.entry:
    liveins: $x
    ; CHECK-LABEL: name: cmpzero_y
    ; CHECK: liveins: $x
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: dead $a = T_A $y, implicit-def $nz
    ; CHECK-NEXT: RTS implicit $n
    CmpZero $y, implicit-def $n, implicit-def $c
    RTS implicit $n
...
---
name: cmpzero_y_a_busy
body: |
  bb.0.entry:
    liveins: $x, $a
    ; CHECK-LABEL: name: cmpzero_y_a_busy
    ; CHECK: liveins: $x, $a
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: dead $c = CMPImm $y, 0, implicit-def $nz
    ; CHECK-NEXT: RTS implicit $n, implicit $a
    CmpZero $y, implicit-def $n, implicit-def $c
    RTS implicit $n, implicit $a
...
---
name: cmpzero_imag8_a_free
body: |
  bb.0.entry:
    liveins: $rc2
    ; CHECK-LABEL: name: cmpzero_imag8_a_free
    ; CHECK: liveins: $rc2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: dead $a = LDImag8 $rc2, implicit-def $nz
    ; CHECK-NEXT: RTS implicit $n
    CmpZero $rc2, implicit-def $n, implicit-def $c
    RTS implicit $n
...
---
name: cmpzero_imag8_x_free
body: |
  bb.0.entry:
    liveins: $rc2, $a
    ; CHECK-LABEL: name: cmpzero_imag8_x_free
    ; CHECK: liveins: $rc2, $a
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: dead $x = LDImag8 $rc2, implicit-def $nz
    ; CHECK-NEXT: RTS implicit $n, implicit $a
    CmpZero $rc2, implicit-def $n, implicit-def $c
    RTS implicit $n, implicit $a
...
---
name: cmpzero_imag8_y_free
body: |
  bb.0.entry:
    liveins: $rc2, $a, $x
    ; CHECK-LABEL: name: cmpzero_imag8_y_free
    ; CHECK: liveins: $rc2, $a, $x
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: dead $y = LDImag8 $rc2, implicit-def $nz
    ; CHECK-NEXT: RTS implicit $n, implicit $a, implicit $x
    CmpZero $rc2, implicit-def $n, implicit-def $c
    RTS implicit $n, implicit $a, implicit $x
...
---
name: cmpzero_imag8_no_gpr_free
body: |
  bb.0.entry:
    liveins: $rc2, $a, $x, $y
    ; CHECK-LABEL: name: cmpzero_imag8_no_gpr_free
    ; CHECK: liveins: $rc2, $a, $x, $y
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: $rc2 = INC $rc2
    ; CHECK-NEXT: dead $rc2 = DEC $rc2, implicit-def $nz
    ; CHECK-NEXT: RTS implicit $n, implicit $a, implicit $x, implicit $y
    CmpZero $rc2, implicit-def $n, implicit-def $c
    RTS implicit $n, implicit $a, implicit $x, implicit $y
...
---
name: cmpzero_imag8_no_gpr_free_lda_avail
body: |
  bb.0.entry:
    liveins: $rc2, $x, $y
    ; CHECK-LABEL: name: cmpzero_imag8_no_gpr_free_lda_avail
    ; CHECK: liveins: $rc2, $x, $y
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: $a = LDImag8 $rc2
    ; CHECK-NEXT: $x = INC $x
    ; CHECK-NEXT: dead $c = CMPImm $a, 0, implicit-def $nz
    ; CHECK-NEXT: RTS implicit $n, implicit $a, implicit $x, implicit $y
    $a = LDImag8 $rc2
    $x = INC $x
    CmpZero $rc2, implicit-def $n, implicit-def $c
    RTS implicit $n, implicit $a, implicit $x, implicit $y
...
---
name: cmpzero_imag8_no_gpr_free_ldx_avail
body: |
  bb.0.entry:
    liveins: $rc2, $a, $x, $y
    ; CHECK-LABEL: name: cmpzero_imag8_no_gpr_free_ldx_avail
    ; CHECK: liveins: $rc2, $a, $x, $y
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: $x = LDImag8 $rc2
    ; CHECK-NEXT: $y = INC $y
    ; CHECK-NEXT: dead $c = CMPImm $x, 0, implicit-def $nz
    ; CHECK-NEXT: RTS implicit $n, implicit $a, implicit $x, implicit $y
    $x = LDImag8 $rc2
    $y = INC $y
    CmpZero $rc2, implicit-def $n, implicit-def $c
    RTS implicit $n, implicit $a, implicit $x, implicit $y
...
---
name: cmpzero_imag8_no_gpr_free_ldy_avail
body: |
  bb.0.entry:
    liveins: $rc2, $a, $x, $y
    ; CHECK-LABEL: name: cmpzero_imag8_no_gpr_free_ldy_avail
    ; CHECK: liveins: $rc2, $a, $x, $y
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: $y = LDImag8 $rc2
    ; CHECK-NEXT: $x = INC $x
    ; CHECK-NEXT: dead $c = CMPImm $y, 0, implicit-def $nz
    ; CHECK-NEXT: RTS implicit $n, implicit $a, implicit $x, implicit $y
    $y = LDImag8 $rc2
    $x = INC $x
    CmpZero $rc2, implicit-def $n, implicit-def $c
    RTS implicit $n, implicit $a, implicit $x, implicit $y
...
---
name: cmpzero_imag8_no_gpr_free_lda_clobbered
body: |
  bb.0.entry:
    liveins: $rc2, $a, $x, $y
    ; CHECK-LABEL: name: cmpzero_imag8_no_gpr_free_lda_clobbered
    ; CHECK: liveins: $rc2, $a, $x, $y
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: $a = LDImag8 $rc2
    ; CHECK-NEXT: $a = COPY $x
    ; CHECK-NEXT: $rc2 = INC $rc2
    ; CHECK-NEXT: dead $rc2 = DEC $rc2, implicit-def $nz
    ; CHECK-NEXT: RTS implicit $n, implicit $a, implicit $x, implicit $y
    $a = LDImag8 $rc2
    $a = COPY $x
    CmpZero $rc2, implicit-def $n, implicit-def $c
    RTS implicit $n, implicit $a, implicit $x, implicit $y
...
---
name: cmpzero_imag8_no_gpr_free_lda_clobbered_ldx_avail
body: |
  bb.0.entry:
    liveins: $rc2, $x, $y
    ; CHECK-LABEL: name: cmpzero_imag8_no_gpr_free_lda_clobbered_ldx_avail
    ; CHECK: liveins: $rc2, $x, $y
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: $x = LDImag8 $rc2
    ; CHECK-NEXT: $a = LDImag8 $rc2
    ; CHECK-NEXT: $a = COPY $y
    ; CHECK-NEXT: dead $c = CMPImm $x, 0, implicit-def $nz
    ; CHECK-NEXT: RTS implicit $n, implicit $a, implicit $x, implicit $y
    $x = LDImag8 $rc2
    $a = LDImag8 $rc2
    $a = COPY $y
    CmpZero $rc2, implicit-def $n, implicit-def $c
    RTS implicit $n, implicit $a, implicit $x, implicit $y
...
---
name: cmpzero_imag8_no_gpr_free_sta
body: |
  bb.0.entry:
    liveins: $rc2, $x, $y
    ; CHECK-LABEL: name: cmpzero_imag8_no_gpr_free_sta
    ; CHECK: liveins: $rc2, $x, $y
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: $rc2 = STImag8 $a
    ; CHECK-NEXT: dead $c = CMPImm $a, 0, implicit-def $nz
    ; CHECK-NEXT: RTS implicit $n, implicit $a, implicit $x, implicit $y
    $rc2 = STImag8 $a
    CmpZero $rc2, implicit-def $n, implicit-def $c
    RTS implicit $n, implicit $a, implicit $x, implicit $y
...
---
name: cmpzero_imag8_no_gpr_free_lda_but_val_changed
body: |
  bb.0.entry:
    liveins: $rc2, $a, $x, $y
    ; CHECK-LABEL: name: cmpzero_imag8_no_gpr_free_lda_but_val_changed
    ; CHECK: liveins: $rc2, $a, $x, $y
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: $a = LDImag8 $rc2
    ; CHECK-NEXT: $rc2 = INC $rc2
    ; CHECK-NEXT: $x = INC $x
    ; CHECK-NEXT: $rc2 = INC $rc2
    ; CHECK-NEXT: dead $rc2 = DEC $rc2, implicit-def $nz
    ; CHECK-NEXT: RTS implicit $n, implicit $a, implicit $x, implicit $y
    $a = LDImag8 $rc2
    $rc2 = INC $rc2
    $x = INC $x
    CmpZero $rc2, implicit-def $n, implicit-def $c
    RTS implicit $n, implicit $a, implicit $x, implicit $y
...
---
name: cmpzero_imag8_no_gpr_free_sta_clobbered
body: |
  bb.0.entry:
    liveins: $rc2, $x, $y
    ; CHECK-LABEL: name: cmpzero_imag8_no_gpr_free_sta_clobbered
    ; CHECK: liveins: $rc2, $x, $y
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: $rc2 = STImag8 $a
    ; CHECK-NEXT: $a = EORImm $a, 42
    ; CHECK-NEXT: $rc2 = INC $rc2
    ; CHECK-NEXT: dead $rc2 = DEC $rc2, implicit-def $nz
    ; CHECK-NEXT: RTS implicit $n, implicit $a, implicit $x, implicit $y
    $rc2 = STImag8 $a
    $a = EORImm $a, 42
    CmpZero $rc2, implicit-def $n, implicit-def $c
    RTS implicit $n, implicit $a, implicit $x, implicit $y
...
---
name: cmpzero_multiple
body: |
  bb.0.entry:
    liveins: $x, $y
    ; CHECK-LABEL: name: cmpzero_multiple
    ; CHECK: liveins: $x, $y
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: dead $a = T_A $y, implicit-def $nz
    ; CHECK-NEXT: RTS implicit $n
    CmpZero $x, implicit-def dead $c
    CmpZero $y, implicit-def $n, implicit-def $c
    RTS implicit $n
...
---
name: ldxyimm_to_inxydexy
body: |
  bb.0.entry:
    ; CHECK-LABEL: name: ldxyimm_to_inxydexy
    ; CHECK: $x = LDImm 0
    ; CHECK-NEXT: $y = LDImm 5
    ; CHECK-NEXT: $x = INC $x
    ; CHECK-NEXT: $y = INC $y
    ; CHECK-NEXT: $x = DEC killed $x
    ; CHECK-NEXT: $y = DEC killed $y
    ; CHECK-NEXT: RTS implicit $x, implicit $y
    dead $x = LDImm 0
    dead $y = LDImm 5
    $x = LDImm 1
    $y = LDImm 6
    $x = LDImm 0
    $y = LDImm 5
    RTS implicit $x, implicit $y
...
---
name: ldxyimm_clobbered
body: |
  bb.0.entry:
    ; CHECK-LABEL: name: ldxyimm_clobbered
    ; CHECK: dead $x = LDImm 0
    ; CHECK-NEXT: dead $x = LDImag8 $rc0
    ; CHECK-NEXT: $x = LDImm 1
    ; CHECK-NEXT: RTS implicit $x
    dead $x = LDImm 0
    dead $x = LDImag8 $rc0
    $x = LDImm 1
    RTS implicit $x
...
---
name: ldxyimm_target_index
body: |
  bb.0.entry:
    ; CHECK-LABEL: name: ldxyimm_target_index
    ; CHECK: dead $x = LDImm target-flags(lo) target-index(mos-static-stack)
    ; CHECK-NEXT: $x = LDImm 1
    ; CHECK-NEXT: RTS implicit $x
    dead $x = LDImm target-flags(lo) target-index(mos-static-stack)
    $x = LDImm 1
    RTS implicit $x
...
---
name: ldxyimm_clear_killed
body: |
  bb.0.entry:
    ; CHECK-LABEL: name: ldxyimm_clear_killed
    ; CHECK: $x = LDImm 0
    ; CHECK-NEXT: $rc0 = STImag8 $x
    ; CHECK-NEXT: $x = INC killed $x
    ; CHECK-NEXT: RTS implicit $x
    $x = LDImm 0
    $rc0 = STImag8 killed $x
    $x = LDImm 1
    RTS implicit $x
...
---
name: tail_jmp
body: |
  bb.0.entry:
    liveins: $a
    ; CHECK-LABEL: name: tail_jmp
    ; CHECK: liveins: $a
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: TailJMP &foo
    JSR &foo
    RTS
...
---
name: ldimm_to_tay
body: |
  bb.0.entry:
    ; CHECK-LABEL: name: ldimm_to_tay
    ; CHECK: $a = LDImm 1
    ; CHECK-NEXT: $rc0 = STImag8 $a
    ; CHECK-NEXT: $y = TA $a
    ; CHECK-NEXT: RTS implicit $y
    $a = LDImm 1
    $rc0 = STImag8 killed $a
    $y = LDImm 1
    RTS implicit $y
...
---
name: ldimm_to_tax
body: |
  bb.0.entry:
    ; CHECK-LABEL: name: ldimm_to_tax
    ; CHECK: $a = LDImm 1
    ; CHECK-NEXT: $rc0 = STImag8 $a
    ; CHECK-NEXT: $x = TA $a
    ; CHECK-NEXT: RTS implicit $x
    $a = LDImm 1
    $rc0 = STImag8 killed $a
    $x = LDImm 1
    RTS implicit $x
...
---
name: ldimm_to_txa
body: |
  bb.0.entry:
    ; CHECK-LABEL: name: ldimm_to_txa
    ; CHECK: $x = LDImm 1
    ; CHECK-NEXT: $rc0 = STImag8 $x
    ; CHECK-NEXT: $a = T_A $x
    ; CHECK-NEXT: RTS implicit $a
    $x = LDImm 1
    $rc0 = STImag8 killed $x
    $a = LDImm 1
    RTS implicit $a
...
---
name: ldimm_to_tya
body: |
  bb.0.entry:
    ; CHECK-LABEL: name: ldimm_to_tya
    ; CHECK: $y = LDImm 1
    ; CHECK-NEXT: $rc0 = STImag8 $y
    ; CHECK-NEXT: $a = T_A $y
    ; CHECK-NEXT: RTS implicit $a
    $y = LDImm 1
    $rc0 = STImag8 killed $y
    $a = LDImm 1
    RTS implicit $a
...
---
name: ldimm_tay_to_iny
body: |
  bb.0.entry:
    ; CHECK-LABEL: name: ldimm_tay_to_iny
    ; CHECK: $a = LDImm 0
    ; CHECK-NEXT: $y = TA $a
    ; CHECK-NEXT: $y = INC killed $y
    ; CHECK-NEXT: RTS implicit $a
    $a = LDImm 0
    $y = TA $a
    $y = LDImm 1
    RTS implicit $a
...
