; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 2
; RUN: opt -O2 -verify-each -S %s | FileCheck %s

define dso_local void @chrout_u16() #0 {
; CHECK-LABEL: define dso_local void @chrout_u16
; CHECK-SAME: () local_unnamed_addr #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    tail call void asm sideeffect "\0A LDA #$$42\0A JSR $$FFD2\0A ", "~{a},~{c}"() #[[ATTR2:[0-9]+]]
; CHECK-NEXT:    ret void
;
entry:
  call void asm sideeffect "\0A    LDA #$$42\0A    JSR $$FFD2\0A  ", "~{a},~{c}"() #2
  ret void
}

define dso_local noundef i16 @main() #1 {
; CHECK-LABEL: define dso_local noundef i16 @main
; CHECK-SAME: () local_unnamed_addr #[[ATTR1:[0-9]+]] {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    tail call void @chrout_u16()
; CHECK-NEXT:    ret i16 0
;
entry:
  call void @chrout_u16()
  ret i16 0
}

attributes #0 = { mustprogress noinline nounwind "frame-pointer"="all" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="mos45gs02" }
attributes #1 = { mustprogress noinline norecurse nounwind "frame-pointer"="all" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="mos45gs02" }
attributes #2 = { nocallback nounwind }
