# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -mtriple=mos -mcpu=moshuc6280 -run-pass=legalizer -verify-machineinstrs -o - %s | FileCheck %s

--- |
  define i16 @memcpy_to_tii() #0 {
    ret i16 1
  }

  define i16 @memset_to_tii() #0 {
    ret i16 1
  }

  define i16 @memcpy_to_multiple_tii() #0 {
    ret i16 1
  }

  define i16 @memset_to_multiple_tii() #0 {
    ret i16 1
  }

  attributes #0 = { optsize }
---
name: memcpy_to_tii
body: |
  bb.1 (%ir-block.0):
    ; CHECK-LABEL: name: memcpy_to_tii
    ; CHECK: [[C:%[0-9]+]]:_(s8) = G_CONSTANT i8 0
    ; CHECK-NEXT: [[MV:%[0-9]+]]:_(s16) = G_MERGE_VALUES [[C]](s8), [[C]](s8)
    ; CHECK-NEXT: HuCMemcpy 8704, 8960, 6, 0 :: (load (s8) from `ptr inttoptr (i16 8704 to ptr)`), (store (s8) into `ptr inttoptr (i16 8960 to ptr)`)
    ; CHECK-NEXT: RTS implicit [[MV]](s16)
    %1:_(s16) = G_CONSTANT i16 8960
    %0:_(p0) = G_INTTOPTR %1:_(s16)
    %3:_(s16) = G_CONSTANT i16 8704
    %2:_(p0) = G_INTTOPTR %3:_(s16)
    %4:_(s16) = G_CONSTANT i16 6
    %5:_(s16) = G_CONSTANT i16 0
    G_MEMCPY %0:_(p0), %2:_(p0), %4:_(s16), 1 :: (store (s8) into `ptr inttoptr (i16 8960 to ptr)`, align 256), (load (s8) from `ptr inttoptr (i16 8704 to ptr)`, align 512); example.c:11:3
    RTS implicit %5
...
---
name: memset_to_tii
body: |
  bb.1 (%ir-block.0):
    ; CHECK-LABEL: name: memset_to_tii
    ; CHECK: [[C:%[0-9]+]]:_(s8) = G_CONSTANT i8 0
    ; CHECK-NEXT: [[MV:%[0-9]+]]:_(s16) = G_MERGE_VALUES [[C]](s8), [[C]](s8)
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s8) = COPY [[C]](s8)
    ; CHECK-NEXT: G_STORE_ABS [[COPY]](s8), 8960 :: (store (s8) into `ptr inttoptr (i16 8960 to ptr)`)
    ; CHECK-NEXT: HuCMemcpy 8960, 8961, 5, 0 :: (load (s8) from `ptr inttoptr (i16 8960 to ptr)`), (store (s8) into `ptr inttoptr (i16 8960 to ptr)` + 1)
    ; CHECK-NEXT: RTS implicit [[MV]](s16)
    %1:_(s16) = G_CONSTANT i16 8960
    %0:_(p0) = G_INTTOPTR %1:_(s16)
    %2:_(s8) = G_CONSTANT i8 0
    %3:_(s16) = G_CONSTANT i16 6
    %4:_(s16) = G_CONSTANT i16 0
    G_MEMSET %0:_(p0), %2:_(s8), %3:_(s16), 1 :: (store (s8) into `ptr inttoptr (i16 8960 to ptr)`, align 256); example.c:11:3
    RTS implicit %4
...
---
name: memcpy_to_multiple_tii
body: |
  bb.1 (%ir-block.0):
    ; CHECK-LABEL: name: memcpy_to_multiple_tii
    ; CHECK: [[C:%[0-9]+]]:_(s8) = G_CONSTANT i8 0
    ; CHECK-NEXT: [[MV:%[0-9]+]]:_(s16) = G_MERGE_VALUES [[C]](s8), [[C]](s8)
    ; CHECK-NEXT: HuCMemcpy 8704, 8960, 16, 0 :: (load (s8) from `ptr inttoptr (i16 8704 to ptr)`), (store (s8) into `ptr inttoptr (i16 8960 to ptr)`)
    ; CHECK-NEXT: HuCMemcpy 8720, 8976, 16, 0 :: (load (s8) from `ptr inttoptr (i16 8704 to ptr)` + 16), (store (s8) into `ptr inttoptr (i16 8960 to ptr)` + 16)
    ; CHECK-NEXT: HuCMemcpy 8736, 8992, 6, 0 :: (load (s8) from `ptr inttoptr (i16 8704 to ptr)` + 32), (store (s8) into `ptr inttoptr (i16 8960 to ptr)` + 32)
    ; CHECK-NEXT: RTS implicit [[MV]](s16)
    %1:_(s16) = G_CONSTANT i16 8960
    %0:_(p0) = G_INTTOPTR %1:_(s16)
    %3:_(s16) = G_CONSTANT i16 8704
    %2:_(p0) = G_INTTOPTR %3:_(s16)
    %4:_(s16) = G_CONSTANT i16 38
    %5:_(s16) = G_CONSTANT i16 0
    G_MEMCPY %0:_(p0), %2:_(p0), %4:_(s16), 1 :: (store (s8) into `ptr inttoptr (i16 8960 to ptr)`, align 256), (load (s8) from `ptr inttoptr (i16 8704 to ptr)`, align 512); example.c:11:3
    RTS implicit %5
...
---
name: memset_to_multiple_tii
body: |
  bb.1 (%ir-block.0):
    ; CHECK-LABEL: name: memset_to_multiple_tii
    ; CHECK: [[C:%[0-9]+]]:_(s8) = G_CONSTANT i8 0
    ; CHECK-NEXT: [[MV:%[0-9]+]]:_(s16) = G_MERGE_VALUES [[C]](s8), [[C]](s8)
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s8) = COPY [[C]](s8)
    ; CHECK-NEXT: G_STORE_ABS [[COPY]](s8), 8960 :: (store (s8) into `ptr inttoptr (i16 8960 to ptr)`)
    ; CHECK-NEXT: HuCMemcpy 8960, 8961, 16, 0 :: (load (s8) from `ptr inttoptr (i16 8960 to ptr)`), (store (s8) into `ptr inttoptr (i16 8960 to ptr)` + 1)
    ; CHECK-NEXT: HuCMemcpy 8976, 8977, 16, 0 :: (load (s8) from `ptr inttoptr (i16 8960 to ptr)` + 16), (store (s8) into `ptr inttoptr (i16 8960 to ptr)` + 17)
    ; CHECK-NEXT: HuCMemcpy 8992, 8993, 5, 0 :: (load (s8) from `ptr inttoptr (i16 8960 to ptr)` + 32), (store (s8) into `ptr inttoptr (i16 8960 to ptr)` + 33)
    ; CHECK-NEXT: RTS implicit [[MV]](s16)
    %1:_(s16) = G_CONSTANT i16 8960
    %0:_(p0) = G_INTTOPTR %1:_(s16)
    %2:_(s8) = G_CONSTANT i8 0
    %3:_(s16) = G_CONSTANT i16 38
    %4:_(s16) = G_CONSTANT i16 0
    G_MEMSET %0:_(p0), %2:_(s8), %3:_(s16), 1 :: (store (s8) into `ptr inttoptr (i16 8960 to ptr)`, align 256); example.c:11:3
    RTS implicit %4
...
