# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -mtriple=mos -run-pass=mos-lower-select -verify-machineinstrs -o - %s | FileCheck %s
---
name: lower_select
legalized: true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.0.entry:
    ; CHECK-LABEL: name: lower_select
    ; CHECK: successors: %bb.1(0x40000000), %bb.2(0x40000000)
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[C:%[0-9]+]]:any(s8) = G_CONSTANT i8 1
    ; CHECK-NEXT: [[C1:%[0-9]+]]:any(s8) = G_CONSTANT i8 2
    ; CHECK-NEXT: [[C2:%[0-9]+]]:any(s1) = G_CONSTANT i1 false
    ; CHECK-NEXT: [[C3:%[0-9]+]]:any(s8) = G_CONSTANT i8 3
    ; CHECK-NEXT: G_BRCOND_IMM [[C2]](s1), %bb.1, 1
    ; CHECK-NEXT: G_BR %bb.2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: .1.entry:
    ; CHECK-NEXT: successors: %bb.3(0x80000000)
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: G_BR %bb.3
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: .2.entry:
    ; CHECK-NEXT: successors: %bb.3(0x80000000)
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: G_BR %bb.3
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: .3.entry:
    ; CHECK-NEXT: [[PHI:%[0-9]+]]:any(s8) = G_PHI [[C1]](s8), %bb.1, [[C]](s8), %bb.2
    ; CHECK-NEXT: [[PHI1:%[0-9]+]]:any(s8) = G_PHI [[C]](s8), %bb.1, [[C1]](s8), %bb.2
    ; CHECK-NEXT: RTS implicit [[PHI1]](s8), implicit [[C3]](s8), implicit [[PHI]](s8)
    %0:any(s8) = G_CONSTANT i8 1
    %1:any(s8) = G_CONSTANT i8 2
    %2:any(s1) = G_CONSTANT i1 false
    %3:any(s8) = G_SELECT %2, %0, %1
    %4:any(s8) = G_CONSTANT i8 3
    %5:any(s8) = G_SELECT %2, %1, %0
    RTS implicit %3, implicit %4, implicit %5
...
---
name: lower_select_around_call
legalized: true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.0.entry:
    ; CHECK-LABEL: name: lower_select_around_call
    ; CHECK: successors: %bb.1(0x40000000), %bb.2(0x40000000)
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[C:%[0-9]+]]:any(s1) = G_CONSTANT i1 false
    ; CHECK-NEXT: G_BRCOND_IMM [[C]](s1), %bb.1, 1
    ; CHECK-NEXT: G_BR %bb.2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: .1.entry:
    ; CHECK-NEXT: successors: %bb.3(0x80000000)
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[C1:%[0-9]+]]:any(s8) = G_CONSTANT i8 1
    ; CHECK-NEXT: G_BR %bb.3
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: .2.entry:
    ; CHECK-NEXT: successors: %bb.3(0x80000000)
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[C2:%[0-9]+]]:any(s8) = G_CONSTANT i8 2
    ; CHECK-NEXT: G_BR %bb.3
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: .3.entry:
    ; CHECK-NEXT: [[PHI:%[0-9]+]]:any(s8) = G_PHI [[C1]](s8), %bb.1, [[C2]](s8), %bb.2
    ; CHECK-NEXT: ADJCALLSTACKDOWN 0, 0, implicit-def $rs0, implicit $rs0
    ; CHECK-NEXT: [[C3:%[0-9]+]]:any(s8) = G_CONSTANT i8 0
    ; CHECK-NEXT: $a = COPY [[C3]](s8)
    ; CHECK-NEXT: [[C4:%[0-9]+]]:any(s8) = G_CONSTANT i8 3
    ; CHECK-NEXT: $y = COPY [[PHI]](s8)
    ; CHECK-NEXT: JSR &fn
    ; CHECK-NEXT: ADJCALLSTACKUP 0, 0, implicit-def $rs0, implicit $rs0
    ; CHECK-NEXT: RTS
    ADJCALLSTACKDOWN 0, 0, implicit-def $rs0, implicit $rs0
    %0:any(s8) = G_CONSTANT i8 0
    $a = COPY %0
    %1:any(s8) = G_CONSTANT i8 1
    %2:any(s8) = G_CONSTANT i8 2
    %3:any(s8) = G_CONSTANT i8 3
    %4:any(s1) = G_CONSTANT i1 false
    %5:any(s8) = G_SELECT %4, %1, %2
    $y = COPY %5
    JSR &fn
    ADJCALLSTACKUP 0, 0, implicit-def $rs0, implicit $rs0
    RTS
...
---
name: sink_nested_select
legalized: true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.0.entry:
    ; CHECK-LABEL: name: sink_nested_select
    ; CHECK: successors: %bb.1(0x40000000), %bb.2(0x40000000)
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[C:%[0-9]+]]:any(s8) = G_CONSTANT i8 1
    ; CHECK-NEXT: [[C1:%[0-9]+]]:any(s1) = G_CONSTANT i1 true
    ; CHECK-NEXT: G_BRCOND_IMM [[C1]](s1), %bb.1, 1
    ; CHECK-NEXT: G_BR %bb.2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: .1.entry:
    ; CHECK-NEXT: successors: %bb.3(0x80000000)
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: G_BR %bb.3
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: .2.entry:
    ; CHECK-NEXT: successors: %bb.4(0x40000000), %bb.5(0x40000000)
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[C2:%[0-9]+]]:any(s1) = G_CONSTANT i1 false
    ; CHECK-NEXT: G_BRCOND_IMM [[C2]](s1), %bb.4, 1
    ; CHECK-NEXT: G_BR %bb.5
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: .4.entry:
    ; CHECK-NEXT: successors: %bb.6(0x80000000)
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: G_BR %bb.6
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: .5.entry:
    ; CHECK-NEXT: successors: %bb.6(0x80000000)
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[C3:%[0-9]+]]:any(s8) = G_CONSTANT i8 2
    ; CHECK-NEXT: G_BR %bb.6
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: .6.entry:
    ; CHECK-NEXT: successors: %bb.3(0x80000000)
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[PHI:%[0-9]+]]:any(s8) = G_PHI [[C]](s8), %bb.4, [[C3]](s8), %bb.5
    ; CHECK-NEXT: G_BR %bb.3
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: .3.entry:
    ; CHECK-NEXT: [[PHI1:%[0-9]+]]:any(s8) = G_PHI [[C]](s8), %bb.1, [[PHI]](s8), %bb.6
    ; CHECK-NEXT: RTS implicit [[PHI1]](s8)
    %0:any(s8) = G_CONSTANT i8 1
    %1:any(s8) = G_CONSTANT i8 2
    %2:any(s1) = G_CONSTANT i1 false
    %3:any(s8) = G_SELECT %2, %0, %1
    %4:any(s1) = G_CONSTANT i1 true
    %5:any(s8) = G_SELECT %4, %0, %3
    RTS implicit %5
...
---
name: tail_duplicate_brcond_imm
legalized: true
regBankSelected: true
tracksRegLiveness: true
body: |
  ; CHECK-LABEL: name: tail_duplicate_brcond_imm
  ; CHECK: bb.0.entry:
  ; CHECK-NEXT:   successors: %bb.1(0x40000000), %bb.2(0x40000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[C:%[0-9]+]]:any(s1) = G_CONSTANT i1 false
  ; CHECK-NEXT:   [[C1:%[0-9]+]]:any(s1) = G_CONSTANT i1 true
  ; CHECK-NEXT:   G_BRCOND_IMM [[C]](s1), %bb.1, 1
  ; CHECK-NEXT:   G_BR %bb.2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.4(0x40000000), %bb.5(0x40000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   G_BRCOND_IMM [[C]](s1), %bb.4, 1
  ; CHECK-NEXT:   G_BR %bb.5
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.4:
  ; CHECK-NEXT:   successors: %bb.6(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   G_BR %bb.6
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.5:
  ; CHECK-NEXT:   successors: %bb.3(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   G_BR %bb.3
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.6:
  ; CHECK-NEXT:   successors: %bb.2(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   successors: %bb.3(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.3:
  ; CHECK-NEXT:   [[PHI:%[0-9]+]]:any(s1) = G_PHI [[C1]](s1), %bb.2, [[C]](s1), %bb.5
  ; CHECK-NEXT:   RTS implicit [[PHI]](s1)
  bb.0.entry:
    %0:any(s1) = G_CONSTANT i1 false
    %1:any(s1) = G_CONSTANT i1 true
    G_BRCOND_IMM %0, %bb.1, 1
    G_BR %bb.2
  bb.1:
    %3:any(s1) = G_SELECT %0, %0, %1
    G_BRCOND_IMM %3, %bb.3, 1
  bb.2:
  bb.3:
    %4:any(s1) = G_PHI %0, %bb.1, %1, %bb.2
    RTS implicit %4
...
---
name: sink_brcond_imm
legalized: true
regBankSelected: true
tracksRegLiveness: true
body: |
  ; CHECK-LABEL: name: sink_brcond_imm
  ; CHECK: bb.0.entry:
  ; CHECK-NEXT:   successors: %bb.1(0x40000000), %bb.2(0x40000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[C:%[0-9]+]]:any(s1) = G_CONSTANT i1 false
  ; CHECK-NEXT:   [[C1:%[0-9]+]]:any(s1) = G_CONSTANT i1 true
  ; CHECK-NEXT:   G_BRCOND_IMM [[C]](s1), %bb.1, 1
  ; CHECK-NEXT:   G_BR %bb.2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.4(0x40000000), %bb.5(0x40000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[C2:%[0-9]+]]:any(s8) = G_CONSTANT i8 42
  ; CHECK-NEXT:   G_BRCOND_IMM [[C]](s1), %bb.4, 1
  ; CHECK-NEXT:   G_BR %bb.5
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.4:
  ; CHECK-NEXT:   successors: %bb.6(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   G_BR %bb.6
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.5:
  ; CHECK-NEXT:   successors: %bb.3(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   G_BR %bb.3
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.6:
  ; CHECK-NEXT:   successors: %bb.2(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   successors: %bb.3(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.3:
  ; CHECK-NEXT:   [[PHI:%[0-9]+]]:any(s1) = G_PHI [[C1]](s1), %bb.2, [[C]](s1), %bb.5
  ; CHECK-NEXT:   RTS implicit [[PHI]](s1)
  bb.0.entry:
    %0:any(s1) = G_CONSTANT i1 false
    %1:any(s1) = G_CONSTANT i1 true
    G_BRCOND_IMM %0, %bb.1, 1
    G_BR %bb.2
  bb.1:
    %3:any(s1) = G_SELECT %0, %0, %1
    %5:any(s8) = G_CONSTANT i8 42
    G_BRCOND_IMM %3, %bb.3, 1
  bb.2:
  bb.3:
    %4:any(s1) = G_PHI %0, %bb.1, %1, %bb.2
    RTS implicit %4
...
