; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -verify-machineinstrs -O2 < %s | FileCheck %s
target triple = "mos"

declare void @foo()

; A CSR shouldn't be used over static stack to save a byte only used once across a call.

define i8 @norecurse(i8 %a) optsize norecurse {
; CHECK-LABEL: norecurse:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    sta .Lnorecurse_sstk ; 1-byte Folded Spill
; CHECK-NEXT:    jsr foo
; CHECK-NEXT:    lda .Lnorecurse_sstk ; 1-byte Folded Reload
; CHECK-NEXT:    rts
  call void @foo()
  ret i8 %a
}

; A CSR should be used over dynamic stack in the same scenario.

define i8 @mayrecurse(i8 %a) optsize {
; CHECK-LABEL: mayrecurse:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    sta __rc16
; CHECK-NEXT:    lda __rc20
; CHECK-NEXT:    pha
; CHECK-NEXT:    lda __rc16
; CHECK-NEXT:    sta __rc20
; CHECK-NEXT:    jsr foo
; CHECK-NEXT:    lda __rc20
; CHECK-NEXT:    sta __rc16
; CHECK-NEXT:    pla
; CHECK-NEXT:    sta __rc20
; CHECK-NEXT:    lda __rc16
; CHECK-NEXT:    rts
  call void @foo()
  ret i8 %a
}
