# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -mtriple=mos -run-pass=postrapseudos -verify-machineinstrs -o - %s | FileCheck %s
---
name: ldaidx
body: |
  bb.0.entry:
    liveins: $x
    ; CHECK-LABEL: name: ldaidx
    ; CHECK: $a = LDAIdx 1234, $x, implicit-def $nz
    $a = LDIdx 1234, $x, implicit-def $nz
...
---
name: ldxidx_y
body: |
  bb.0.entry:
    liveins: $y
    ; CHECK-LABEL: name: ldxidx_y
    ; CHECK: $x = LDXIdx 1234, $y, implicit-def $nz
    $x = LDIdx 1234, $y, implicit-def $nz
...
---
name: ldxidx_x
body: |
  bb.0.entry:
    liveins: $x
    ; CHECK-LABEL: name: ldxidx_x
    ; CHECK: PH $a
    ; CHECK: $a = LDAIdx 1234, $x, implicit-def $nz
    ; CHECK: $x = TA $a, implicit-def $nz
    ; CHECK: $a = PL implicit-def $nz
    ; CHECK: $c = CMPImm $a, 0, implicit-def $nz
    $x = LDIdx 1234, $x, implicit-def $nz
    $c = CMPImm $a, 0, implicit-def $nz
...
---
name: ldyidx_x
body: |
  bb.0.entry:
    liveins: $x
    ; CHECK-LABEL: name: ldyidx_x
    ; CHECK: $y = LDYIdx 1234, $x, implicit-def $nz
    $y = LDIdx 1234, $x, implicit-def $nz
...
---
name: ldcimm
body: |
  bb.0.entry:
    ; CHECK-LABEL: name: ldcimm
    ; CHECK: $c = LDCImm 1, implicit-def $nz
    $c = LDImm1 1, implicit-def $nz
...
