# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -mtriple=mos -mcpu=mosspc700 -run-pass=postrapseudos -verify-machineinstrs -o - %s | FileCheck %s
---
name: set_v
body: |
  bb.0.entry:
    ; CHECK-LABEL: name: set_v
    ; CHECK: PH $p
    ; CHECK-NEXT: [[PL:%[0-9]+]]:ac = PL
    ; CHECK-NEXT: [[PL:%[0-9]+]]:ac = ORAImm [[PL]], 64
    ; CHECK-NEXT: PH killed [[PL]]
    ; CHECK-NEXT: $p = PL
    $v = LDImm1 -1
...
---
name: ldxidx_y
body: |
  bb.0.entry:
    liveins: $y
    ; CHECK-LABEL: name: ldxidx_y
    ; CHECK: liveins: $y
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[LDAAbsIdx:%[0-9]+]]:ac = LDAAbsIdx 1234, $y
    ; CHECK-NEXT: $x = TA [[LDAAbsIdx]]
    ; CHECK-NEXT: $c = CMPImm $a, 0
    $x = LDAbsIdx 1234, $y
    $c = CMPImm $a, 0
...
---
name: ldyidx_x
body: |
  bb.0.entry:
    liveins: $x
    ; CHECK-LABEL: name: ldyidx_x
    ; CHECK: liveins: $x
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[LDAAbsIdx:%[0-9]+]]:ac = LDAAbsIdx 1234, $x
    ; CHECK-NEXT: $y = TA [[LDAAbsIdx]]
    ; CHECK-NEXT: $c = CMPImm $a, 0
    $y = LDAbsIdx 1234, $x
    $c = CMPImm $a, 0
...
---
name: ldimm16
body: |
  bb.0.entry:
    ; CHECK-LABEL: name: ldimm16
    ; CHECK: $rc2 = LDImm 210
    ; CHECK-NEXT: $rc3 = LDImm 4
    $rs1 = LDImm16SPC700 1234
...
