; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -verify-machineinstrs -O2 < %s | FileCheck %s

; When calling a preserve_most function, the caller can keep values in imaginary
; registers across the call without spilling, since the callee preserves all of
; them. This is the key benefit of the convention.

target datalayout = "e-m:e-p:16:8-p1:8:8-i16:8-i32:8-i64:8-f32:8-f64:8-a:8-Fi8-n8"
target triple = "mos"

declare preserve_mostcc void @pm_callee()
declare void @std_callee()

; The value is held in __rc2 across the call with no save/restore around it.
define i8 @call_pm_no_spill(i8 %a) {
; CHECK-LABEL: call_pm_no_spill:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    sta __rc2
; CHECK-NEXT:    jsr pm_callee
; CHECK-NEXT:    inc __rc2
; CHECK-NEXT:    lda __rc2
; CHECK-NEXT:    rts
entry:
  call preserve_mostcc void @pm_callee()
  %r = add i8 %a, 1
  ret i8 %r
}

; In contrast, a standard-CC callee only preserves __rc20-__rc31, so the value
; is kept in one of those, and that register must be saved and restored since
; it is callee-saved in this function.
define i8 @call_std_keep_in_csr(i8 %a) {
; CHECK-LABEL: call_std_keep_in_csr:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    sta __rc16
; CHECK-NEXT:    lda __rc20
; CHECK-NEXT:    pha
; CHECK-NEXT:    lda __rc16
; CHECK-NEXT:    sta __rc20
; CHECK-NEXT:    jsr std_callee
; CHECK-NEXT:    inc __rc20
; CHECK-NEXT:    lda __rc20
; CHECK-NEXT:    sta __rc16
; CHECK-NEXT:    pla
; CHECK-NEXT:    sta __rc20
; CHECK-NEXT:    lda __rc16
; CHECK-NEXT:    rts
entry:
  call void @std_callee()
  %r = add i8 %a, 1
  ret i8 %r
}

; The motivating case: an interrupt handler that calls a preserve_most function
; only needs to save A, X, Y and the registers the callee may clobber (__rc16
; and __rc17), not the whole imaginary register file.
define void @isr_calls_pm() "interrupt" {
; CHECK-LABEL: isr_calls_pm:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    cld
; CHECK-NEXT:    pha
; CHECK-NEXT:    clc
; CHECK-NEXT:    lda __rc0
; CHECK-NEXT:    adc #255
; CHECK-NEXT:    sta __rc0
; CHECK-NEXT:    lda __rc1
; CHECK-NEXT:    adc #254
; CHECK-NEXT:    sta __rc1
; CHECK-NEXT:    pla
; CHECK-NEXT:    pha
; CHECK-NEXT:    txa
; CHECK-NEXT:    pha
; CHECK-NEXT:    tya
; CHECK-NEXT:    pha
; CHECK-NEXT:    lda __rc16
; CHECK-NEXT:    pha
; CHECK-NEXT:    lda __rc17
; CHECK-NEXT:    ldy #0
; CHECK-NEXT:    sta (__rc0),y ; 1-byte Folded Spill
; CHECK-NEXT:    jsr pm_callee
; CHECK-NEXT:    ldy #0
; CHECK-NEXT:    lda (__rc0),y ; 1-byte Folded Reload
; CHECK-NEXT:    sta __rc17
; CHECK-NEXT:    pla
; CHECK-NEXT:    sta __rc16
; CHECK-NEXT:    pla
; CHECK-NEXT:    tay
; CHECK-NEXT:    pla
; CHECK-NEXT:    tax
; CHECK-NEXT:    pla
; CHECK-NEXT:    pha
; CHECK-NEXT:    clc
; CHECK-NEXT:    lda __rc0
; CHECK-NEXT:    adc #1
; CHECK-NEXT:    sta __rc0
; CHECK-NEXT:    lda __rc1
; CHECK-NEXT:    adc #1
; CHECK-NEXT:    sta __rc1
; CHECK-NEXT:    pla
; CHECK-NEXT:    rti
entry:
  call preserve_mostcc void @pm_callee()
  ret void
}

; In contrast, an interrupt handler that calls a C function must save every
; imaginary register that function may clobber.
define void @isr_calls_std() "interrupt" {
; CHECK-LABEL: isr_calls_std:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    cld
; CHECK-NEXT:    pha
; CHECK-NEXT:    clc
; CHECK-NEXT:    lda __rc0
; CHECK-NEXT:    adc #239
; CHECK-NEXT:    sta __rc0
; CHECK-NEXT:    lda __rc1
; CHECK-NEXT:    adc #254
; CHECK-NEXT:    sta __rc1
; CHECK-NEXT:    pla
; CHECK-NEXT:    pha
; CHECK-NEXT:    txa
; CHECK-NEXT:    pha
; CHECK-NEXT:    tya
; CHECK-NEXT:    pha
; CHECK-NEXT:    lda __rc2
; CHECK-NEXT:    pha
; CHECK-NEXT:    lda __rc3
; CHECK-NEXT:    ldy #16
; CHECK-NEXT:    sta (__rc0),y ; 1-byte Folded Spill
; CHECK-NEXT:    lda __rc4
; CHECK-NEXT:    dey
; CHECK-NEXT:    sta (__rc0),y ; 1-byte Folded Spill
; CHECK-NEXT:    lda __rc5
; CHECK-NEXT:    dey
; CHECK-NEXT:    sta (__rc0),y ; 1-byte Folded Spill
; CHECK-NEXT:    lda __rc6
; CHECK-NEXT:    dey
; CHECK-NEXT:    sta (__rc0),y ; 1-byte Folded Spill
; CHECK-NEXT:    lda __rc7
; CHECK-NEXT:    dey
; CHECK-NEXT:    sta (__rc0),y ; 1-byte Folded Spill
; CHECK-NEXT:    lda __rc8
; CHECK-NEXT:    dey
; CHECK-NEXT:    sta (__rc0),y ; 1-byte Folded Spill
; CHECK-NEXT:    lda __rc9
; CHECK-NEXT:    dey
; CHECK-NEXT:    sta (__rc0),y ; 1-byte Folded Spill
; CHECK-NEXT:    lda __rc10
; CHECK-NEXT:    dey
; CHECK-NEXT:    sta (__rc0),y ; 1-byte Folded Spill
; CHECK-NEXT:    lda __rc11
; CHECK-NEXT:    dey
; CHECK-NEXT:    sta (__rc0),y ; 1-byte Folded Spill
; CHECK-NEXT:    lda __rc12
; CHECK-NEXT:    dey
; CHECK-NEXT:    sta (__rc0),y ; 1-byte Folded Spill
; CHECK-NEXT:    lda __rc13
; CHECK-NEXT:    dey
; CHECK-NEXT:    sta (__rc0),y ; 1-byte Folded Spill
; CHECK-NEXT:    lda __rc14
; CHECK-NEXT:    dey
; CHECK-NEXT:    sta (__rc0),y ; 1-byte Folded Spill
; CHECK-NEXT:    lda __rc15
; CHECK-NEXT:    dey
; CHECK-NEXT:    sta (__rc0),y ; 1-byte Folded Spill
; CHECK-NEXT:    lda __rc16
; CHECK-NEXT:    dey
; CHECK-NEXT:    sta (__rc0),y ; 1-byte Folded Spill
; CHECK-NEXT:    lda __rc17
; CHECK-NEXT:    dey
; CHECK-NEXT:    sta (__rc0),y ; 1-byte Folded Spill
; CHECK-NEXT:    lda __rc18
; CHECK-NEXT:    dey
; CHECK-NEXT:    sta (__rc0),y ; 1-byte Folded Spill
; CHECK-NEXT:    lda __rc19
; CHECK-NEXT:    dey
; CHECK-NEXT:    sta (__rc0),y ; 1-byte Folded Spill
; CHECK-NEXT:    jsr std_callee
; CHECK-NEXT:    ldy #0
; CHECK-NEXT:    lda (__rc0),y ; 1-byte Folded Reload
; CHECK-NEXT:    sta __rc19
; CHECK-NEXT:    iny
; CHECK-NEXT:    lda (__rc0),y ; 1-byte Folded Reload
; CHECK-NEXT:    sta __rc18
; CHECK-NEXT:    iny
; CHECK-NEXT:    lda (__rc0),y ; 1-byte Folded Reload
; CHECK-NEXT:    sta __rc17
; CHECK-NEXT:    iny
; CHECK-NEXT:    lda (__rc0),y ; 1-byte Folded Reload
; CHECK-NEXT:    sta __rc16
; CHECK-NEXT:    iny
; CHECK-NEXT:    lda (__rc0),y ; 1-byte Folded Reload
; CHECK-NEXT:    sta __rc15
; CHECK-NEXT:    iny
; CHECK-NEXT:    lda (__rc0),y ; 1-byte Folded Reload
; CHECK-NEXT:    sta __rc14
; CHECK-NEXT:    iny
; CHECK-NEXT:    lda (__rc0),y ; 1-byte Folded Reload
; CHECK-NEXT:    sta __rc13
; CHECK-NEXT:    iny
; CHECK-NEXT:    lda (__rc0),y ; 1-byte Folded Reload
; CHECK-NEXT:    sta __rc12
; CHECK-NEXT:    iny
; CHECK-NEXT:    lda (__rc0),y ; 1-byte Folded Reload
; CHECK-NEXT:    sta __rc11
; CHECK-NEXT:    iny
; CHECK-NEXT:    lda (__rc0),y ; 1-byte Folded Reload
; CHECK-NEXT:    sta __rc10
; CHECK-NEXT:    iny
; CHECK-NEXT:    lda (__rc0),y ; 1-byte Folded Reload
; CHECK-NEXT:    sta __rc9
; CHECK-NEXT:    iny
; CHECK-NEXT:    lda (__rc0),y ; 1-byte Folded Reload
; CHECK-NEXT:    sta __rc8
; CHECK-NEXT:    iny
; CHECK-NEXT:    lda (__rc0),y ; 1-byte Folded Reload
; CHECK-NEXT:    sta __rc7
; CHECK-NEXT:    iny
; CHECK-NEXT:    lda (__rc0),y ; 1-byte Folded Reload
; CHECK-NEXT:    sta __rc6
; CHECK-NEXT:    iny
; CHECK-NEXT:    lda (__rc0),y ; 1-byte Folded Reload
; CHECK-NEXT:    sta __rc5
; CHECK-NEXT:    iny
; CHECK-NEXT:    lda (__rc0),y ; 1-byte Folded Reload
; CHECK-NEXT:    sta __rc4
; CHECK-NEXT:    iny
; CHECK-NEXT:    lda (__rc0),y ; 1-byte Folded Reload
; CHECK-NEXT:    sta __rc3
; CHECK-NEXT:    pla
; CHECK-NEXT:    sta __rc2
; CHECK-NEXT:    pla
; CHECK-NEXT:    tay
; CHECK-NEXT:    pla
; CHECK-NEXT:    tax
; CHECK-NEXT:    pla
; CHECK-NEXT:    pha
; CHECK-NEXT:    clc
; CHECK-NEXT:    lda __rc0
; CHECK-NEXT:    adc #17
; CHECK-NEXT:    sta __rc0
; CHECK-NEXT:    lda __rc1
; CHECK-NEXT:    adc #1
; CHECK-NEXT:    sta __rc1
; CHECK-NEXT:    pla
; CHECK-NEXT:    rti
entry:
  call void @std_callee()
  ret void
}
