; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s | FileCheck %s -check-prefix=NMOS
; RUN: llc -mcpu=mos65c02 < %s | FileCheck %s -check-prefix=CMOS

target datalayout = "e-p:16:8:8-p1:8:8-i16:8:8-i32:8:8-i64:8:8-f32:8:8-f64:8:8-a:8:8-Fi8-n8"
target triple = "mos"

; Function Attrs: nounwind
define void @print_int(i8 zeroext %x) local_unnamed_addr #0 {
; NMOS-LABEL: print_int:
; NMOS:       ; %bb.0: ; %entry
; NMOS-NEXT:    cmp #10
; NMOS-NEXT:    bcs .LBB0_1
; NMOS-NEXT:    jmp .LBB0_2
; NMOS-NEXT:  .LBB0_1: ; %if.end.preheader
; NMOS-NEXT:    sta __rc16
; NMOS-NEXT:    clc
; NMOS-NEXT:    lda __rc0
; NMOS-NEXT:    adc #255
; NMOS-NEXT:    sta __rc0
; NMOS-NEXT:    lda __rc1
; NMOS-NEXT:    adc #255
; NMOS-NEXT:    sta __rc1
; NMOS-NEXT:    lda __rc20
; NMOS-NEXT:    pha
; NMOS-NEXT:    lda __rc21
; NMOS-NEXT:    pha
; NMOS-NEXT:    lda __rc16
; NMOS-NEXT:    clc
; NMOS-NEXT:    ldx __rc0
; NMOS-NEXT:    stx __rc20
; NMOS-NEXT:    ldx __rc1
; NMOS-NEXT:    stx __rc21
; NMOS-NEXT:    ldx #10
; NMOS-NEXT:    ldy __rc20
; NMOS-NEXT:    sty __rc2
; NMOS-NEXT:    ldy __rc21
; NMOS-NEXT:    sty __rc3
; NMOS-NEXT:    jsr __udivmodqi4
; NMOS-NEXT:    tax
; NMOS-NEXT:    ldy #0
; NMOS-NEXT:    lda (__rc20),y
; NMOS-NEXT:    sta __rc20
; NMOS-NEXT:    txa
; NMOS-NEXT:    jsr print_int
; NMOS-NEXT:    lda __rc20
; NMOS-NEXT:    sta __rc16
; NMOS-NEXT:    pla
; NMOS-NEXT:    sta __rc21
; NMOS-NEXT:    pla
; NMOS-NEXT:    sta __rc20
; NMOS-NEXT:    clc
; NMOS-NEXT:    lda __rc0
; NMOS-NEXT:    adc #1
; NMOS-NEXT:    sta __rc0
; NMOS-NEXT:    lda __rc1
; NMOS-NEXT:    adc #0
; NMOS-NEXT:    sta __rc1
; NMOS-NEXT:    lda __rc16
; NMOS-NEXT:  .LBB0_2: ; %if.then
; NMOS-NEXT:    ora #48
; NMOS-NEXT:    ;APP
; NMOS-NEXT:    jsr 65490
; NMOS-NEXT:    ;NO_APP
; NMOS-NEXT:    rts
;
; CMOS-LABEL: print_int:
; CMOS:       ; %bb.0: ; %entry
; CMOS-NEXT:    cmp #10
; CMOS-NEXT:    bcs .LBB0_1
; CMOS-NEXT:  ; %bb.3: ; %entry
; CMOS-NEXT:    jmp .LBB0_2
; CMOS-NEXT:  .LBB0_1: ; %if.end.preheader
; CMOS-NEXT:    pha
; CMOS-NEXT:    clc
; CMOS-NEXT:    lda __rc0
; CMOS-NEXT:    adc #255
; CMOS-NEXT:    sta __rc0
; CMOS-NEXT:    lda __rc1
; CMOS-NEXT:    adc #255
; CMOS-NEXT:    sta __rc1
; CMOS-NEXT:    pla
; CMOS-NEXT:    ldx __rc20
; CMOS-NEXT:    phx
; CMOS-NEXT:    ldx __rc21
; CMOS-NEXT:    phx
; CMOS-NEXT:    clc
; CMOS-NEXT:    ldx __rc0
; CMOS-NEXT:    stx __rc20
; CMOS-NEXT:    ldx __rc1
; CMOS-NEXT:    stx __rc21
; CMOS-NEXT:    ldx #10
; CMOS-NEXT:    ldy __rc20
; CMOS-NEXT:    sty __rc2
; CMOS-NEXT:    ldy __rc21
; CMOS-NEXT:    sty __rc3
; CMOS-NEXT:    jsr __udivmodqi4
; CMOS-NEXT:    tax
; CMOS-NEXT:    lda (__rc20)
; CMOS-NEXT:    sta __rc20
; CMOS-NEXT:    txa
; CMOS-NEXT:    jsr print_int
; CMOS-NEXT:    lda __rc20
; CMOS-NEXT:    sta __rc16
; CMOS-NEXT:    plx
; CMOS-NEXT:    stx __rc21
; CMOS-NEXT:    plx
; CMOS-NEXT:    stx __rc20
; CMOS-NEXT:    clc
; CMOS-NEXT:    lda __rc0
; CMOS-NEXT:    adc #1
; CMOS-NEXT:    sta __rc0
; CMOS-NEXT:    lda __rc1
; CMOS-NEXT:    adc #0
; CMOS-NEXT:    sta __rc1
; CMOS-NEXT:    lda __rc16
; CMOS-NEXT:  .LBB0_2: ; %if.then
; CMOS-NEXT:    ora #48
; CMOS-NEXT:    ;APP
; CMOS-NEXT:    jsr 65490
; CMOS-NEXT:    ;NO_APP
; CMOS-NEXT:    rts
entry:
  %cmp12 = icmp ult i8 %x, 10
  br i1 %cmp12, label %if.then, label %if.end.preheader

if.end.preheader:                                 ; preds = %entry
  %div = udiv i8 %x, 10
  tail call void @print_int(i8 zeroext %div)
  %rem = urem i8 %x, 10
  br label %if.then

if.then:                                          ; preds = %if.end.preheader, %entry
  %x.tr.lcssa = phi i8 [ %x, %entry ], [ %rem, %if.end.preheader ]
  %add = add nuw nsw i8 %x.tr.lcssa, 48
  %0 = tail call i8 asm sideeffect "JSR\09$$FFD2", "=a,0"(i8 %add) #1, !srcloc !2
  ret void
}

attributes #0 = { nounwind "disable-tail-calls"="false" "frame-pointer"="all" "less-precise-fpmad"="false" "min-legal-vector-width"="0" "no-infs-fp-math"="false" "no-jump-tables"="false" "no-nans-fp-math"="false" "no-signed-zeros-fp-math"="false" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "unsafe-fp-math"="false" "use-soft-float"="false" }
attributes #1 = { nounwind }

!llvm.module.flags = !{!0}
!llvm.ident = !{!1}

!0 = !{i32 1, !"wchar_size", i32 4}
!1 = !{!"clang version 12.0.0 (git@github.com:mysterymath/clang6502.git 51e3618d42bc67892d46290a51ea57ea7e127aa6)"}
!2 = !{i32 70}
