# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -mtriple=mos -run-pass=greedy -verify-machineinstrs -o - %s | FileCheck %s
---
name: remat_ldimm
legalized: true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.0.entry:
    liveins: $a
    ; CHECK-LABEL: name: remat_ldimm
    ; CHECK: liveins: $a
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: JSR &fn, mos_csr
    ; CHECK-NEXT: [[LDImm:%[0-9]+]]:gpr = LDImm 42
    ; CHECK-NEXT: $a = COPY [[LDImm]]
    ; CHECK-NEXT: RTS implicit $a
    %0:gpr = LDImm 42
    JSR &fn, mos_csr
    $a = COPY %0
    RTS implicit $a
...
---
name: spill_y
legalized: true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.0.entry:
    liveins: $y
    ; CHECK-LABEL: name: spill_y
    ; CHECK: liveins: $y
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: dead early-clobber %1:imag16 = STStk $y, %stack.0, 0 :: (store (s8) into %stack.0)
    ; CHECK-NEXT: JSR &fn, mos_csr
    ; CHECK-NEXT: $y, dead early-clobber %2:imag16 = LDStk %stack.0, 0 :: (load (s8) from %stack.0)
    ; CHECK-NEXT: RTS implicit $y
    %0:yc = COPY $y
    JSR &fn, mos_csr
    $y = COPY %0
    RTS implicit $y
...
