# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -mtriple=mos -mcpu=mos65c02 -run-pass=scavenger-test -verify-machineinstrs -o - %s | FileCheck %s
---
name: spill_y
body: |
  bb.0.entry:
    liveins: $a, $x, $y
    ; CHECK-LABEL: name: spill_y
    ; CHECK: PH $y
    ; CHECK-NEXT: dead $y = LDImm 42
    ; CHECK-NEXT: $y = PL
    ; CHECK-NEXT: RTS implicit $a, implicit $x, implicit $y
    %0:yc = LDImm 42
    RTS implicit $a, implicit $x, implicit $y
...
---
name: spill_y_around_phy
body: |
  bb.0.entry:
    liveins: $a, $x, $y
    ; CHECK-LABEL: name: spill_y_around_phy
    ; CHECK: $rc17 = STImag8 $y
    ; CHECK-NEXT: $y = LDImm 42
    ; CHECK-NEXT: PH killed $y
    ; CHECK-NEXT: $y = LDImag8 $rc17
    ; CHECK-NEXT: RTS implicit $a, implicit $x, implicit $y
    %0:yc = LDImm 42
    PH %0
    RTS implicit $a, implicit $x, implicit $y
...
---
name: spill_y_around_ply
body: |
  bb.0.entry:
    liveins: $a, $x, $y
    ; CHECK-LABEL: name: spill_y_around_ply
    ; CHECK: $rc17 = STImag8 $y
    ; CHECK-NEXT: dead $y = PL
    ; CHECK-NEXT: $y = LDImag8 $rc17
    ; CHECK-NEXT: RTS implicit $a, implicit $x, implicit $y
    %0:yc = PL
    RTS implicit $a, implicit $x, implicit $y
...
