; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -verify-machineinstrs < %s | FileCheck %s

target datalayout = "e-m:e-p:16:8-p1:8:8-i16:8-i32:8-i64:8-f32:8-f64:8-a:8-Fi8-n8"
target triple = "mos"

@zeropage_i8 = external global i8, section ".zeropage", align 1

define void @main() {
; CHECK-LABEL: main:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    ldx #0
; CHECK-NEXT:    stx mos8(zeropage_i8)
; CHECK-NEXT:    rts
entry:
  store i8 0, i8* @zeropage_i8, align 1
  ret void
}

@zeropage_i8_array = global [2 x i8] c"**", section ".zeropage", align 1

define void @main_gep() {
; CHECK-LABEL: main_gep:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    ldx #0
; CHECK-NEXT:    stx mos8(zeropage_i8_array+1)
; CHECK-NEXT:    rts
entry:
  %arrayidx = getelementptr inbounds [2 x i8], [2 x i8]* @zeropage_i8_array, i16 0, i16 1
  store i8 0, i8* %arrayidx, align 1
  ret void
}
