; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -verify-machineinstrs -O2 --filetype=asm -zp-avail=224 < %s | FileCheck %s

target datalayout = "e-m:e-p:16:8-p1:8:8-i16:8-i32:8-i64:8-f32:8-f64:8-a:8-Fi8-n8"
target triple = "mos-sim"

@c = dso_local global [224 x i8] zeroinitializer, section ".zp", align 1
@llvm.compiler.used = appending global [1 x ptr] [ptr @c], section "llvm.metadata"

@global = global i8 0, align 1
@global_noinit = global i8 undef, align 1

define i64 @foo(i64 %live_across_call) norecurse {
; CHECK-LABEL: foo:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    sta __rc16
; CHECK-NEXT:    lda __rc20
; CHECK-NEXT:    pha
; CHECK-NEXT:    lda __rc21
; CHECK-NEXT:    pha
; CHECK-NEXT:    lda __rc22
; CHECK-NEXT:    pha
; CHECK-NEXT:    lda __rc23
; CHECK-NEXT:    pha
; CHECK-NEXT:    lda __rc16
; CHECK-NEXT:    ldy __rc24
; CHECK-NEXT:    sty .Lfoo_sstk ; 1-byte Folded Spill
; CHECK-NEXT:    ldy __rc25
; CHECK-NEXT:    sty .Lfoo_sstk+1 ; 1-byte Folded Spill
; CHECK-NEXT:    ldy __rc26
; CHECK-NEXT:    sty .Lfoo_sstk+2 ; 1-byte Folded Spill
; CHECK-NEXT:    ldy __rc27
; CHECK-NEXT:    sty .Lfoo_sstk+3 ; 1-byte Folded Spill
; CHECK-NEXT:    sta __rc20
; CHECK-NEXT:    stx __rc21
; CHECK-NEXT:    ldx __rc2
; CHECK-NEXT:    stx __rc22
; CHECK-NEXT:    ldx __rc3
; CHECK-NEXT:    stx __rc23
; CHECK-NEXT:    ldx __rc4
; CHECK-NEXT:    stx __rc24
; CHECK-NEXT:    ldx __rc5
; CHECK-NEXT:    stx __rc25
; CHECK-NEXT:    ldx __rc6
; CHECK-NEXT:    stx __rc26
; CHECK-NEXT:    ldx __rc7
; CHECK-NEXT:    stx __rc27
; CHECK-NEXT:    ldx global
; CHECK-NEXT:    stx global_noinit
; CHECK-NEXT:    jsr bar
; CHECK-NEXT:    ldx __rc22
; CHECK-NEXT:    stx __rc2
; CHECK-NEXT:    ldx __rc23
; CHECK-NEXT:    stx __rc3
; CHECK-NEXT:    ldx __rc24
; CHECK-NEXT:    stx __rc4
; CHECK-NEXT:    ldx __rc25
; CHECK-NEXT:    stx __rc5
; CHECK-NEXT:    ldx __rc26
; CHECK-NEXT:    stx __rc6
; CHECK-NEXT:    ldx __rc27
; CHECK-NEXT:    stx __rc7
; CHECK-NEXT:    ldx __rc21
; CHECK-NEXT:    lda __rc20
; CHECK-NEXT:    sta __rc16
; CHECK-NEXT:    ldy .Lfoo_sstk+3 ; 1-byte Folded Reload
; CHECK-NEXT:    sty __rc27
; CHECK-NEXT:    ldy .Lfoo_sstk+2 ; 1-byte Folded Reload
; CHECK-NEXT:    sty __rc26
; CHECK-NEXT:    ldy .Lfoo_sstk+1 ; 1-byte Folded Reload
; CHECK-NEXT:    sty __rc25
; CHECK-NEXT:    ldy .Lfoo_sstk ; 1-byte Folded Reload
; CHECK-NEXT:    sty __rc24
; CHECK-NEXT:    pla
; CHECK-NEXT:    sta __rc23
; CHECK-NEXT:    pla
; CHECK-NEXT:    sta __rc22
; CHECK-NEXT:    pla
; CHECK-NEXT:    sta __rc21
; CHECK-NEXT:    pla
; CHECK-NEXT:    sta __rc20
; CHECK-NEXT:    lda __rc16
; CHECK-NEXT:    rts
entry:
  %0 = load i8, ptr @global, align 1
  store i8 %0, ptr @global_noinit, align 1
  call void @bar()
  ret i64 %live_across_call
}

define void @bar() norecurse noinline {
; CHECK-LABEL: bar:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    rts
entry:
  ret void
}
