; XFAIL: *
; RUN: llvm-mc -triple mos -mcpu=mos65ce02 --filetype=obj -I %S/Inputs -o=%t.obj %s
; RUN: llvm-objdump -d %t.obj | FileCheck %s

; PENDING #549 (https://github.com/llvm-mos/llvm-mos/pull/549): the 65CE02's
; 16-bit branch encoding (bcc relaxed to opcode 0x93 + a 2-byte operand) is a
; genuine hardware quirk -- unlike a normal 3-byte instruction (opcode + 3
; relative, the same rule brl uses on the 65816), the 65CE02 computes its
; 16-bit branch displacement relative to opcode + 2, one byte short of the
; instruction's own length. getRelativeMOSPCCorrection in MOSAsmBackend.cpp
; as of upstream tip 1f334fef02b5 does not know this: it applies the -2
; (opcode+3) correction to EVERY PCRel16 fixup, 65CE02 included, so this CPU
; currently gets an off-by-one-low displacement in the generated bytes. #549
; fixes exactly this (a per-CPU correction: -1 for 65CE02 PCRel16, -2
; elsewhere).
;
; The expected bytes below are hand-derived from the datasheet-correct
; opcode+2 rule, NOT from what today's buggy assembler emits (that failure
; mode -- copying buggy golden output into a test's expectations, which is
; exactly how llvm/test/MC/MOS/long-branches-65ce02.s missed this bug in the
; first place -- is what this file exists to avoid). displacement = target -
; (opcode_addr + 2), one less byte of "address_of_next_instruction" than the
; instruction's real 3-byte length would suggest.
;
; This file is therefore expected to FAIL today (XFAIL above): today's
; assembler is off by exactly one, low, on both rows (see the comments at
; each CHECK for the buggy value it currently produces instead). Once this
; branch is rebased onto #549's fix, delete the XFAIL line above -- these
; checks should then start passing (an unexpected XPASS is the signal that
; the rebase landed correctly and this file is ready to lose its gate).

; --- 16-bit bcc, forward ---
; N = 300 -> correct displacement = target - (opcode_addr + 2)
;          = (opcode_addr + 3 + 300) - (opcode_addr + 2) = 301 = 0x012d
;          -> bytes 2d 01 (little-endian)
; (today's buggy assembler emits 93 2c 01 -- displacement 300, one low)
  bcc fwd16                       ; CHECK: 93 2d 01 bcc
  .fill 300, 1, 0xea
fwd16:
  rts

; --- 16-bit bcc, backward ---
; N = 300 -> correct displacement = 0 - (opcode_addr + 2), opcode_addr = 300
;          = -(300 + 2) = -302 = 0xfed2 -> bytes d2 fe
; (today's buggy assembler emits 93 d1 fe -- displacement -303, one low)
back16:
  .fill 300, 1, 0xea
  bcc back16                      ; CHECK: 93 d2 fe bcc
