// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --version 2
// RUN: %clang_cc1 -triple mos -O2 -emit-llvm %s -o - | FileCheck %s

// Test MOSs inline assembly.

char c;
_Bool b;

// CHECK-LABEL: define dso_local void @test_a
// CHECK-SAME: () local_unnamed_addr #[[ATTR0:[0-9]+]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = load i8, ptr @c, align 1, !tbaa [[TBAA2:![0-9]+]]
// CHECK-NEXT:    tail call void asm sideeffect "", "a"(i8 [[TMP0]]) #[[ATTR2:[0-9]+]], !srcloc !5
// CHECK-NEXT:    ret void
//
void test_a() {
  asm volatile("" :: "a"(c));
}

// CHECK-LABEL: define dso_local void @test_x
// CHECK-SAME: () local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = load i8, ptr @c, align 1, !tbaa [[TBAA2]]
// CHECK-NEXT:    tail call void asm sideeffect "", "x"(i8 [[TMP0]]) #[[ATTR2]], !srcloc !6
// CHECK-NEXT:    ret void
//
void test_x() {
  asm volatile("" :: "x"(c));
}

// CHECK-LABEL: define dso_local void @test_y
// CHECK-SAME: () local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = load i8, ptr @c, align 1, !tbaa [[TBAA2]]
// CHECK-NEXT:    tail call void asm sideeffect "", "y"(i8 [[TMP0]]) #[[ATTR2]], !srcloc !7
// CHECK-NEXT:    ret void
//
void test_y() {
  asm volatile("" :: "y"(c));
}

// CHECK-LABEL: define dso_local void @test_R
// CHECK-SAME: () local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = load i8, ptr @c, align 1, !tbaa [[TBAA2]]
// CHECK-NEXT:    tail call void asm sideeffect "", "R"(i8 [[TMP0]]) #[[ATTR2]], !srcloc !8
// CHECK-NEXT:    ret void
//
void test_R() {
  asm volatile("" :: "R"(c));
}

// CHECK-LABEL: define dso_local void @test_d
// CHECK-SAME: () local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = load i8, ptr @c, align 1, !tbaa [[TBAA2]]
// CHECK-NEXT:    tail call void asm sideeffect "", "d"(i8 [[TMP0]]) #[[ATTR2]], !srcloc !9
// CHECK-NEXT:    ret void
//
void test_d() {
  asm volatile("" :: "d"(c));
}

// CHECK-LABEL: define dso_local void @test_c
// CHECK-SAME: () local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = load i8, ptr @b, align 1, !tbaa [[TBAA10:![0-9]+]], !range [[RNG12:![0-9]+]], !noundef !13
// CHECK-NEXT:    [[TOBOOL:%.*]] = icmp ne i8 [[TMP0]], 0
// CHECK-NEXT:    tail call void asm sideeffect "", "c"(i1 [[TOBOOL]]) #[[ATTR2]], !srcloc !14
// CHECK-NEXT:    ret void
//
void test_c() {
  asm volatile("" :: "c"(b));
}

// CHECK-LABEL: define dso_local void @test_v
// CHECK-SAME: () local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = load i8, ptr @b, align 1, !tbaa [[TBAA10]], !range [[RNG12]], !noundef !13
// CHECK-NEXT:    [[TOBOOL:%.*]] = icmp ne i8 [[TMP0]], 0
// CHECK-NEXT:    tail call void asm sideeffect "", "v"(i1 [[TOBOOL]]) #[[ATTR2]], !srcloc !15
// CHECK-NEXT:    ret void
//
void test_v() {
  asm volatile("" :: "v"(b));
}

// CHECK-LABEL: define dso_local void @test_clobber
// CHECK-SAME: () local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    tail call void asm sideeffect "", "~{a}"() #[[ATTR2]], !srcloc !16
// CHECK-NEXT:    tail call void asm sideeffect "", "~{x}"() #[[ATTR2]], !srcloc !17
// CHECK-NEXT:    tail call void asm sideeffect "", "~{y}"() #[[ATTR2]], !srcloc !18
// CHECK-NEXT:    tail call void asm sideeffect "", "~{c}"() #[[ATTR2]], !srcloc !19
// CHECK-NEXT:    tail call void asm sideeffect "", "~{v}"() #[[ATTR2]], !srcloc !20
// CHECK-NEXT:    tail call void asm sideeffect "", "~{p}"() #[[ATTR2]], !srcloc !21
// CHECK-NEXT:    tail call void asm sideeffect "", "~{rc0}"() #[[ATTR2]], !srcloc !22
// CHECK-NEXT:    tail call void asm sideeffect "", "~{rc31}"() #[[ATTR2]], !srcloc !23
// CHECK-NEXT:    tail call void asm sideeffect "", "~{rs0}"() #[[ATTR2]], !srcloc !24
// CHECK-NEXT:    tail call void asm sideeffect "", "~{rs15}"() #[[ATTR2]], !srcloc !25
// CHECK-NEXT:    ret void
//
void test_clobber() {
  asm volatile("" ::: "a");
  asm volatile("" ::: "x");
  asm volatile("" ::: "y");
  asm volatile("" ::: "c");
  asm volatile("" ::: "v");
  asm volatile("" ::: "p");
  asm volatile("" ::: "rc0");
  asm volatile("" ::: "rc31");
  asm volatile("" ::: "rs0");
  asm volatile("" ::: "rs15");
}

// CHECK-LABEL: define dso_local void @test_leaf_asm
// CHECK-SAME: () local_unnamed_addr #[[ATTR1:[0-9]+]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    tail call void asm sideeffect "", ""() #[[ATTR3:[0-9]+]], !srcloc !26
// CHECK-NEXT:    ret void
//
void test_leaf_asm() {
  __attribute__((leaf)) asm volatile("");
}
