// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --version 2
// RUN: %clang_cc1 -triple mos -O2 -emit-llvm %s -o - | FileCheck %s

// Test MOSs inline assembly.

char c;
_Bool b;

// CHECK-LABEL: define dso_local void @test_a
// CHECK-SAME: () local_unnamed_addr #[[ATTR0:[0-9]+]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = load i8, ptr @c, align 1, !tbaa [[TBAA2:![0-9]+]]
// CHECK-NEXT:    tail call void asm sideeffect "", "a"(i8 [[TMP0]]) #[[ATTR1:[0-9]+]], !srcloc [[META5:![0-9]+]]
// CHECK-NEXT:    ret void
//
void test_a() {
  asm volatile("" :: "a"(c));
}

// CHECK-LABEL: define dso_local void @test_x
// CHECK-SAME: () local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = load i8, ptr @c, align 1, !tbaa [[TBAA2]]
// CHECK-NEXT:    tail call void asm sideeffect "", "x"(i8 [[TMP0]]) #[[ATTR1]], !srcloc [[META6:![0-9]+]]
// CHECK-NEXT:    ret void
//
void test_x() {
  asm volatile("" :: "x"(c));
}

// CHECK-LABEL: define dso_local void @test_y
// CHECK-SAME: () local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = load i8, ptr @c, align 1, !tbaa [[TBAA2]]
// CHECK-NEXT:    tail call void asm sideeffect "", "y"(i8 [[TMP0]]) #[[ATTR1]], !srcloc [[META7:![0-9]+]]
// CHECK-NEXT:    ret void
//
void test_y() {
  asm volatile("" :: "y"(c));
}

// CHECK-LABEL: define dso_local void @test_R
// CHECK-SAME: () local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = load i8, ptr @c, align 1, !tbaa [[TBAA2]]
// CHECK-NEXT:    tail call void asm sideeffect "", "R"(i8 [[TMP0]]) #[[ATTR1]], !srcloc [[META8:![0-9]+]]
// CHECK-NEXT:    ret void
//
void test_R() {
  asm volatile("" :: "R"(c));
}

// CHECK-LABEL: define dso_local void @test_d
// CHECK-SAME: () local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = load i8, ptr @c, align 1, !tbaa [[TBAA2]]
// CHECK-NEXT:    tail call void asm sideeffect "", "d"(i8 [[TMP0]]) #[[ATTR1]], !srcloc [[META9:![0-9]+]]
// CHECK-NEXT:    ret void
//
void test_d() {
  asm volatile("" :: "d"(c));
}

// CHECK-LABEL: define dso_local void @test_c
// CHECK-SAME: () local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = load i8, ptr @b, align 1, !tbaa [[TBAA10:![0-9]+]], !range [[RNG12:![0-9]+]], !noundef [[META13:![0-9]+]]
// CHECK-NEXT:    [[TOBOOL:%.*]] = trunc nuw i8 [[TMP0]] to i1
// CHECK-NEXT:    tail call void asm sideeffect "", "c"(i1 [[TOBOOL]]) #[[ATTR1]], !srcloc [[META14:![0-9]+]]
// CHECK-NEXT:    ret void
//
void test_c() {
  asm volatile("" :: "c"(b));
}

// CHECK-LABEL: define dso_local void @test_v
// CHECK-SAME: () local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = load i8, ptr @b, align 1, !tbaa [[TBAA10]], !range [[RNG12]], !noundef [[META13]]
// CHECK-NEXT:    [[TOBOOL:%.*]] = trunc nuw i8 [[TMP0]] to i1
// CHECK-NEXT:    tail call void asm sideeffect "", "v"(i1 [[TOBOOL]]) #[[ATTR1]], !srcloc [[META15:![0-9]+]]
// CHECK-NEXT:    ret void
//
void test_v() {
  asm volatile("" :: "v"(b));
}

// CHECK-LABEL: define dso_local void @test_clobber
// CHECK-SAME: () local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    tail call void asm sideeffect "", "~{a}"() #[[ATTR1]], !srcloc [[META16:![0-9]+]]
// CHECK-NEXT:    tail call void asm sideeffect "", "~{x}"() #[[ATTR1]], !srcloc [[META17:![0-9]+]]
// CHECK-NEXT:    tail call void asm sideeffect "", "~{y}"() #[[ATTR1]], !srcloc [[META18:![0-9]+]]
// CHECK-NEXT:    tail call void asm sideeffect "", "~{c}"() #[[ATTR1]], !srcloc [[META19:![0-9]+]]
// CHECK-NEXT:    tail call void asm sideeffect "", "~{v}"() #[[ATTR1]], !srcloc [[META20:![0-9]+]]
// CHECK-NEXT:    tail call void asm sideeffect "", "~{p}"() #[[ATTR1]], !srcloc [[META21:![0-9]+]]
// CHECK-NEXT:    tail call void asm sideeffect "", "~{rc0}"() #[[ATTR1]], !srcloc [[META22:![0-9]+]]
// CHECK-NEXT:    tail call void asm sideeffect "", "~{rc31}"() #[[ATTR1]], !srcloc [[META23:![0-9]+]]
// CHECK-NEXT:    tail call void asm sideeffect "", "~{rs0}"() #[[ATTR1]], !srcloc [[META24:![0-9]+]]
// CHECK-NEXT:    tail call void asm sideeffect "", "~{rs15}"() #[[ATTR1]], !srcloc [[META25:![0-9]+]]
// CHECK-NEXT:    ret void
//
void test_clobber() {
  asm volatile("" ::: "a");
  asm volatile("" ::: "x");
  asm volatile("" ::: "y");
  asm volatile("" ::: "c");
  asm volatile("" ::: "v");
  asm volatile("" ::: "p");
  asm volatile("" ::: "rc0");
  asm volatile("" ::: "rc31");
  asm volatile("" ::: "rs0");
  asm volatile("" ::: "rs15");
}

// CHECK-LABEL: define dso_local void @test_leaf_asm
// CHECK-SAME: () local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    tail call void asm sideeffect "", ""() #[[ATTR2:[0-9]+]], !srcloc [[META26:![0-9]+]]
// CHECK-NEXT:    ret void
//
void test_leaf_asm() {
  __attribute__((leaf)) asm volatile("");
}
